package-lock.json, package.json
=> fix: Revert url loader

package-lock.json, package.json, src/app/utils/mail.ts
=> feat: merge release v4.32.1 back into develop branch

.travis.yml, CONTRIBUTING.md, README.md, docs/DEPLOYMENT_SETUP.md
FormSG is available as open source to the community, but questions remain on the available features, product roadmap and deployment instructions.
1. List the available features and provide clarity on the product/engineering roadmap
2. Provide clear instructions on how to start contributing based on GitHub issues listed
3. Provide an email to report security issues
4. Clarify that the project team welcomes "all contributions, bug reports, bug fixes, documentation improvements, enhancements, and ideas"
5. Clarify the infrastructure required to run the application in a cloud environment
These are modest improvements; more work is probably required for another project team to get the system deployed
Note: end-to-end tests have been disabled due to a probable concurrency bug. An example is …
=> Greater clarity for available features, project roadmap and deployment instructions; disable E2E tests

package-lock.json, package.json
Update package to use latest version of `spcp-auth-client`
=> chore: update spcp-auth-client library

.github/pull_request_template.md
This PR allows for contributors to not have to manually delete lines for a cleaner PR, and just insert wherever possible. The remaining text is the entirety of the template for example's sake.
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
**New environment variables**:
- `env var` : env var details
**New scripts**:
- `script` : script details
- `dependency` : dependency details
**New dev dependencies**:
- `dependency` : dependency details
=> chore: use comments for PR template guiding questions

package-lock.json, package.json
This PR upgrades MockPass to resolve a vulnerability with `node-forge`.
=> fix(deps-dev): run npm audit fix

src/public/modules/forms/admin/directiveViews/edit-captcha.client.view.html
=> chore: ui/copy changes

README.md
Acknowledge the contributions made by Tellform and its lead,
as well as those who have worked on FormSG who are not in
the commit log
=> docs(readme): acknowledge tellform, others

package-lock.json, package.json
=> build: revert "fix(deps): bump mongoose from 5.10.0 to 5.10.9"

src/app/services/myinfo/__tests__/myinfo.constants.spec.ts, src/app/services/myinfo/__tests__/myinfo.factory.spec.ts, src/app/services/myinfo/__tests__/myinfo.service.spec.ts, src/app/services/myinfo/__tests__/myinfo.test.constants.ts, src/app/services/myinfo/__tests__/myinfo.util.spec.ts, src/app/services/myinfo/__tests__/myinfo_hash.model.spec.ts
=> test: add tests for MyInfo TypeScript migration

src/app/modules/spcp/__tests__/spcp.controller.spec.ts, src/app/modules/spcp/__tests__/spcp.factory.spec.ts, src/app/modules/spcp/__tests__/spcp.routes.spec.ts, src/app/modules/spcp/__tests__/spcp.service.spec.ts, src/app/modules/spcp/__tests__/spcp.test.constants.ts
=> test: add tests for /spcp/validate

src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js, src/public/modules/forms/services/attachment.client.service.js, src/types/field/attachmentField.ts
Reverts opengovsg/FormSG#668 to incorporate further changes in #662
=> build: Revert "feat: Increase attachment size options"

src/public/main.css, src/public/modules/core/css/core.css, src/public/modules/forms/base/css/form.css, src/public/modules/forms/base/directiveViews/submit-form.directive.view.html, src/public/modules/users/css/privacy-tou.css, src/public/modules/users/views/static/privacy.client.view.html, src/public/modules/users/views/static/terms.client.view.html
This PR updates the TOU and PP of our application, and also updates public form footers for quick links to both the TOU and PP.
Note that the TOU and PP are both dated to 24th Nov 2020, for next Tuesday release.
Related to #369.
**Features**:
- update privacy policy page
- update terms of use page
- add TOU and PP to public form footer
Also tested on IE11, nothing looks off.
=> feat: update TOU + PP, update public form footer

src/app/modules/spcp/spcp.controller.ts, src/app/modules/spcp/spcp.routes.ts, src/app/modules/spcp/spcp.service.ts, src/app/modules/spcp/spcp.util.ts
This PR adds documentation for all the new functions introduced in the SPCP TypeScript migration.
=> docs: add documentation for new SPCP module

src/app/modules/spcp/__tests__/spcp.controller.spec.ts, src/app/modules/spcp/__tests__/spcp.factory.spec.ts, src/app/modules/spcp/__tests__/spcp.routes.spec.ts, src/app/modules/spcp/__tests__/spcp.service.spec.ts, src/app/modules/spcp/__tests__/spcp.test.constants.ts, tests/unit/backend/helpers/jest-express.ts
=> test: add tests for SPCP login endpoints

src/shared/util/file-validation.ts
This PR removes `.oa` files from the list of allowed file types
=> feat: remove .oa file from allowed file types

src/public/modules/forms/admin/componentViews/share-form.client.view.html, src/public/modules/forms/admin/css/share-form.css, src/public/translations/en-SG/main.json
=> chore: add Go and Postman tips on Share tab

src/public/modules/forms/services/submissions.client.factory.js
Closes #768
**BEFORE**:
**AFTER**:
=> chore: improve default submission error message

src/app/modules/submission/email-submission/__tests__/email-submission.service.spec.ts, tests/unit/backend/helpers/generate-email-data.ts, tests/unit/backend/helpers/generate-form-data.ts
=> test: add tests for prepareEmailSubmission

src/app/modules/submission/email-submission/__tests__/email-submission.receiver.spec.ts, src/app/modules/submission/email-submission/__tests__/email-submission.service.spec.ts, src/app/modules/submission/email-submission/__tests__/email-submission.util.spec.ts
=> test: add tests for validate- and receiveEmailSubmission

src/app/services/captcha/__tests__/captcha.factory.spec.ts, src/app/services/captcha/__tests__/captcha.service.spec.ts
=> test: add tests for Captcha

src/public/modules/forms/admin/views/edit-fields.client.modal.html
Closes #422 
Add `feature-toggle` and `feature-name=` attribute to the `div` containing the email domain restriction feature.
**AFTER**:
To be added
=> Put email domain restriction behind verified-fields feature toggle

src/app/modules/submission/email-submission/email-submission.types.ts, src/app/modules/submission/encrypt-submission/encrypt-submission.middleware.ts, src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts, src/app/modules/submission/submission.types.ts, src/app/routes/admin-forms.server.routes.js, src/app/utils/encryption.ts, src/app/utils/field-validation/validators/common.ts, src/app/utils/field-validation/validators/dateValidator.ts, src/app/utils/field-validation/validators/decimalValidator.ts, src/app/utils/field-validation/validators/homeNoValidator.ts, src/app/utils/field-validation/validators/mobileNoValidator.ts, src/app/utils/field-validation/validators/nricValidator.ts, src/app/utils/field-validation/validators/radioButtonValidator.ts, src/app/utils/field-validation/validators/ratingValidator.ts, src/app/utils/field-validation/validators/textValidator.ts, src/types/express.locals.ts, src/types/response/index.ts, tests/unit/backend/controllers/encrypt-submissions.server.controller.spec.js
Part of #144
- migrates validateAndProcessEncryptSubmission to typescript
=> refactor: validateAndProcessEncryptSubmission to typescript

src/app/modules/submission/__tests__/submission/submission.service.spec.ts, src/app/modules/submission/email-submission/__tests__/email-submission.service.spec.ts
=> test: add tests for email confirmation

package-lock.json, package.json
This PR upgrades the following packages to resolve vulnerabilities identified by Snyk:
- `file-loader`
- `babel-loader`
=> fix(deps): run Snyk wizard

Dockerfile.development, Dockerfile.production, docs/TROUBLESHOOTING.md, package.json
This PR upgrades our Node version to 12.20.0 as recommended by Snyk.
=> fix: upgrade node to 12.20.0

src/app/controllers/encrypt-submissions.server.controller.js, src/app/modules/submission/encrypt-submission/encrypt-submission.middleware.ts, src/app/modules/submission/encrypt-submission/encrypt-submission.types.ts, src/app/routes/admin-forms.server.routes.js, src/app/routes/public-forms.server.routes.js, tests/unit/backend/controllers/encrypt-submissions.server.controller.spec.js
Part of #144
- migrates prepareEncryptSubmission to typescript
=> refactor: prepareEncryptSubmission to typescript

src/app/modules/submission/email-submission/__tests__/email-submission.routes.spec.ts, src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.routes.spec.ts, tests/unit/backend/helpers/jest-db.ts
Adds integration tests for the following scenarios:
- SPCP cookie is valid
- SPCP cookie is present but cannot be decoded
- SPCP cookie is present but wrong type (eg CP cookie for SP form)
- SPCP cookie is not present
- SPCP cookie can be decoded but has wrong shape
=> test: add SPCP authentication integration tests

package-lock.json, package.json, src/public/main.js, src/public/modules/core/componentViews/navbar.html, src/public/modules/core/services/gtag.client.service.js, src/public/modules/forms/admin/controllers/view-responses.client.controller.js, src/public/modules/forms/admin/css/pop-up-modal.css, src/public/modules/forms/admin/css/view-responses.css, src/public/modules/forms/admin/views/decrypt-progress.client.modal.html, src/public/modules/forms/admin/views/download-all-attachments.client.modal.html, src/public/modules/forms/admin/views/view-responses.client.view.html, src/public/modules/forms/helpers/CsvMergedHeadersGenerator.js, src/public/modules/forms/helpers/decryption.worker.js, src/public/modules/forms/services/submissions.client.factory.js, tests/end-to-end/helpers/encrypt-mode.js, tests/end-to-end/helpers/selectors.js
This pull request adds the modal and other frontend features necessary to enable bulk attachment downloading.
This adds a dropdown and modal and otherwise uses the existing csvDownload and attachment download backends.
Closes #16
=> Bulk Attachment Download Frontend

package-lock.json, package.json, src/config/config.ts
Upgrades TypeScript to v4.1.3 and fixes type issues.
Replacement for #1009
=> build/typescript-4.1.3: TypeScript version upgrade

src/app/services/sms/sms.service.ts
=> feat: update SMS OTP message

src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts, src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts, src/app/modules/form/admin-form/__tests__/admin-form.utils.spec.ts, src/app/modules/form/admin-form/admin-form.types.ts, src/types/field/baseField.ts
=> tests: add tests for refactored update form flow

package-lock.json, package.json, src/app/modules/auth/auth.utils.ts, src/app/modules/billing/billing.controller.ts, src/app/modules/form/admin-form/admin-form.controller.ts, src/types/vendor/express.d.ts
Builds failing due to express-session types.
Revert #1141.
=> fix: Revert "chore: update package and typings for express session"

.github/dependabot.yml
=> chore: set dependabot to run at 1am singapore time

src/app/modules/verified-content/__tests__/__mocks__/verified-content.factory.ts, src/app/modules/verified-content/__tests__/verified-content.factory.spec.ts, src/app/modules/verified-content/__tests__/verified-content.middleware.spec.ts, src/app/modules/verified-content/__tests__/verified-content.utils.spec.ts, src/app/modules/verified-content/verified-content.middlewares.ts
This PR implements the missing unit tests for the `verified-content` module.
=> test: add missing modules/verified-content tests

src/public/modules/forms/base/componentViews/end-page.html, src/public/modules/forms/base/css/start-end-page.css
@syan-syan requested for the following changes:
1. Change "logged out from SingPass" to "logged out of SingPass".
2. Insert the "automatically logged out" line after the custom instructions, not before.
3. Insert extra spacing between the custom instructions and the "automatically logged out" line.
**Before**
**After**
=> style: update MyInfo end page styling

src/public/modules/forms/admin/directiveViews/verify-secret-key.client.view.html, src/public/translations/en-SG/main.json
Closes #1292 
Added golink to secret key loss instructions to Links
Changed copy on verify secret key client view and inserted link
=> chore: change copy & insert secretkeyloss golink 

package-lock.json, package.json
=> build: remove unused await-to-js

src/public/modules/forms/admin/directives/configure-mobile.client.directive.js
changed copy to better communicate verified SMS charges
=> chore: change verified sms modal copy

src/public/modules/forms/admin/directives/configure-mobile.client.directive.js, src/public/modules/forms/admin/views/edit-fields.client.modal.html
added currency to verified sms copy
corrected email confirmation tooltip
=> chore: copy changes

src/app/modules/webhook/__tests__/webhook.service.spec.ts
An import was accidentally imported from the built application `dist`  folder instead of the app.
This PR fixes that import.
=> fix(test): use app import instead of dist import

src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
Minor cleanup to avoid using `res.locals` in `handleEncryptedSubmission`
Removed uses of `res.locals`.
=> refactor: Minor cleanup to avoid using res.locals

src/app/modules/form/admin-form/__tests__/admin-form.routes.spec.ts, src/app/routes/api/v3/admin/forms/__tests__/admin-forms.submissions.routes.spec.ts
the test is flaky on travis but not on local, this is just an attempt to hopefully fix the flakiness
=> test: fix possibly flaky test by assigning constant to date

src/public/modules/forms/base/componentViews/field-textfield.client.view.html, src/public/modules/forms/base/components/field-textfield.client.component.js, src/public/modules/forms/base/directives/submit-form.directive.js
- Removes yellow highlight if prefill is enabled for field but url does not contain prefill value
=> feat: show highlights only if prefill is provided in url

src/app/models/__tests__/form.server.model.spec.ts, src/app/models/form.server.model.ts, src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts, src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts, src/app/modules/form/admin-form/admin-form.controller.ts, src/app/modules/form/admin-form/admin-form.service.ts, src/app/modules/form/form.utils.ts, src/app/routes/api/v3/admin/forms/__tests__/admin-forms.logic.routes.spec.ts, src/app/routes/api/v3/admin/forms/admin-forms.logic.routes.ts, src/public/modules/forms/admin/controllers/edit-logic-modal.client.controller.js, src/public/services/AdminFormService.ts, src/types/form.ts, src/types/form_logic.ts
Closes #1488
Test using manual API calls
=> refactor: extract update logic endpoint

src/public/modules/forms/admin/css/settings-form.css, src/public/modules/forms/admin/directiveViews/edit-captcha.client.view.html
Closes #1730 
**BEFORE**:
**AFTER**:
=> feat: add enable captcha infobox

src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
Closes #1854 
Adds relevant types
=> fix: add types to RequestHandler in submitEncryptModeForm

package-lock.json, package.json, src/app/models/admin_verification.server.model.ts, src/app/models/agency.server.model.ts, src/app/models/form.server.model.ts, src/app/models/form_feedback.server.model.ts, src/app/models/form_statistics_total.server.model.ts, src/app/models/login.server.model.ts, src/app/models/submission.server.model.ts, src/app/models/token.server.model.ts, src/app/models/user.server.model.ts, src/app/modules/bounce/bounce.model.ts, src/app/modules/myinfo/myinfo_hash.model.ts, src/app/modules/verification/verification.model.ts, src/app/services/sms/sms_count.server.model.ts, src/types/submission.ts
This PR updates `mongoose` to 5.12.12 and updates the types of our models due to having better mongoose types available now.
=> fix(deps): update mongoose to 5.12.12, update model types

README.md, docs/DEPLOYMENT_SETUP.md
Changes the following in the documentation:
- Updates product roadmap as per @syan-syan's suggestions
- Combines the separate sections on site banners in `README.md` and `DEPLOYMENT_SETUP.md` into `DEPLOYMENT_SETUP.MD`
- Updates `DEPLOYMENT_SETUP.md` to reflect the fact that feature-specific environment variables are now required
Part of #1842
=> docs(feature-manager): update docs to reflect FeatureManager removal

frontend/src/app/App.tsx, frontend/src/components/Button/Button.stories.tsx, frontend/src/components/Button/Button.tsx, frontend/src/components/IconButton/IconButton.stories.tsx, frontend/src/components/IconButton/IconButton.tsx, frontend/src/components/IconButton/index.ts, frontend/src/theme/components/Button.ts
Note that this PR builds on #2148 since IconButtons share a theme with buttons
This PR adds the IconButton component and story.
Closes #1998 
**Features**:
- feat: add IconButton component and story
=> feat(design-system): add IconButton component and story

src/app/modules/form/admin-form/admin-form.controller.ts
key has already been deleted from the schema, Joi validation can now be updated.
Closes #2177
=> feat(AdminFormCtl): remove read permissionList.read key from Joi

src/app/models/field/index.ts, src/app/models/field/uenField.ts, src/app/models/form.server.model.ts, src/app/utils/field-validation/answerValidator.factory.ts, src/app/utils/field-validation/validators/uenValidator.ts, src/public/main.js, src/public/modules/forms/base/componentViews/field-uen.client.view.html, src/public/modules/forms/base/components/field-uen.client.component.js, src/public/modules/forms/base/directiveViews/field.client.directive.view.html, src/public/modules/forms/base/directives/validate-uen.client.directive.js, src/public/modules/forms/base/resources/icon-types.js, src/public/modules/forms/helpers/field-factory.js, src/shared/resources/basic/index.ts, src/shared/util/uen-validation.ts, src/types/field/fieldTypes.ts, src/types/field/index.ts, src/types/field/uenField.ts, src/types/field/utils/guards.ts
Restores the UEN field feature, which was initially introduced in #2100 and refactored in #2156, then reverted in #2169.
- Due to new field type
=> feat: restore UEN field

src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts, src/app/modules/form/admin-form/admin-form.controller.ts, src/app/modules/submission/__tests__/submission/submission.service.spec.ts, src/app/modules/submission/email-submission/ParsedResponsesObject.class.ts, src/app/modules/submission/email-submission/__tests__/ParsedResponsesObject.class.spec.ts, src/app/modules/submission/email-submission/email-submission.controller.ts, src/app/modules/submission/email-submission/email-submission.types.ts, src/app/modules/submission/submission.service.ts
This reverts #2248, where it temporarily reverted commit 6512a84 to reduce risk for the next release.
=> refactor: revert the revert of encapsulate parsedResponses

frontend/package-lock.json, frontend/package.json, frontend/src/components/Field/YesNo/YesNo.stories.tsx, frontend/src/components/Field/YesNo/YesNo.tsx, frontend/src/components/Field/YesNo/YesNoOption.tsx, frontend/src/components/Field/YesNo/index.ts, frontend/src/theme/components/Button.ts, frontend/src/theme/components/Field/YesNo.ts, frontend/src/theme/components/index.ts, frontend/src/theme/foundations/breakpoints.ts, frontend/src/theme/foundations/colours.ts, frontend/src/theme/index.ts, frontend/src/utils/storybook.tsx
This PR adds the YesNo field component alongside with their stories. A Playground story is also created to check how it would work with React hook form.
Whilst working on this PR, also add breakpoints to the application according to design system so the component is mobile responsive.
Closes #2009 
**Features**:
- add breakpoints according to design system
- add YesNo presentation component
- add composite field playground component story
In storybook
- `react-hook-form` : updated to `7.8.8`
=> feat(design-system): add Field/YesNo component and stories, update react-hook-form, add more breakpoints

frontend/src/assets/icons/BxsHelpCircle.tsx, frontend/src/components/FormControl/FormLabel/FormLabel.stories.tsx, frontend/src/components/FormControl/FormLabel/FormLabel.tsx, frontend/src/components/FormControl/FormLabel/index.ts, frontend/src/theme/components/FormLabel.ts, frontend/src/theme/components/index.ts
This PR adds the FormLabel component.
Closes #2001
**Features**:
- Add `components/FormControl/FormLabel` component and stories
In generated storybook.
=> feat(design-system): add FormLabel component and stories

frontend/package-lock.json, frontend/package.json, frontend/src/components/Link/Link.stories.tsx, frontend/src/components/Link/Link.tsx, frontend/src/components/Link/index.ts, frontend/src/theme/components/Button.ts, frontend/src/theme/components/Link.ts, frontend/src/theme/components/index.ts, frontend/src/theme/index.ts
This PR adds the Link component.
Closes #2001
**Features**:
- Add `components/Link` component and stories
- styles(theme): enable fontFeatureSettings in global body style
- fix: correct usage of focus-visible with chakra's extend theme
**Dependency upgrades**:
- chore: bump chakra-ui/cli package to 1.4.0
In generated storybook.
=> feat(design-system): add Link component, stories; enable standard fonts across app

src/public/modules/forms/admin/css/settings-form.css, src/public/modules/forms/admin/directiveViews/settings-form.client.view.html, src/public/modules/forms/admin/directives/settings-form.client.directive.js
Reword and reorder the form auth options as indicated below:
*Desktop*
*Mobile*
=> fix(settings): reorder and reword auth options

frontend/package-lock.json, frontend/package.json, frontend/src/assets/icons/BxsInfoCircle.tsx, frontend/src/components/Banner/Banner.stories.tsx, frontend/src/components/Banner/Banner.tsx, frontend/src/theme/components/Banner.ts, frontend/src/theme/components/index.ts
> This PR builds on the Link component as banners are able to show links....
Creates the Banner component. Goes a step further and allows for markdown rendering inside the banner so we can have prettier and more accessible links.
Closes #2013 
**Features**:
- feat(theme): add multistyle config theme for Banner component
- feat(Banner): add component and stories
In storybook
- chore: add react-markdown package to allow markdown parsing
=> feat(design-system): add Banner component and stories

.github/dependabot.yml, .gitignore
wrong indentation sorry
somehow didn't fail any checks (makes sense since it won't run until its committed :/)
=> fix(form-v2): correct indentation in dependabot config

src/app/models/user.server.model.ts, src/types/api/user.ts, src/types/user.ts
=> fix(SGID): add sgid to User schema beta flags

package-lock.json, package.json
Followup to #2305 since we asked dependabot to shut up in #2106.
=> feat(deps): upgrade to latest TypeScript

shared/types/analytics.ts, src/public/services/AnalyticsService.ts, src/types/analytics.ts
This time for analytics
Related to #2066
- ref: extract analytics types to root shared folder
=> feat(shared-types): extract analytics types to root shared folder

frontend/src/assets/icons/BxCheckAnimated.tsx, frontend/src/assets/icons/index.ts, frontend/src/components/Checkbox/Checkbox.stories.tsx, frontend/src/components/Checkbox/Checkbox.tsx, frontend/src/components/Checkbox/index.ts, frontend/src/theme/components/Checkbox.ts, frontend/src/theme/components/index.ts
Part of #2008
Opening purely for code review first, will request design review when the rest of #2008 is complete.
=> feat(Checkbox): add individual checkbox and stories

.github/workflows/chromatic.yml
save on snapshotting unchanged stories, see https://www.chromatic.com/docs/turbosnap
=> chore: enable Chromatic Turbosnap

src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts, src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts
=> fix: update response limit error message for storage mode submissions

frontend/src/components/Radio/Radio.stories.tsx, frontend/src/components/Radio/Radio.tsx, frontend/src/components/Radio/index.ts, frontend/src/theme/components/Radio.ts, frontend/src/theme/components/index.ts
Part of #2008
Opening purely for code review first, will request design review when the rest of #2008 is complete.
=> feat(Radio): add individual radio and stories

src/app/config/config.ts, src/app/config/schema.ts, src/app/services/mail/__tests__/mail.service.spec.ts, src/app/services/mail/mail.service.ts, src/app/services/mail/mail.types.ts, src/app/services/mail/mail.utils.ts, src/app/utils/formatters.ts, src/app/views/templates/sms-verification-disabled-admin.server.view.html, src/app/views/templates/sms-verification-disabled-collab.server.view.html, src/app/views/templates/sms-verification-warning-admin.view.html, src/app/views/templates/sms-verification-warning-collab.view.html, src/app/views/templates/sms-verification-warning.view.html, src/public/modules/forms/admin/directives/configure-mobile.client.directive.js, src/types/config.ts
1. Update copywriting for emails 
2. Update `reply-to` in email
3. Update copywriting for modal (not yet confirmed)
4. log email disablings/sends
=> feat(sms-limiting): changes for mail/modal

src/app/services/mail/mail.service.ts
This PR fixes the bug where collab warning/disabled emails fail to send.
This occurs because the `form` param types passed into the functions to send the disabled/warning emails was not actually `IPopulatedForm`, and thus form.admin.email would have been undefined, resulting in a mail error where the emails failed to send.
=> fix(MailService): correct type, pass in original form admin as param

frontend/src/app/App.tsx, frontend/src/app/AppRouter.tsx, frontend/src/app/PrivateRoute.tsx, frontend/src/app/PublicRoute.tsx, frontend/src/constants/routes.ts, frontend/src/contexts/AuthContext.tsx, frontend/src/pages/login/LoginPage.tsx, frontend/src/pages/login/index.ts, frontend/src/pages/workspace/WorkspacePage.tsx, frontend/src/pages/workspace/index.ts
This PR adds the PrivateRoute and PublicRoute components as the base for any new routes in the future.
Additionally, an example AuthContext is created to allow a mock generated logged in or logged out states
=> feat(react): add Public and Private Route components

frontend/src/components/Tooltip/Tooltip.stories.tsx, frontend/src/components/Tooltip/Tooltip.tsx, frontend/src/components/Tooltip/index.ts, frontend/src/theme/components/Tooltip.ts, frontend/src/theme/components/index.ts
This PR implements the Tooltip component.
To test the displaying of the tooltip on tap on mobile devices, please use Chrome's developer tools to trigger a touch event.
Closes #2023
In storybook
=> feat(design-system): add Tooltip component, styles and stories

frontend/src/templates/Field/Uen/UenField.stories.tsx, frontend/src/templates/Field/Uen/UenField.test.tsx, frontend/src/templates/Field/Uen/UenField.tsx, frontend/src/utils/fieldValidation.ts
This PR implements component that takes in an UEN field schema and creates a field with validation.
Closes #2603 
Add unit tests using Storybook's stories
=> feat(react): add UenField component

src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
This PR enhances logging in the encrypt-submission controllers.
- Details ...
**Features**:
- feat: log sessionUserId in all encrypt-submission controllers
=> feat: log sessionUserId in all encrypt-submission controllers

README.md
This PR updates README.md to bring webhooks out of beta  (in documentation).
=> docs: update README.md to bring webhooks out of beta

frontend/.storybook/preview-head.html, frontend/src/components/Button/Button.tsx, frontend/src/components/Menu/Menu.stories.tsx, frontend/src/components/Menu/Menu.tsx, frontend/src/components/Menu/index.ts, frontend/src/theme/components/Menu.ts
There were slight variances in the Menu component as compared to the design. This PR attempts to correct those variances.
There are also some attempts to fix Chromatic snapshot flakiness on Menu and Tooltip stories by adding a font preload using Google fonts so the snapshot will not move that much.
- feat(Button): allow forwardRef
- style(Menu): update theme styling to better fit design
=> feat(v2): update Menu styling to better fit design

src/app/services/mail/mail.service.ts
Closes #3388
- Details ...
- Set up form with email field with OTP enabled. Publish form. Trigger email otp. Check that outcome of `transporter.sendMail()` is logged with messageId included.
=> feat: log ses message id

frontend/src/theme/utils/contrast.ts
=> fix(contrastUtils): remove errant console.log statement

.github/workflows/chromatic.yml
Accidentally pushed a commit (f2e39d56ddf2d6d70ca272d85d795fc548677ad3) into `form-v2/develop` branch when it was not ready... this PR fixes the bugs introduced.
=> fix(chromatic): remove storybookBaseDir, update autoAccept

docs/DEPLOYMENT_SETUP.md
Fixing some small nitpick inconsistencies
=> fix(docs): Add missing characters for consistency

frontend/src/assets/icons/BxsUser.tsx, frontend/src/components/Avatar/Avatar.stories.tsx, frontend/src/components/Avatar/Avatar.tsx, frontend/src/components/Avatar/index.ts, frontend/src/components/Menu/Menu.tsx, frontend/src/templates/AvatarMenu/AvatarMenu.stories.tsx, frontend/src/templates/AvatarMenu/AvatarMenu.tsx, frontend/src/templates/AvatarMenu/index.ts, frontend/src/theme/components/Avatar.ts, frontend/src/theme/components/AvatarMenu.ts, frontend/src/theme/components/index.ts
**Features**:
- add avatar component and stories. closes #2014
- note that as clarified with design, avatar does not have its own hover / active / focus styles, as it is wrapped in clear button
In storybook
=> feat(design-system): add avatar component and stories

src/public/modules/users/views/static/terms.client.view.html
Updating TOU to exclude HIPAA clauses on request of LEGL after they received updated info
=> chore: update TOU to exclude HIPAA clauses

src/app/modules/bounce/bounce.controller.ts, src/app/routes/api/v3/notifications/bounces/bounces.routes.ts
We tried to update the SNS topic endpoint but we forgot that we had to confirm the email...
=> feat(BounceController): log SNS topic confirmation notification emails

README.md
Add a new sentence about giving docker more RAM on Mac OS or else it may not build the existing Angular based frontend.
=> chore: Add a new sentence about giving docker more RAM on Mac OS

src/app/modules/bounce/bounce.controller.ts
This reverts commit 2a28e5dc8c85726fcaa88e25e786b84270a6c55f.
=> revert: log SNS topic confirmation notification emails

frontend/src/features/admin-form/create/logic/CreatePageLogicTab.stories.tsx, frontend/src/features/admin-form/create/logic/components/LogicContent/HeaderBlock.tsx, frontend/src/features/admin-form/create/logic/components/LogicContent/LogicBlock/LogicBadge.tsx, frontend/src/features/admin-form/create/logic/components/LogicContent/LogicBlock/LogicBlock.tsx, frontend/src/features/admin-form/create/logic/components/LogicContent/LogicBlock/LogicConditionValues.tsx, frontend/src/features/admin-form/create/logic/components/LogicContent/LogicContent.tsx, frontend/src/features/admin-form/create/logic/utils.ts
Logic design has changed. Update client to look like design.
Storybook should reflect new design
=> feat(v2): update styling of admin logic content page

frontend/package-lock.json
by running npx browserslist@latest --update-db
=> fix(v2/deps): update browserlist

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/BuilderAndDesignContent.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/FieldRow/FieldRowContainer.tsx, frontend/src/features/admin-form/create/builder-and-design/utils/questionNumbers.ts, frontend/src/features/admin-form/create/constants.ts
Form builder currently does not contain question numbers.
Calculate and render question numbers. However, note that this approach is only temporary so that the form builder can go through design review. It will be subsequently be refactored based on #3625 (the approach in #3625 requires fairly extensive changes, so I avoided duplicating it here to avoid merge conflicts).
=> feat: add question numbers in form builder

frontend/src/features/public-form/PublicFormPage.stories.tsx, frontend/src/features/public-form/PublicFormProvider.tsx, frontend/src/features/public-form/components/FormFields/FormFieldsContainer.tsx, frontend/src/mocks/msw/handlers/public-form.ts
This PR adds design and styling fixes that were missed in the epic chain.
- feat(msw/public-form): remove default form logic on form mock
- add `PublicFormPage/WithLogic` story
**Bug Fixes**:
- fix(PublicFormProvider): do not provide sitekey if captcha is disabled
- captchaKey may be available and triggered even if captcha is disabled. This may lead to errors where recaptcha script tries to initiate but is unable to inject itself into the dom (since the div is not instantiated when there is no captcha needed)
- style(FormFieldsContainer): remove excess padding 
- fix(msw/public-form): correctly merge overrides without mutation
Stories should now have minimal changes:
- add question number
- add WithLogic story
Everything else should remain the same.
=> feat(v2/submit): design and squash fixes

frontend/src/features/admin-form/AdminFormSettingsPage.stories.tsx
import changed in #3695 but both were merged at the same time
=> fix(v2/AdminFormSettingsPage): update msw handler import

frontend/src/features/logic/constants.ts, frontend/src/features/logic/types.ts, shared/types/form/form_logic.ts
Build failure due to missing import. This PR moves the missing type from `src/shared` to `/shared`  to be imported.
=> fix(shared/logic): move and import LogicCondition type into /shared

Dockerfile.development, docker-compose.yml, init-mongo.js
While trying to get replica sets working in local development (to better mirror prod/staging), realize a better image that streamlines the process pretty well. 
This PR updates the mongodb image used and the init script.
=> chore(docker-compose): change mongo image to bitnami/mongodb:4.4

frontend/src/features/logic/utils/getVisibleFieldIds.ts, frontend/src/features/logic/utils/typeguards.ts
bug introduced in #3755 where it was merged before verifying that it built...
=> fix(v2/logic): use correct import path for LogicableFields

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditCheckbox.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditHeader.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditNric.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditRadio.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditUen.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditYesNo.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/common/FormFieldDrawerActions.tsx, frontend/src/features/admin-form/settings/components/WebhooksSection/RetryToggle.tsx, frontend/src/mocks/msw/handlers/admin-form/form.ts
Design review of #3698 revealed some design discrepancies. Instead of polluting that PR with unrelated fixes, this PR is opened to fix those flagged issues.
- style(FormFieldDrawerActions): remove min-width on button 
- feat(EditField): add mobile styling to drawer actions
**Bug Fixes**:
- fix(msw): update form handlers to use cuid instead of deterministic id
=> feat(v2): admin builder style fixes

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/FieldRow/FieldRowContainer.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditParagraph.tsx, frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/index.ts, frontend/src/features/admin-form/create/builder-and-design/utils/fieldCreation.ts
_Depends on #3695_
Implements field builder for Paragraph (aka Statement) fields.
=> feat: implement paragraph field editing

docs/TROUBLESHOOTING.md
Reopening #3783 with the right branch name.
=> fix: Update TROUBLESHOOTING.md with MongoDB not primary error

frontend/package-lock.json
=> chore(v2): run npx browserslist@latest --update-db

package-lock.json, package.json
it broke AngularJS building in this branch for some reason...
=> fix: downgrade @babel/preset-env package to 7.17.10

docs/DEPLOYMENT_SETUP.md, src/app/config/schema.ts, src/app/modules/verification/__tests__/verification.routes.spec.ts, src/app/modules/verification/verification.routes.ts, src/app/routes/api/v3/forms/__tests__/public-forms.verification.routes.spec.ts, src/app/routes/api/v3/forms/public-forms.verification.routes.ts
Closes [#129](https://github.com/datagovsg/formsg-private/issues/129)
=> feat: rate limit for otp generation
