src/app/models/sms_count.server.model.ts
src/types/agency.ts
src/types/field/baseField.ts
src/types/form.ts
src/types/form_feedback.ts
src/types/form_logic.ts
src/types/form_statistics_total.ts
src/types/login.ts
src/types/myinfo_hash.ts
src/types/sms_count.ts
src/types/submission.ts
src/types/token.ts
src/types/user.ts

We have two interfaces for each model, one for plain objects and one for Mongoose documents. For example, we have `IForm` for plain Form objects, and `IFormSchema` for documents retrieved from the database. However, none of our interfaces for plain objects include an `_id` key, despite the fact that all objects retrieved from the database have an `_id` key which we frequently access. This makes it difficult for us to write typed code for objects retrieved from the database, as every time we need to access the `_id` key, we have to create a union type.
Add an `_id` key to all relevant interfaces. The following interfaces were excluded because we set `_id: false` in the schema:
- Form logo
- Custom form logo
- MyInfo schema (part of baseField)
- Columns in table fields
The disadvantage of …

refactor: add _id to all model interfaces

---

package-lock.json
package.json
src/shared/constants.ts

While migrating `src/shared/constants.js` to TypeScript, one of the enum fields was accidentally changed from uppercase to sentence case. This caused a problem where old clients were not able to create form fields. This release fixes the issue.

build: Release 4.30.1 - Fix field creation on old clients

---

src/app/models/form.server.model.ts

Slow queries in production for the dashboard page were the result of collection scans from a lack of relevant indexes on the form schema. The query logic requires that a form be loaded if the user is either an admin or collaborator.
Create two indexes for each query - admin or collaborator as advised by the Mongo Performance Advisor.

feat(FormSchema): New indexes for form dashboard

---

scripts/remove-unused-flags/remove-allow-sms.js
src/app/controllers/authentication.server.controller.js
src/app/models/user.server.model.ts
src/app/utils/beta-permissions/index.js
src/app/utils/beta-permissions/sms.js
src/public/modules/forms/admin/directiveViews/configure-mobile.client.view.html
src/public/modules/forms/admin/directives/configure-mobile.client.directive.js
src/public/modules/forms/services/betas.client.factory.js
src/types/user.ts
tests/unit/backend/controllers/authentication.server.controller.spec.js

This PR removes the beta flag which blocks users from accessing the mobile number verification feature.

feat: remove allowSms beta flag

---

.github/dependabot.yml

This PR fixes dependabot errors due to using v1 syntax instead of the newer v2 syntax. :(
The config has now been tested with https://dependabot.com/docs/config-file/validator/ and is valid.

fix: update dependabot config to use v2 syntax

---

src/shared/util/phone-num-validation.ts

This PR adds an even strong mobile validation (only for Singapore numbers). SG phone number validation now only accepts 8 digit numbers starting with `8` or `9` using a regex match: 
```ts
nationalNumber.match(/^[89][0-9]{7}$/g)
```
Closes #100
**Bug Fixes**:
- Increases mobile validation strength by also validating the start of the number in addition to the number length.
**BEFORE**:
**AFTER**:

fix: phone validation now only accepts 8 digit #s starting with 8 or 9

---

src/app/utils/request.js
src/app/utils/request.ts

Migrates `utils/request` to Typescript
Related to #8

refactor: migrate `utils/request` to Typescript

---

tests/unit/backend/models/verification.server.model.spec.js

test: add tests for verification model

---

src/app/controllers/encrypt-submissions.server.controller.js
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/admin/views/view-responses.client.view.html
src/public/modules/forms/services/submissions.client.factory.js

Users have trouble finding specific responses and trying to download attachments for these responses.
This introduces a new textbox which filters submissions by reference ID so users can jump to a certain response immediately.

feat: Filter Storage Mode Responses by Submission Id

---

package-lock.json
package.json
src/config/config.ts
src/config/logger.ts

1. In the current release, logs from our `/emailnotifications` endpoint are going to the main log group instead of the custom log group `formsg-email-notifications-production`. This means that our bounce alarms are on the wrong log group, and email logs are being stored for a year instead of a week as intended.
2. An extra trailing `/` was introduced to the AWS endpoint during the TypeScript migration, breaking all image, logo and attachment uploads and downloads.
1. The problem was that during the TypeScript migration for `src/config/logger`, the AWS and CloudWatch environment variables were modified to be imported from `config` instead of taken directly from `process.env`. This caused them to be undefined because `config` depends on `logger`, resulting in a circular dependency. The …

Release 4.30.2 - fix AWS endpoint and /emailnotifications log group

---

README.md

Readme was still pointing at the old `datagovsg/formsg` repository. There were also some formatting issues flagged by the local IDE markdown linter.
* Update the build status to point to this repository's release branch
* Move the title up
* Fix syntax issues highlighted by the markdown linter

docs(readme): point build status image to new repo, improve formatting

---

src/public/modules/forms/base/views/submit-form.client.view.html

In the case of a MyInfo error, the form fields are being shown instead of the error message.
The issue is that the submit form controller is passing `vm.myInfoError` to the submit form directive via an attribute called `myinfo-error`, whereas the submit form directive is reading it as `myInfoError` (note uppercase I) instead of `myinfoError` (note lowercase i). The solution is to change the attribute to `my-info-error` (note extra hyphen) so it can be read correctly as `myInfoError`(note uppercase I).
The following screenshots are after setting `myInfoError` to `true` in `SubmitFormController`.

fix: fix myInfoError typo

---

src/config/config.ts

This PR removes the now unused mongoTimestamp plugin, since we have mongoose's own timestamp plugin.

feat: remove unused mongoTimestamp plugin

---

src/public/modules/forms/base/componentViews/field-attachment.client.view.html
src/public/modules/forms/base/components/field-attachment.client.component.js

We have a high frequency of "Required but no attachment content" validation errors from attachment fields, meaning the user and the frontend think that the attachment was uploaded successfully, but the backend discovers that the attachment content is actually missing. These errors occur almost exclusively on Android phones.
Closes #23 
The error occurs when the user attempts to upload a file directly from Google Drive. The UI behaves as if the file has been uploaded correctly, but in fact `FileReader` has failed silently because we have not set an error handler on it.
The ideal solution would be to fix file uploads from Google Drive, but this is unlikely to be straightforward and likely to introduce a lot of special cases in the code since Google Drive files clearly behave differently …

feat: show error upon FileReader failure

---

package.json

Certain refactorings seem to have removed the webpack watch flag from the `build-frontend-dev` script.
This PR adds it back.

chore: add --watch flag back to build-frontend-dev script

---

src/app/controllers/email-submissions.server.controller.js

If we have security incidents involving potentially malicious IP addresses, it is important to be able to trace the IP back to specific submission IDs. This is currently not possible as we do not log the IP together with the form and submission IDs.
Closes #129 
Add the form ID and IP address to our submission log string.

feat: log IP, submissionId and formId together

---

src/app/controllers/authentication.server.controller.js
src/app/views/templates/otp-email.server.view.html

Closes #140
Add in the user's ip address to the email sent to admin.
**BEFORE**:
**AFTER**:

feat: include user ip address when sending otp

---

src/app/services/myinfo.service.js
tests/unit/backend/services/myinfo.service.spec.ts

MyInfo circuit breaker is too sensitive, potentially resulting in many users getting locked out of MyInfo unnecessarily.
Closes #118 
Decrease the sensitivity by:
1. Increasing the statistical window from 10s (default) to 30s. This means that, over 30s, at least 80% of requests to MyInfo must take at least 5s in order for the breaker to open.
2. Increasing the volume threshold from 0 (default) to 5. This means that within the 30s statistical window, there must be at least 5 requests which take at least 5s in order for the breaker to open.

feat: increase breaker window time and add volume threshold

---

src/app/services/sms.service.ts

This PR enables the `forceDelivery` option on Twilio to attempt to send messages without validating against `libphonenumber` (which has delays when new mobile numbers are issued).
Closes #177

fix: enable forceDelivery on twilio message sending

---

src/public/modules/core/services/gtag.client.service.js
src/public/modules/forms/admin/controllers/create-form-modal.client.controller.js
src/public/modules/forms/admin/css/pop-up-modal.css
src/public/modules/forms/admin/views/create-form.client.modal.html

People lose their secret keys, thus losing all responses.
Addresses #9, but not fully as design is not finalised.
Update the warning in the secret key modal to include guidelines for safekeeping secret keys, and add a convenient mailto URL to encourage users to share their secret keys.

feat: mailto link for secret key

---

package-lock.json
package.json

**Rationale**
1. Minimal [breaking changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#breaking-changes) in TS4, and the breaking changes shouldn't affect us anyway.
2. A lot of useful new features, e.g. `??=` assignment operator.
3. 4.0.2 - 3.9.7 = 0.0.5 which doesn't seem like that big of a change.

chore(deps-dev): bump typescript to 4.0.2

---

src/app/modules/core/core.errors.ts

This PR adds a core `ApplicationError` class for easy wrapping and consistent handling of errors in the express application:
```ts
constructor(message?: string, status?: number, meta?: string)
```
It has 2 extra parameters `status` and `meta` as compared to the `Error` class it extends from. See the documentation in the class for more details.
```ts
import HttpStatus from 'http-status-codes'
import { ApplicationError } from '../core/core.errors'
export class InvalidOtpError extends ApplicationError {
constructor(message: string, meta?: string) {
super(message, HttpStatus.UNPROCESSABLE_ENTITY, meta)
}
}
export class MalformedOtpError extends ApplicationError {
constructor(
message: string = 'Malformed OTP. Please try again later. If the problem persists, contact us.',
meta?: string,
) { …
```

feat: add core ApplicationError for express app

---

src/public/modules/core/services/gtag.client.service.js
src/public/modules/forms/admin/controllers/view-responses.client.controller.js

Builds on PR #154 to avoid userEmail unintentionally being sent as a query parameter
- Shift retrieval of userEmail to GA service

fix: shift userEmail retrieval to GA service

---

src/public/modules/forms/admin/controllers/view-responses.client.controller.js

Users have to repeatedly enter their form secret key if they open multiple tabs with the same form. This hinders future bulk downloading of attachments (Issue #16) because there are multiple clicks involved in unlocking a response from a tab.
We utilize `BroadcastChannel` to request and broadcast the form secret key to other tabs.
- Open two tabs and navigate to the View Responses page of a storage mode form. Upload a secret key to one form to unlock. The other tab should be unlocked automatically.
- Unlock responses on one form. Open a second tab and go to view responses. The tab should already be unlocked.
`BroadcastChannel` will only broadcast the message to scripts from the same origin (i.e. `https://form.gov.sg` in practice) so all data should be controlled by scripts originating …

feat: Share form secret keys across browser tabs using BroadcastChannel

---

src/public/modules/core/controllers/edit-contact-number-modal.client.controller.js

Hotfix for missing param in `EditContactNumberModalController`. 
edit: why did it work on staging though :hmm:
edit2: it worked because Auth always passed during test, meaning $state will not get invoked.

fix: pass missing $state param into EditContactNumberModalController

---

package-lock.json
package.json
src/app/utils/mail.ts

Hotfix for valid mail being rejected as invalid due to being split by semicolons `;` instead of commas `,`.
This is due to legacy forms having their emails split by semicolons in the past.

fix: Hotfix v4.32.1 -- split mail by semicolon in addition to comma when validating

---

src/public/modules/forms/admin/components/response-components/response-attachment.client.component.js
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/admin/css/view-responses.css
src/public/modules/forms/admin/views/view-responses.client.view.html
src/public/modules/forms/services/submissions.client.factory.js

Users have complained that managing high volume forms with lots of attachments is hard.
This adds a feature which allows users to download all attachments from a particular respondent with one click. The download attachment link will only show up when there is at least one attachment in the submission.

feat: Bulk download of storage mode attachments in a zip file

---

src/public/main.js
src/public/modules/core/css/core.css
src/public/modules/forms/admin/controllers/activate-form-modal.client.controller.js
src/public/modules/forms/admin/controllers/create-form-modal.client.controller.js
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/forms/services/mailto.client.factory.js
src/public/modules/forms/services/toastr.client.factory.js

feat: mailto option after form activation

---

src/app/controllers/authentication.server.controller.js
src/app/routes/admin-forms.server.routes.js
tests/unit/backend/controllers/authentication.server.controller.spec.js

Imports for `src/app/utils/permission-levels` are broken after TS migration.
Remove filetype from imports.

fix: remove filetype from permission levels imports

---

src/app/modules/bounce/bounce.service.ts

As requested by @syan-syan, we should log more information about critical bounces so the information is easier to access.

feat: log more info about critical bounces

---

src/public/modules/forms/admin/css/view-responses.css
src/public/modules/forms/admin/directiveViews/verify-secret-key-activation.client.view.html

This PR fixes a small misalignment in the error message box when typing in the storage mode acknowledgment input.
**BEFORE**:
**AFTER**:

fix: correct left margin in acknowledgment error when activating storage mode form

---

src/public/modules/forms/admin/controllers/view-responses.client.controller.js

Question number for storage mode bulk download is off by one.
This is because there was a mistaken `- 1` when setting the question number, so this was removed.

fix: fix off by one for storage mode bulk attachment downloads

---

src/app/models/form.server.model.ts
src/app/models/submission.server.model.ts
src/types/form.ts
tests/unit/backend/controllers/email-submissions.server.controller.spec.js
tests/unit/backend/models/form.server.model.spec.ts

Using `EncryptSubmission` Model without having compiled `Submission` Model causes `EncryptSubmission` Model to be without core keys like `form`
This problem extends to `Form` model as well.
Closes #243
**Bug Fixes**:
- Fix possible race conditions by only returning discriminated models after compiling/retrieving their base instead of compiling from scratch.
Note: The usual way of exporting discriminated models should be employed once we have fully migrated over to Typescript.
```ts
export const EmailFormModel = FormModel.discriminator(ResponseMode.Email, EmailFormSchema)
export const EncryptFormModel = FormModel.discriminator(ResponseMode.Encrypt, EncryptedFormSchema)
```

fix: prevent discriminated models from being created before their base model

---

docker-compose.yml
docs/DEPLOYMENT_SETUP.md
init-localstack.sh
src/config/config.ts

All Localstack services (image upload, logo upload, storage mode attachments) were not working.
Closes #202 
In their latest version, [the `awslocal` CLI](https://github.com/localstack/awscli-local) switched to using the edge port 4566 for all services by default. However, this edge port is not available to us, since we are using an older version of Localstack. Hence it is now necessary to specify the endpoint URL in `init-localstack.sh` when creating the S3 buckets.
All actions involving S3 require the global `AWS` object to have its credentials configured. Since we removed the mock AWS credentials, those credentials could no longer be set, resulting in all S3 operations failing. The solution was to restore the mock credentials to `docker-compose`.
Sadly, the …

fix(dev): fix Localstack yet again

---

docs/DEPLOYMENT_SETUP.md
package-lock.json
package.json
src/config/feature-manager/sentry.config.ts
src/public/main.js

The Raven SDK is outdated. From the [Sentry repo](https://github.com/getsentry/sentry-javascript):
> raven-js: Our old stable JavaScript SDK, we still support and release bug fixes for the SDK but all new features will be implemented in @sentry/browser which is the successor.
This PR upgrades our Sentry SDK to the latest version, and adds the [AngularJS plugin](https://docs.sentry.io/platforms/javascript/guides/angular/angular1/).

feat: upgrade Sentry SDK

---

docs/DEPLOYMENT_SETUP.md
src/config/config.ts

The following environment variables are deprecated by Nodemailer and verified to be no longer in use in production
* SES_RATE
* SES_RATELIMIT
Removed aforementioned environment variables from the codebase.
Additionally, addressed Markdown linting issues in the deployment setup
file.
- Improved code cleanliness
- Improved documentation
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
**Removed environment variables**:
* SES_RATE
* SES_RATELIMIT

refactor: remove unused Nodemailer env vars

---

scripts/date-logic/date-logic.js
scripts/date-logic/remove-isfutureonly-key.js
src/app/controllers/admin-forms.server.controller.js
src/app/models/field/dateField.ts
src/public/modules/forms/services/form-api.client.factory.js

Closes #40 
Create 5 date fields in admin view with the following options. Test that the validations work in the preview panel datepicker on the right (i.e. the popup calendar).
Validation for date range validation option in admin view
Able to submit forms correctly
Test for editing and reordering, instead of creating
- DB script in remove-isfutureonly-key.js, to be run one week after release

chore: remove form_field.isFutureOnly key

---

src/config/config.ts

Not sure why `promisify` didn't work. Testing this fix on staging now.
Edit: deployed to staging successfully

fix: revert changes to configureAws

---

docker-compose.yml

The [issue](https://github.com/localstack/localstack/issues/2407) which was holding back our Localstack version has now been resolved, so we can upgrade to the latest version.
**However, the edge port 4566 still doesn't work.** I keep running into the error `Unable to find forwarding rule for host` when doing `docker-compose`, and from the Localstack repo it seems that many other folks are running into issues with the edge port as well. Hence we are sticking to 4572 for now.

feat: upgrade localstack version

---

src/app/modules/user/user.controller.ts
src/loaders/express/error-handler.ts
src/loaders/mongoose.ts

This PR cleans up remnants of logger invocations that does not adhere to the expected format.
Typescript did not complain due to the `any` type of the parameters being passed in :(

fix: fix invocations of logger that does not adhere to expected shape

---

src/config/logger.ts

JavaScript files will not throw any error when the wrong argument signature is passed into logger invocations. Add try catch block as a defensive measure at least until the application is 100% typescript, to prevent possible errors from being thrown due to the wrong type

feat: add try-catch block to custom logger for js files

---

src/public/modules/forms/admin/directiveViews/configure-mobile.client.view.html
src/public/modules/forms/admin/directives/configure-mobile.client.directive.js
src/public/modules/forms/admin/directives/edit-form.client.directive.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html

Closes https://github.com/opengovsg/FormSG/issues/184
_Desktop_
_Mobile_

feat: verified sms modal

---

src/loaders/express/index.ts

Closes https://github.com/datagovsg/formsg-private/issues/33

refactor(proxy): do not override X-Forwarded-Proto headers

---

src/loaders/express/helmet.ts

Since the last release a week ago, Sentry has had 1.2m events due to CSP errors. While the errors do not seem to affect any functionality, they are likely to cause us to burst our Sentry limits again.
In particular, there are problems caused by the `angular-sanitize` package, which show up in both the `form.gov.sg` landing page and all public forms:
As well as problems due to the `jquery` package, which show up in the `form.gov.sg` landing page:
Allow inline styles from `angular-sanitize.js` by adding the relevant hash to the allowed `style-src` list. This fixes the issue on public forms:
However, the issue with `jquery` is less straightforward because it sets attributes rather than inline style tags, so we [cannot use a hash](https://stackoverflow.com/questions/52724956/why-doesnt-chrome- …

fix: allow inline styles from angular-sanitize in CSP

---

src/public/modules/forms/admin/directiveViews/edit-captcha.client.view.html
src/public/modules/forms/admin/directives/verify-secret-key.client.directive.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/services/captcha.client.service.js
src/public/modules/users/views/static/privacy.client.view.html

feat: update copy for email fields, intranet, privacy

---

package-lock.json
package.json

`npm audit fix` suggested the following changes:
1. Upgrade `bl` (dependency of `mongoose`, `connect-mongo`, `puppeteer-core`, `@shelf/jest-mongodb`.
2. Upgrade `mongodb-memory-server-core` ([breaking changes in v6](https://github.com/nodkz/mongodb-memory-server/blob/master/CHANGELOG.md#600-2019-10-22)). This is a dev dependency and should not affect production.
3. Upgrade `minimist` (dependency of `selectize`).
`bl` and `mongodb-memory-server-core` were updated. I tested form and field creation/modification/deletion and autoreply PDF on staging-alt and everything seemed to work fine.
I did not upgrade `minimist` as it is a low-severity vulnerability and a frontend dependency, so it is unlikely to be worth fixing ahead of React migration.

fix(deps): fix npm audit issues

---

package.json
tests/end-to-end/encrypt-submission.e2e.js
tests/end-to-end/helpers/all-fields.js
tests/end-to-end/helpers/all-hidden-form.js

Localstack keeps making breaking changes which cause our CI pipeline to fail. This is particularly harmful in cases where we need to make an urgent hotfix e.g. #333.
Remove Localstack as a dependency from our end-to-end tests. We should remember to test storage mode attachments manually before every release.

build: remove Localstack from end-to-end tests

---

src/config/config.ts

Lots of console log spam in tests due to the silencing check in `logger.ts` not working. This PR fixes the conditional by assigning `config.nodeEnv` in dev environment properly.

fix: set nodeEnv to assigned variable if in dev environment

---

.travis.yml
docker-compose.yml

Travis will now install a pinned version of `localstack` and use Travis's [chrome addon](https://docs.travis-ci.com/user/chrome) instead of downloading from `apt`. This PR also cleans up the redundant script installations such as `fluxbox` (which from tracing past commits seems to have been used to start browsers for e2e tests which are now not required).
This PR also pins the `localstack` version in docker-compose to `0.11.5`, which prevents any commits in `localstack:master` (which is then pushed to `latest` in Dockerhub) from causing any build failures (if any) suddenly.

chore: update travis.yml and pin localstack in docker-compose

---

.travis.yml

Accidentally removed it from travis.yml thinking that it was `awslocal`

chore: add awscli back to toolchain

---

src/types/user.ts

The types for `User` use a key called `betaFlag` which should actually be called `betaFlags` according to `user.server.model.ts`.

fix: specify betaFlags key correctly

---

src/app/controllers/encrypt-submissions.server.controller.js
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/admin/css/export-button.css
src/public/modules/forms/admin/css/view-responses.css
src/public/modules/forms/admin/views/view-responses.client.view.html
src/public/modules/forms/services/submissions.client.factory.js

Reverts #174 as pre-release tests revealed long-running db queries on secondary

fix: Revert "feat: Filter Storage Mode Responses by Submission Id"

---

src/types/bounce.ts

`bounceType` was made optional in #318  for backwards compatibility reasons, since old Bounce collection documents would not have that key. Since documents in the Bounce collection expire after 24h, it is now safe to make the key required.

refactor: make bounceType required

---

.travis.yml
Dockerfile.development
Dockerfile.production
docs/TROUBLESHOOTING.md
package-lock.json
package.json

Closes [#10](https://github.com/datagovsg/formsg-private/issues/10)
- Upgrade both node and alpine to address vulnerabilities
- node:12.18.0-alpine3.11 -> node:12.18.4-alpine3.12
- Upgrade chromium to v83 to correspond to alpine v3.12.0
- Downgrade puppeteer-core to v3.1.0 to correspond to chromium v83 (it appears to have been erroneously bumped up to v5.2.1 previously)

fix(deps): upgrade node, alpine and chromium

---

package-lock.json
package.json
src/app/models/user.server.model.ts
src/app/modules/user/user.service.ts
src/types/user.ts
tests/unit/backend/@types/vendor/@shelf/jest-mongodb/setup.d.ts
tests/unit/backend/@types/vendor/@shelf/jest-mongodb/teardown.d.ts
tests/unit/backend/helpers/jest-db.ts
tests/unit/backend/models/user.server.model.spec.ts
tests/unit/backend/modules/user/user.service.spec.ts

This PR adds a new `lastAccessed` key in the `User` collection which gets updated every time the user's document is retrieved when the user logs into the application.
This PR also adds a new `updatedAt` key which is only updated when contact is updated for now. The `timestamp` plugin is not used as updating the `lastAccessed` key will also inadvertently update the `updatedAt` key, which is not the behaviour we want.
Closes #345
**Features**:
- add `lastAccessed` and `updatedAt` keys to User model which gets updated when user logins and when new user is created/user updates their contact respectively.

feat: add `lastAccessed` key to track user login

---

src/app/controllers/admin-console.server.controller.js

`searchSubmissionsForForm` aggregate pipeline step was incorrectly matching against a key of `key` instead of the key parameter passed into the function:
```ts
let searchSubmissionsForForm = (key, formId) => [
{
$match: {
// key "key" is matched instead of the key parameter.
key: mongoose.Types.ObjectId(formId),
},
},
]
```
This PR fixes that by correctly using the given key parameter as a match key:
```ts
let searchSubmissionsForForm = (key, formId) => [
{
$match: {
[key]: mongoose.Types.ObjectId(formId),
},
},
]
```

fix: invalid key reference in retrieving form submissions

---

src/public/modules/core/css/avatar-dropdown.css

Styling for avatar dropdown is not great if the email is long -- the avatar circle gets squished, whilst the email text expands outside of its parent.
This PR fixes that by correcting the CSS styling.

fix: correct squished styling when user emails are too long

---

src/app/models/field/emailField.ts
src/public/modules/forms/admin/directives/validate-email-domain-from-text.directive.js
src/shared/util/email-domain-validation.ts

Currently, email domain validation is done via regex. We would like to use `validator.isEmail` to validate email domains. In order to use `isEmail`, we will prepend email domains with a string i.e. "bob".
Closes #54 
I put in a lot of thought before finally deciding on "bob". I wanted something short and not nonsensical like abc.
I received these linting errors:
```bash
/Users/jiayee/FormSG/src/app/models/field/emailField.ts
7:32  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
/Users/jiayee/FormSG/src/public/modules/forms/admin/directives/validate-email-domain-from-text.directive.js
3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'
```
As such, I had to do the following extra stuff:
1. `const …

refactor: use validator's isEmail for validating email domains

---

src/public/modules/core/componentViews/avatar-dropdown.html
src/public/modules/core/components/avatar-dropdown.client.component.js

In staging alt, even if the sms feature is not turned on, the exclamation will show, since the conditional is whether the user has a contact number or not. However, that results in an exclamation mark that cannot be removed:
This PR updates the conditional to only show the exclamation mark if the sms feature is available AND when the user has no contact number: 
```diff
- showExclamation = !vm.user.contact
+ showExclamation = features.sms && !vm.user.contact
```

fix: only show exclamation in navbar if sms feature is enabled

---

src/public/modules/forms/admin/controllers/collaborator-modal.client.controller.js
src/public/modules/forms/admin/views/collaborator.client.modal.html

closes #347 
use `Toastr`
Please refer to screenshots in issue.

fix: transfer form toastr

---

.eslintrc
src/app/models/form.server.model.ts
src/app/modules/webhook/webhook.controller.ts
src/loaders/mongoose.ts
src/server.ts

A couple of scares that happened with promises failing to be invoked or awaited, etc (floating promises), most recently with https://github.com/opengovsg/FormSG/pull/362 (correct me if I'm wrong).
This PR adds an ESLint rule that returns an error if any promises are floating. Also fixes the errors that this lint rule highlighted.

chore: add lint rule to prevent floating promises

---

package-lock.json
package.json
src/app/controllers/admin-console.server.controller.js
src/app/controllers/admin-forms.server.controller.js
src/app/controllers/authentication.server.controller.js
src/app/controllers/core.server.controller.js
src/app/controllers/email-submissions.server.controller.js
src/app/controllers/encrypt-submissions.server.controller.js
src/app/controllers/forms.server.controller.js
src/app/controllers/myinfo.server.controller.js
src/app/controllers/public-forms.server.controller.js
src/app/controllers/spcp.server.controller.js
src/app/controllers/submissions.server.controller.js
src/app/modules/auth/auth.controller.ts
src/app/utils/request.ts
src/loaders/express/index.ts
src/loaders/express/logging.ts

Implements tracing for (https://github.com/datagovsg/formsg-private/issues/25)
Add trace to logs using cloudflare cf-ray header. If cf-ray does not exist, trace using x-request-id header
**On staging**
**On localhost**
```
isDev
? format.combine(format.colorize(), errorPrinter(), customFormat)
: format.json({ replacer: jsonErrorReplacer }),
```
with 
``` 
format.json({ replacer: jsonErrorReplacer }),
```
Access a public form. Check that the value of x-request-id header is logged under trace in the server logs for the get request. 
- express-request-id^1.4.1

feat: add trace to logs

---

src/app/controllers/admin-console.server.controller.js
src/app/controllers/admin-forms.server.controller.js
src/app/controllers/authentication.server.controller.js
src/app/controllers/email-submissions.server.controller.js
src/app/controllers/encrypt-submissions.server.controller.js
src/app/controllers/forms.server.controller.js
src/app/controllers/myinfo.server.controller.js
src/app/controllers/public-forms.server.controller.js
src/app/controllers/spcp.server.controller.js
src/app/controllers/submissions.server.controller.js
src/app/factories/google-analytics.factory.js
src/app/factories/spcp-myinfo.factory.js
src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/auth.controller.ts
src/app/modules/user/user.controller.ts
src/app/modules/verification/verification.factory.ts
src/app/routes/frontend.server.routes.js
src/loaders/express/error-handler.ts
tests/unit/backend/controllers/forms.server.controller.spec.js
tests/unit/backend/controllers/myinfo.server.controller.spec.js
tests/unit/backend/controllers/spcp.server.controller.spec.js
tests/unit/backend/modules/user/user.controller.spec.ts

Usage of `res.send` creates the risk of HTML injection attacks if not used with care. Using `res.json` is better practice.
**This PR addresses the cases where changing from `res.status` to `res.json` or `res.sendStatus` should be risk-free.**
When `res.send` is called with an object, it behaves the same way as if `res.json` is called, since Express just [calls `res.json` internally](https://github.com/expressjs/express/blob/508936853a6e311099c9985d4c11a4b1b8f6af07/lib/response.js#L158). Moreover, when `res.send` is called with no argument, it is (almost) equivalent to calling `res.sendStatus`, since the client should not be doing anything with the empty response body. This PR addresses these two cases throughout the codebase by changing `res.send` to `res.json` or `res.sendStatus` as …

refactor: use res.json or sendStatus for objects or empty body

---

.template-env
docker-compose.yml
docs/DEPLOYMENT_SETUP.md
package-lock.json
package.json
src/app/controllers/public-forms.server.controller.js
src/app/modules/auth/auth.routes.ts
src/app/routes/public-forms.server.routes.js
src/app/utils/__tests__/limit-rate.spec.ts
src/app/utils/limit-rate.ts
src/config/config.ts
src/config/schema.ts
src/types/config.ts

We want to limit the rate of requests to public endpoints as a security measure against DDoS attacks. However, we need to ensure that the limits do not affect regular application usage. Hence it is necessary to ensure that the limits do not get exceeded on a regular basis, before actually denying requests which exceed the limit.
After some discussion, we decided to apply the limits to three endpoints: `/auth/sendotp` as well as both submissions endpoints, `v2/submissions/email` and `v2/submissions/encrypt`.
Use `express-rate-limit` with a custom handler which logs a message if the rate limit is exceeded, then carries on handling the request as normal. Note that the package uses per-IP limits by default.
The log message looks like this:
It is important to apply a limit which does not …

feat: soft-launch rate-limiting of API endpoints

---

src/app/controllers/admin-console.server.controller.js
src/app/controllers/admin-forms.server.controller.js
src/app/controllers/public-forms.server.controller.js
src/app/controllers/spcp.server.controller.js
src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.controller.ts
src/app/modules/user/user.controller.ts
src/loaders/express/error-handler.ts
tests/unit/backend/controllers/public-forms.server.controller.spec.js
tests/unit/backend/controllers/spcp.server.controller.spec.js
tests/unit/backend/modules/user/user.controller.spec.ts

Usage of `res.send` creates the risk of HTML injection attacks if not used with care. Using `res.json` is better practice.
**This PR addresses the cases where changing from `res.status` to `res.json` is compatible with the client.**
When the client does not use the content of the response body, it is safe to change `res.send` to `res.json`, wrapping the original string in an object. For example, the client sometimes does its own success/error handling, or simply logs errors to the console. This applies to the following API endpoints:
- `GET /billing`
- `POST /:formId/adminform/feedback`
- `POST /:formId/feedback`
- `GET /spcp/redirect`
- `GET /spcp/validate`
- `GET /auth/signout`
- `GET /user`
- Generic error handling for `celebrate` errors

refactor: use res.json if backwards compatible with client

---

src/public/modules/forms/base/directives/validate-email-domain.client.directive.js

Fixes bug where optional email fields are still failing validation for restricted email domains even when they are empty.
Closes #431
**Bug Fixes**:
- Remove restricted email domain field validation when field is an empty string (on required fields, the required validator will still fire) 
**AFTER**:
Required fields will have error when field is empty when submitting
Optional field will have no error when field is empty when submitting

fix: early return when validating empty email string

---

.eslintrc
src/app/modules/bounce/__tests__/bounce-test-helpers.ts
src/app/modules/bounce/__tests__/bounce.service.spec.ts
src/loaders/express/error-handler.ts

Unused imports are building up around the codebase. This PR upgrades the linting rule from "warn" to "error", and fixes the resulting lint errors.

chore: add lint error for unused variables

---

src/app/controllers/admin-console.server.controller.js
src/app/controllers/admin-forms.server.controller.js
src/app/controllers/authentication.server.controller.js
src/app/controllers/email-submissions.server.controller.js
src/app/controllers/encrypt-submissions.server.controller.js
src/app/controllers/forms.server.controller.js
src/app/controllers/myinfo.server.controller.js
src/app/controllers/public-forms.server.controller.js
src/app/controllers/spcp.server.controller.js
src/app/controllers/submissions.server.controller.js
src/app/modules/analytics/analytics.controller.ts
src/app/modules/auth/auth.controller.ts
src/app/utils/limit-rate.ts
src/app/utils/request.ts
src/loaders/express/logging.ts
src/types/express.d.ts

Closes #415 and #416
- create getMeta() utility function to extract relevant log info (i.e. ip, trace, url, header) instead of specifying at each logger function call
- extend Request interface globally
**On staging**
**On localhost**
```
isDev
? format.combine(format.colorize(), errorPrinter(), customFormat)
: format.json({ replacer: jsonErrorReplacer }),
```
with 
``` 
format.json({ replacer: jsonErrorReplacer }),
```
Access a public form. Check that the value of x-request-id header is logged under trace in the server logs for the get request.

chore: extend namespace globally for request properties and log info utility function

---

jest.config.js

The current test coverage is about 28%, so we can safely set the minimum to 25.
From the latest `develop` build:

chore: update test coverage threshold to 25

---

src/public/modules/forms/admin/controllers/list-forms.client.controller.js

Fixes error that occurs when user session expires, resulting in `String.split` being performed on a `vm.user` that is `undefined`.
**Bug Fixes**:
- fix: safely retrieve user's name from email before attempting to split the resulting name string.

fix: prevent undefined split errors when vm.user does not exist

---

src/app/controllers/admin-forms.server.controller.js
src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.controller.ts
tests/integration/helpers/express-auth.ts

Usage of `res.send` creates the risk of HTML injection attacks if not used with care. Using `res.json` is better practice.
This PR covers all remaining cases in the codebase where `res.send` is used. All these cases pass strings into `res.send`, hence these changes are backwards-compatible. The client sees the same response except with the `Content-Type` header changed from `text/html` to `application/json`.

refactor: convert remaining res.send to res.json

---

src/app/modules/webhook/webhook.utils.ts
tests/.test-basic-env
tests/.test-full-env
tests/unit/backend/modules/webhook/webhook.utils.spec.ts

Users are allowed to enter webhook URLs which point back to the app, which results in 404 errors when our servers POST back to themselves.
Validate that the webhook URL domain is not the same as the app URL.

feat: validate that webhook does not point back to app

---

package-lock.json
package.json

Upgrades myinfo-gov-client to use the latest patch.
TODO:
1. test in staging environment
2. publish new myinfo-gov-client in npm
3. update package.json in this PR to use published package instead of installing from github branch

fix: upgrade myinfo-gov-client

---

src/app/modules/bounce/__tests__/bounce.controller.spec.ts
src/app/modules/bounce/bounce.controller.ts
tests/unit/backend/modules/verification/verification.controller.spec.ts

Email notifications arrive at our `/emailnotifications` endpoint asynchronously, and processing them involves retrieving documents from the Bounce collection. This means that multiple server instances sometimes attempt to access and modify the same Bounce document concurrently, resulting in Mongoose throwing `VersionErrors`. These errors are caught and HTTP 400 is returned, sometimes resulting in false HTTP 400 alarms.
Check if the error is a `VersionError`, and return 200 if it is. The idea here is that we accept the risk of `VersionErrors` as a limitation of our system, and return an OK response since the error is on our end.
Tests for the Bounce and Verification controllers were updated with hardcoded numbers for HTTP status codes instead of using the `http-status-codes` package.

feat: return 200 for Bounce collection VersionError

---

src/public/modules/forms/admin/controllers/view-responses.client.controller.js

Missed adding `vm`... seems like that came back to bite us in the butt.
**Bug Fixes**:
- fix: correctly show decrypt progress modal when downloading storage mode responses
> For local testing, I've set the timeout before the modal appears to 0 milliseconds (i.e instantly).
> For release testing, a test form with >100k responses should be used so the decrypting takes more than 3 seconds.

fix: correctly show decrypt progress modal after 3 seconds when downloading storage mode responses

---

src/app/controllers/admin-console.server.controller.js

This PR simply logs the error message from mongoose for the examples search endpoint.

chore(examples-search): log failures from database

---

src/public/modules/forms/admin/css/view-responses.css

Submission search button was overlapped by other elements resulting it in being unclickable when screen width was between 768px to ~1500px
Closes [#439]
Increase minimum width of search button's container
**BEFORE**:
**AFTER**:

fix: unclickable submissionId search button

---

src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/shared/util/email-domain-validation.ts

This PR adds an additional check for the allowed domains entered by the user to enforce starting with an '@' symbol. This prevents a form admin from adding a complete email address such as `test@example.com` into the allowed domain field.
Related to https://github.com/datagovsg/formsg-private/issues/53
**Bug Fixes**:
- fix: add additional startsWith('@') check when validating domain
**BEFORE**:
Allows full email domains
**AFTER**:
Prevents full email addresses

fix: add additional startsWith('@') check when validating domain

---

src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/user/__tests__/user.routes.spec.ts
src/loaders/express/error-handler.ts
tests/unit/backend/helpers/celebrate.ts

This PR uses the default [`celebrate` error handler](https://github.com/arb/celebrate#errorsopts) to handle validation errors instead of rolling our own generic one. This gives the client more informative error messages when validation fails. Logging was also improved to include the details of the validation error.
**Why not use the celebrate error handler as a middleware?**
Using `isCelebrateError` allows us to retain control over the error object before passing it to the celebrate error handler, which allows us to perform customised actions, e.g. logging. Moreover, I thought it was cleaner to use the celebrate error handler within the `if (isCelebrateError)` block rather than calling `next`, because that allows our error handler to retain control of the error object rather than calling …

refactor: use celebrate error handler

---

src/public/modules/core/css/admin-form-header.css
src/public/modules/forms/admin/views/collaborator.client.modal.html

Closes https://github.com/opengovsg/FormSG/issues/214
Extend form transfer functionality to email mode forms
_Encrypt Forms_
_Email Forms_

feat: allow form transfer for email mode forms

---

package.json

Upgrading mongoose beyond 5.10.0 breaks server deployment. It is probable that deployments have not been affected only because TravisCI caches node_modules.
Pin mongoose version to 5.10.0 until we can figure out the root cause.

build: pin mongoose version to 5.10.0

---

src/public/modules/forms/admin/css/edit-form.css
src/public/modules/forms/admin/views/edit-fields.client.modal.html

Form admins should not be able to save empty allowed domains list on the front-end. This prevents user confusion, and also makes it easier to query for usage without having to ignore empty arrays.
Related to https://github.com/datagovsg/formsg-private/issues/53
**Features**:
- Require non-empty domains if restrict domain is toggled on
- Add red error border to edit panel textareas if input is invalid (via `ng-invalid`). 
**BEFORE**:
Can be saved even if textarea is invalid
**AFTER**:
Error prevents form saving

feat: require non-empty domains if restrict domain is toggled on

---

package-lock.json
package.json

Able to unpin mongoose since `await mongoose.connection` in `5.10.10` now correctly returns the connection in and not `undefined`.
Closes #506.
Bumps [mongoose](https://github.com/Automattic/mongoose) from 5.10.0 to 5.10.10.
<p><em>Sourced from <a href="https://github.com/Automattic/mongoose/blob/master/History.md">mongoose's changelog</a>.</em></p>
5.10.10 / 2020-10-23
====================
* fix(schema): handle merging schemas from separate Mongoose module instances when schema has a virtual #9471
* fix(connection): make connection.then(...) resolve to a connection instance #9497 [AbdelrahmanHafez](https://github.com/AbdelrahmanHafez)
* fix(aggregate): when using $search with discriminators, add `$match` as the 2nd stage in pipeline rather than 1st #9487
* fix(query): cast $nor within …

fix(deps): unpin and bump mongoose from 5.10.0 to 5.10.10

---

src/public/modules/core/services/gtag.client.service.js
src/public/modules/forms/admin/controllers/create-form-modal.client.controller.js

Part of [#25](https://github.com/datagovsg/formsg-private/issues/25)
- Log to GA when admin form creation fails

feat: log create form failure on GA

---

docs/TROUBLESHOOTING.md
package.json

Local tests cannot be run unless using that specific `node` version due to the mongo binary being used.
Also keeps it consistent with the node version used in our Dockerfiles.

chore: fix node version used to 12.18.4 to be consistent

---

src/public/modules/forms/admin/views/edit-fields.client.modal.html

- For email form field Restrict Email Domains, it is still possible to toggle Restrict Email Domains even when OTP verification is toggled false, although visually Restrict Email Domains remains shown as toggle false. This results in Restrict Email Domains toggled to true and subsequently, field validation fails as the domain list is empty. 
- Disable Restrict Email Domains toggle if OTP verification is not toggled true
**BEFORE**:
**AFTER**
(no longer possible to get into the 'BEFORE' state)

build: Release 4.42.0 hotfix

---

package-lock.json
package.json
src/app/controllers/public-forms.server.controller.js
src/app/routes/frontend.server.routes.js
src/public/modules/forms/base/directives/field.client.directive.js
tests/unit/backend/controllers/public-forms.server.controller.spec.js

Closes #498
- Retain query params when redirecting from non-hashbang url
- On public form route, extract query params using $location service on frontend to stealth prefill forms
TODO:
- Test that special characters in query param values work correctly and that they are passed correctly to redirect endpoint
**AFTER**:
With the query param string: `?<fieldId2>=yes&<fieldId4>=hello`

feat: stealth textfield prefill feature from query parameters

---

src/app/modules/billing/__tests__/billing.routes.spec.ts

This PR adds integration tests for the /billing endpoint.
Related to https://github.com/opengovsg/FormSG/issues/456

test: add integration tests for /billing endpoint

---

.travis.yml
package.json

Local builds are failing with an error (but no steps to fix it):
```
bad option: --transpileOnly
```
The fix is to change the `--transpileOnly` flag to `--transpile-only`.
See https://github.com/whitecolor/ts-node-dev/issues/223
Travis also failed to build due to Javascript heap being out of memory. This PR also increases the heap size Javascript can use.

fix: local builds failing to transpile due to breaking change in tsnd + Travis JS heap increase

---

.travis.yml
src/app/modules/auth/auth.utils.ts
src/app/modules/billing/__tests__/billing.controller.spec.ts
src/app/modules/billing/billing.controller.ts
src/types/express.d.ts

This PR tightens the check to see if a user is logged in. 
- Tighten checks on whether user is in session by checking for existence of `user._id` instead of just the `user` object.

feat: tighten isUserInSession conditional for protected routes

---

src/public/modules/forms/base/directives/field.client.directive.js

Potential phishing concerns from disabling editing of prefill.
Do not disable the input box after prefill.

fix(prefill): do not disable textfield due to phishing concerns

---

src/app/factories/spcp-myinfo.factory.js

The `encryptedVerifiedFields` function in the SPCP controller is no longer accessed through the SPCP factory, and is now accessed through the `WebhookVerifiedFactory`. Hence there is no need for the SPCP factory to export this function.

refactor: remove unused SPCP factory function

---

src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/public/modules/forms/services/betas.client.factory.js

The function `userHasAccessToVerifiedMobileOrAutoreply` was created as part of the verified mobile release, but was later missed during the code cleanup when verified mobile was released to all users. This PR removes references to that function.

refactor: remove unused verified mobile beta check

---

Dockerfile.development
Dockerfile.production
package-lock.json
package.json

All our Docker builds are breaking as Alpine recently changed the supported version of Chromium from 83 to 86:
Upgrade Chromium to 86 and puppeteer-core to 5.3.1, which is the [corresponding version](https://www.npmjs.com/package/puppeteer-core?activeTab=versions).

fix(deps): upgrade Chromium and puppeteer-core

---

src/public/modules/forms/admin/css/settings-form.css
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html

Closes #542
**BEFORE**:
**AFTER**:

chore: shift webhook field to bottom of settings page, update copy

---

src/public/modules/core/css/admin-form-header.css
src/public/modules/forms/admin/css/pop-up-modal.css

Hotfix PR to fix ie11 incorrectly resizing modal due to overflow

fix: breakage of add collaborator styling on ie11

---

src/app/controllers/myinfo.server.controller.js
src/app/models/myinfo_hash.server.model.ts
src/types/myinfo_hash.ts
tests/unit/backend/models/myinfo_hash.server.model.spec.ts

MyInfo controller interacts directly with the model to update the field hashes, which makes it hard to refactor the logic into a clean service.
This PR moves the logic for updating MyInfo field value hashes from the controller into a model static method, and adds test for the MyInfoHash model.

refactor: convert MyInfo hash update to domain method

---

src/public/modules/core/components/avatar-dropdown.client.component.js

This PR fixes the issue where the `!` exclamation mark sign does not disappear from user profile icon after emergency contact number has been added, until page is refreshed. 
Related to #369

feat: remove exclamation when user updates contact

---

package-lock.json
package.json

This PR bumps myinfo-gov-client to v2.1.2 so we can take advantage of the newly exported types.

feat: upgrade myinfo-gov-client

---

src/app/controllers/myinfo.server.controller.js
src/app/models/myinfo_hash.server.model.ts
src/types/myinfo_hash.ts
tests/unit/backend/controllers/myinfo.server.controller.spec.js
tests/unit/backend/models/myinfo_hash.server.model.spec.ts

The MyInfo controller currently has the responsibility of hashing the user's ID (`uinFin`) in order to search and update the `MyInfoHash` collection. However, hashing is really a concern of how the data is stored, not the business logic of the application. It would be better if the service and controller layers could deal with the ID as-is, instead of having to worry about transforming it so the model can store it correctly.
Move the responsibility of hashing the uinFin into model static methods, and have the controller interact with the model through those methods.

refactor: hash uinFin in domain layer

---

src/public/modules/core/css/core.css
src/public/modules/forms/admin/css/view-responses.css

Closes [#83](https://github.com/datagovsg/formsg-private/issues/83)
- force allow overflow when printing
**BEFORE**:
(cut off after first page)
**AFTER**:
**Tested on GSIB-IE**

fix: overflow when printing responses

---

src/public/modules/forms/base/componentViews/start-page.html
src/public/modules/forms/base/components/start-page.client.component.js
src/public/modules/forms/base/css/form.css
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html

In forms with long set of Instructions, SPCP login note is pushed all the way to the bottom and also exceeds the instructions container.
Related to #369
**Features**:
- Move SPCP gated message to start page section
- Move MyInfo error messaging to above instructions
**BEFORE**:
See above
**AFTER**:
SP Logins
CP Logins
MyInfo errors

feat: move public spcp login form messaging

---

src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/services/captcha.client.service.js

Closes #31 
Display a Toast when the captcha module's `on-error` handler is fired.
**Features**:
1. The Toast does not show up immediately upon page load. It takes a bit of time (5 seconds) to show up after a user first touches the form (e.g. clicking on a form field). User does not need to fill up anything. He/she just needs to touch the form.
1. The Toast shows up at the same time as the reCAPTCHA failure at the bottom of the form (this is good).
**BEFORE**:
Only the reCAPTCHA failure at the bottom of the form will be observed after the user touches the form.
**AFTER**:
Both Toast at the top and reCAPTCHA failure at the bottom will be observed.

feat: display a Toast when reCAPTCHA fails while users are filling up a form

---

src/app/factories/spcp-myinfo.factory.js
src/config/feature-manager/spcp-myinfo.config.ts
src/config/feature-manager/types.ts
tests/.test-full-env

MyInfo environment variables are currently not being read and validated by Convict like all the others. Instead, they are read directly from `process.env`. This also means the `spcp-myinfo` feature is activated even when the MyInfo environment variables are missing.
Integrate the MyInfo environment variables into the existing Convict framework.

refactor: validate MyInfo env vars using Convict

---

src/public/modules/forms/base/components/field-date.client.component.js

Closes #377
- set dateOptions.initDate = dateOptions.minDate

chore: set datepicker default view to minimum date

---

src/app/controllers/encrypt-submissions.server.controller.js
src/app/models/submission.server.model.ts
src/app/routes/admin-forms.server.routes.js
src/types/submission.ts
tests/unit/backend/controllers/submissions.server.controller.spec.js
tests/unit/backend/models/encrypt-submission.server.model.spec.ts
tests/unit/backend/modules/webhook/webhook.service.spec.ts

This PR extracts out the inlined mongoose queries in the `/:formId([a-fA-F0-9]{24})/adminform/submissions/metadata` controller handler. Also adds `celebrate` middleware validation for the route.
**Features**:
- Add `EncryptSubmissionModel#findSingleMetadata` static method to retrieve metadata for a single submission
- Add `EncryptSubmissionModel#findAllMetadatabyFormId` static method to retrieve all submission metadatas for the given form id.
- Add celebrate middleware validation to `/:formId([a-fA-F0-9]{24})/adminform/submissions/metadata` endpoint.
- Replace inlined queries in the controller handler for `/:formId([a-fA-F0-9]{24})/adminform/submissions/metadata` endpoint with `EncryptSubmissionModel` static methods.

ref: migrate inline queries for retrieval of submissions metadata to model static methods

---

README.md
docker-compose.yml
src/config/config.ts

`nodemailer-direct-transport` has been failing intermittently, preventing emails from being sent in the dev environment. Moreover, the package is not currently maintained and is not keeping pace with changes in `nodemailer`.
Add `maildev` to our dev environment. In addition to being a well-maintained package, this allows us to completely isolate our dev environment to our local machines.

fix: use maildev for dev environment emails

---

package-lock.json
package.json
src/app/controllers/encrypt-submissions.server.controller.js
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/helpers/decryption.worker.js
src/public/modules/forms/services/submissions.client.factory.js

Backend implementation for bulk attachment downloading using existing CSV decryption workers.

feat: Backend implementation for bulk attachment downloading

---

src/app/controllers/admin-forms.server.controller.js
src/app/controllers/email-submissions.server.controller.js
src/app/controllers/myinfo.server.controller.js
tests/unit/backend/controllers/email-submissions.server.controller.spec.js
tests/unit/backend/controllers/myinfo.server.controller.spec.js

`myinfo.server.controller` assigns a `hashedFields` key to the Express request object in order for subsequent middlewares to keep track of which MyInfo attributes have been verified through their hashes. `hashedFields` is an object which maps the MyInfo attribute to the corresponding client response, but subsequent middlewares have no need for the values of this object, since they only check that the value corresponding to each key is truthy, i.e. that the object contains the key.
Convert `hashedFields` into a Set, which is the more correct data structure for this case. This ensures that subsequent refactors (#560) don't have to bend over backwards just to get `hashedFields` into the right format.
Also, assign `hashedFields` to `res.locals` instead of `req`.

ref: convert req.hashedFields to Set

---

src/app/controllers/admin-forms.server.controller.js
src/app/modules/core/core.errors.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.constants.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.errors.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/form/admin-form/admin-form.utils.ts
src/app/routes/admin-forms.server.routes.js

This PR migrates the createPresignedPost endpoint flow to Typescript (barring router layer).
Adds tests for all the new migrated functions.
**Features**:
- add `ExternalError` class for errors arising externally (like S3)
- add `AdminFormService#createPresignedPostForImages` function
- add `AdminFormController#handleCreatePresignedPostForImages` function
- replace controller handler function used for `POST /:formId([a-fA-F0-9]{24})/adminform/images` route with migrated TypeScript function
- Remove all traces of old Javascript handler function

ref: migrate createPresignedPost endpoint for images to TypeScript

---

src/public/modules/core/css/admin-form-header.css
src/public/modules/forms/admin/views/collaborator.client.modal.html

Closes #499 
**BEFORE**:
**AFTER**:

style: make transfer ownership email more prominent

---

src/app/controllers/admin-forms.server.controller.js
src/app/modules/core/core.errors.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.errors.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/form/admin-form/admin-form.utils.ts
src/app/routes/admin-forms.server.routes.js

Continuation of #604, this time for creating presigned urls for **logo** uploads.
**Features**:
- add `AdminFormController#handleCreatePresignedPostForLogos` handler for presigning logos upload POST url
- add `AdminFormService#createPresignedPostForLogos` function
- add and use `CreatePresignedUrlError` instead of `ExternalError`
- ExternalError seemed too general for use, and could conflict in the future if other external services also error
- replace controller handler function used for `POST /:formId([a-fA-F0-9]{24})/adminform/logos` route with migrated TypeScript function
- Remove all traces of old Javascript handler function

ref: migrate createPresignedPost endpoint for logos to TypeScript 

---

src/app/controllers/spcp.server.controller.js
src/app/factories/spcp.factory.js
src/app/modules/spcp/__tests__/spcp.controller.spec.ts
src/app/modules/spcp/__tests__/spcp.factory.spec.ts
src/app/modules/spcp/__tests__/spcp.routes.spec.ts
src/app/modules/spcp/__tests__/spcp.service.spec.ts
src/app/modules/spcp/__tests__/spcp.test.constants.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.errors.ts
src/app/modules/spcp/spcp.factory.ts
src/app/modules/spcp/spcp.routes.ts
src/app/modules/spcp/spcp.service.ts
src/app/modules/spcp/spcp.util.ts
src/app/routes/spcp.server.routes.js
src/loaders/express/index.ts
tests/unit/backend/controllers/spcp.server.controller.spec.js

This PR migrates the `/spcp/redirect` endpoint to TypeScript. Note that the base branch is `ref/ts-spcp`, which will be eventually merged into `develop` after all the SPCP functionality has been migrated.

ref: migrate /spcp/redirect endpoint to TypeScript

---

.ebextensions/eb-memory-monitor.config

EC2 memory monitoring was previously relying on an unofficial 3rd party solution, which at one point was working intermittently.
The problem has become more pressing since PR #555 was merged, which reported a 19 MB increase in memory usage for a single bulk download of 10,000 submissions.
Upgrade to use an official solution provided by AWS [here](https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-memory-monitoring/), which provides both memory and disk monitoring. The only change made was to the cron expression, which has been updated to report every minute instead of every 5 minutes.
The requisite permissions have been granted to our Elastic Beanstalk instance profiles.

feat(monitoring): add memory monitoring to EC2 instances

---

package-lock.json
package.json
src/app/controllers/__tests__/frontend.server.controller.spec.ts
src/app/controllers/frontend.server.controller.js
src/public/modules/forms/base/components/field-textfield.client.component.js
src/public/modules/forms/base/directives/field.client.directive.js
tests/unit/backend/helpers/jest-express.ts

- This PR resolves the issue of `&` being html-encoded as `&amp;` upon redirect, which is not valid URI
- Also shifts the stealth prefill feature from the field directive to the textfield component 
- Closes #531 
- Replace `&amp;` with `&` in the ejs template. This was preferred to allowing all characters to be escaped, which may possibly introduce a security vulnerability
The following non-hashbang URL will be redirected as follows:
`https://form.gov.sg/<formId>?<fieldId1>=abc&<fieldId2>=xyz`
**BEFORE**:
`https://form.gov.sg/#!/<formId>?<fieldId1>=abc&amp;<fieldId2>=xyz`
**AFTER**:
`https://form.gov.sg/#!/<formId>?<fieldId1>=abc&<fieldId2>=xyz`
**dependencies**
- he module has been removed

fix: resolve &amp; in url upon redirect, shift prefill to textfield component

---

src/shared/util/file-validation.ts

Tested on Intranet in addition to public internet.
**Features**:
- Allow `<filename>.oa` files to be used in the attachment fields.

feat: allow .oa files to be attached

---

package-lock.json
package.json

This PR upgrades @opengovsg/spcp-auth-client to the latest, typed version.

feat: upgrade spcp-auth-client to TypeScript version

---

.travis.yml

Some tests are flaky (mostly form server model admin checks), resulting in failed tests that developers have to manually retry (either via an empty commit push or via trigger build).
This PR adds a retry mechanism using [`travis_retry`](https://docs.travis-ci.com/user/common-build-problems/#travis_retry) to automatically retry failed tests up to 3 times.

chore: use travis_retry to retry flaky tests automatically

---

.travis.yml

This PR adds lockfile-lint to our CI to prevent potential [malicious injections through our lockfile](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/).

build: add lockfile-lint to CI

---

src/public/modules/forms/admin/directiveViews/configure-mobile.client.view.html

This PR changes 'Verified?' on SMS config to say 'OTP verification' like in Email fields
Related to #369 
**AFTER**:

feat: change 'Verified?' on SMS config to 'OTP verification'

---

src/app/controllers/spcp.server.controller.js
src/app/models/login.server.model.ts
src/types/login.ts
tests/unit/backend/models/login.server.model.spec.ts

This PR moves the logic for creating a new Login document from the SPCP controller to a Login model static method.

refactor: create addLoginFromForm static method

---

src/app/controllers/admin-forms.server.controller.js
src/app/factories/spcp.factory.js
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/spcp/spcp.util.ts
src/app/routes/admin-forms.server.routes.js

The `passThroughSpcp` function serves to populate mock SingPass and CorpPass authentication info when admins submit the form in the preview. This functionality will eventually be subsumed under a single controller function, so this PR migrates the business logic into a util which can easily be called by that controller in future.

refactor: move passThroughSpcp business logic into service

---

.github/workflows/codeql-analysis.yml

This PR runs GitHub's static analysis engine, [CodeQL](https://securitylab.github.com/tools/codeql), against a repository's source code to find security vulnerabilities. It then automatically uploads the results to GitHub so they can be displayed in the repository's security tab. CodeQL runs an extensible set of queries, which have been developed by the community and the GitHub Security Lab to find common vulnerabilities in the code.
CodeQL is free for open source repositories.

feat: introduce static analysis with CodeQL

---

src/public/modules/core/componentViews/navbar.html
src/public/translations/en-SG/main.json

This PR adds a new feature request navbar item for admins to request for features. Due to size constraints, the link is hidden in mobile screens (like our User Guide link).
Related to #369
**Features**:
- add feature request link in admin navbar
**AFTER**:
iPhone 6 size (link is hidden like our user guide is)
iPad size
iPad Pro size
Laptop 1024 size
Laptop 1440 size

feat: add feature request link in admin navbar

---

src/app/controllers/encrypt-submissions.server.controller.js
src/app/models/submission.server.model.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.service.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.service.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts
src/app/modules/submission/submission.errors.ts
src/app/routes/admin-forms.server.routes.js
src/app/utils/handle-mongo-error.ts
src/types/submission.ts
tests/unit/backend/models/encrypt-submission.server.model.spec.ts

This PR migrates all the inlined services in the old `encrypt-submissions.server.controller.js#getEncryptedResponse` function into the layered architecture design with Typescript.
PS: Abbreviating `EncryptSubmission` to `ES` for ease of typing.
**Features**:
- Add `ESModel#findEncryptedSubmissionById` static method
- Add `ESService#getEncryptedSubmissionData` function that calls the above method
- Add `ESService#transformAttachmentMetasToSignedUrls` function to have a better chunk out work in the controller
- Add `ESController#handleGetEncryptedResponse` function for route to use
Tests are written for all the newly added code
- `ESModel#findEncryptedSubmissionById`
- `ESService#getEncryptedSubmissionData`
- `ESService#transformAttachmentMetasToSignedUrls`
- …

ref: migrate get single encrypt submission flow to TypeScript

---

src/app/controllers/authentication.server.controller.js
src/app/modules/form/admin-form/admin-form.types.ts
src/app/routes/admin-forms.server.routes.js
src/app/utils/permission-levels.ts
tests/unit/backend/controllers/authentication.server.controller.spec.js

This PR migrates the sole enum in `utils/permission-levels` to `form/admin-form/admin-form.types`
Also updated the casing of the enum to PascalCase following standard practices

refactor: migrate utils/permission-levels to admin-form.types

---

src/app/controllers/admin-forms.server.controller.js
src/app/controllers/email-submissions.server.controller.js
src/app/services/myinfo/__tests__/myinfo.service.spec.ts
src/app/services/myinfo/__tests__/myinfo.test.constants.ts
src/app/services/myinfo/myinfo.factory.ts
src/app/services/myinfo/myinfo.service.ts
src/app/services/myinfo/myinfo.types.ts
src/app/services/myinfo/myinfo.util.ts
src/types/express.locals.ts
tests/unit/backend/controllers/email-submissions.server.controller.spec.js

If there are duplicate verified MyInfo fields, hash verification passes even if the responses are tampered with, as long as the last duplicate field matches the hash. For example, if there are two MyInfo name fields which are filled in and disabled, a user can use Developer Tools to edit the first field, and the MyInfo hash verification would still pass.
The problem is that the code uses a `Map<MyInfoAttribute, Promise<boolean>>` to keep track of the hash comparisons, and this Map is built while iterating through all the MyInfo fields (the Map was formerly an object before the TypeScript refactor, but the idea is the same). This meant that if there were duplicate `MyInfoAttribute`s, later hashes would override earlier ones, which made it possible to edit all duplicate fields except the …

fix: check duplicate MyInfo fields

---

src/app/controllers/email-submissions.server.controller.js
src/app/controllers/encrypt-submissions.server.controller.js
src/app/modules/submission/__tests__/submission/submission.service.spec.ts
src/app/modules/submission/submission.errors.ts
src/app/modules/submission/submission.service.ts
src/app/utils/encryption.ts
src/app/utils/field-validation/index.ts
tests/unit/backend/controllers/encrypt-submissions.server.controller.spec.js
tests/unit/backend/utils/field-validation/attachment-validation.spec.js
tests/unit/backend/utils/field-validation/checkbox-validation.spec.js
tests/unit/backend/utils/field-validation/date-validation.spec.js
tests/unit/backend/utils/field-validation/decimal-validation.spec.js
tests/unit/backend/utils/field-validation/dropdown-validation.spec.js
tests/unit/backend/utils/field-validation/email-validation.spec.ts
tests/unit/backend/utils/field-validation/nric-validation.spec.js
tests/unit/backend/utils/field-validation/number-validation.spec.js
tests/unit/backend/utils/field-validation/phone-num-validation.spec.js
tests/unit/backend/utils/field-validation/radio-button-validation.spec.js
tests/unit/backend/utils/field-validation/rating-validation.spec.js
tests/unit/backend/utils/field-validation/table-validation.spec.js
tests/unit/backend/utils/field-validation/text-validation.spec.js
tests/unit/backend/utils/field-validation/yesno-validation.spec.js

- Part of #144
- This PR is the first of a series of neverthrow refactoring PRs
- Refactor error throwing to instead return neverthrow err() and ok()

refactor: use neverthrow for exceptions

---

src/app/controllers/authentication.server.controller.js
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.utils.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.types.ts
src/app/modules/form/admin-form/admin-form.utils.ts
tests/unit/backend/controllers/authentication.server.controller.spec.js

This PR extracts out the logic in `authentication.server.controller.js#verifyPermissions` into their own utility functions so other services can use those instead of passing through the middleware.
**Features**:
- add methods to assert user permissions on forms in `admin-form.utils`
- use adminForm permission util fns when verifying form permissions

ref: extract assert permission levels helper functions

---

src/app/controllers/admin-forms.server.controller.js
src/app/modules/feedback/__tests__/feedback.service.spec.ts
src/app/modules/feedback/feedback.service.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/admin-forms.server.routes.js

This PR builds upon the work done in #703 
This PR migrates the old controller functions for the `/:formId([a-fA-F0-9]{24})/adminform/feedback/count` endpoint.
**Features**:
- Add `FeedbackService#getFormFeedbackCount` function
- Add `AdminFormController#handleCountFormFeedback` handler function
- Use new `AdminFormController#handleCountFormFeedback` function in admin form route for retrieving feedback counts.
New tests have been written for all the new migrated functions.
Note that route level integration tests have not been written yet.

ref: migrate feedback/count endpoint handler flow to TypeScript

---

src/app/modules/form/admin-form/admin-form.service.ts

The [MyInfo] prefix is supposed to show for all MyInfo fields for admin preview submissions in email mode, but they currently do not.
The bug was that ObjectIds were not being converted to strings before being added to the set of hashed fields.

fix: ensure [MyInfo] prefix appears in admin preview

---

docs/MONGODB.md

Unlisting several forms at once is a common database operation which can take prohibitively long if there are many (e.g. hundreds) of forms to unlist at once.
Add a function to our MongoDB scripts which unlists an array of form IDs. Since the forms to unlist are often given as form links and not object IDs, include a parsing step so any string can be passed into the function as an array element, as long as it contains the form ID.

docs: add script for unlisting array of forms

---

src/app/routes/admin-forms.server.routes.js

This PR adds Joi validation on `adminform/submissions` endpoint. The handler is expecting a string based submissionId.
No issues regardless on prod, since all errors are caught properly. 
Current behavior (prior to this fix):
- If submissionId is not provided, 404 will be returned.
- If submissionId is malformed (i.e. not a 24length string), 500 will be returned due to inability to cast the id to an object.
- Frontend always passes query.submissionId to request string.

fix(AdminFormRoutes): add Joi validation on /submissions endpoint

---

src/app/controllers/encrypt-submissions.server.controller.js
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.service.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.service.ts
src/app/routes/admin-forms.server.routes.js

Building upon #601, this PR migrates the rest of the controller into Typescript.
**Features**:
- add `EncryptSubSvc#getSubmissionMetadata` service fn to use model static method
- add `EncryptSubSvc#getSubmissionMetadataList` service fn to use model static method
- add `EncryptSubCtl#handleGetMetadata` handler fn for route endpoint
- Tighten (or relax depending on your POV) Joi validation on metadata retrieval endpoint
- `query.page` is now optional iff `query.submissionId` exists, since singular submission metadata search does not require the page parameter.
Add tests for all new methods. 
Note that route integration tests are not done in this PR, and will be done when route also gets refactored.

feat: migrate get encrypt metadata endpoint controller to TypeScript

---

src/app/modules/form/form.service.ts
src/app/modules/submission/__tests__/submission/submission.utils.spec.ts
src/app/modules/submission/submission.utils.ts
src/app/utils/assert-unreachable.ts

This PR adds an utility to allow for compile time checks to switch blocks if the switch cases should be exhaustive.
Application will fail to compile if the switch cases are not exhaustive.

feat(utils): add exhaustive switch case typeguard

---

src/app/utils/field-validation/validators/homeNoValidator.ts
src/app/utils/field-validation/validators/mobileNoValidator.ts
src/app/utils/field-validation/validators/nricValidator.ts
src/app/utils/field-validation/validators/radioButtonValidator.ts
src/app/utils/field-validation/validators/ratingValidator.ts
src/app/utils/field-validation/validators/textValidator.ts

This is a series of small (and somewhat vain) refactors to the existing TypeScript field validators.
This code:
```
(field) => (response) => pipe(validator1(response), makeValidator2(field))
```
is the same as this:
```
(field) => (response) => pipe(response, validator1, makeValidator2(field))
```
where, instead of explicitly calling `validator1` with `response`, we just `pipe` `response` through `validator1`. Notice that all the inner anonymous function is doing is passing on its argument as the first argument to `pipe`. In fact, this is why the `flow` function exists: instead of calling a series of unary functions, chain them together and return a unary function whose argument is the input of the first function in the chain. We end up with:
```
(field) => flow(validator1, …
```

refactor(field-validation): simplify

---

src/app/controllers/admin-forms.server.controller.js
src/app/modules/feedback/__tests__/feedback.service.spec.ts
src/app/modules/feedback/feedback.service.ts
src/app/modules/feedback/feedback.types.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/admin-forms.server.routes.js
src/types/form_feedback.ts
tests/unit/backend/controllers/admin-forms.server.controller.spec.js

Same old, same old. This PR migrates the god controller function for getFeedback into the DDD architecture we all know and love.
**Features**:
- add `AdminFormCtl#handleGetFormFeedbacks` handler fn
- add `FeedbackSvc#getFormFeedbacks` fn
- Remove old Javascript `getFeedback` controller handler and replace with `AdminFormCtl#handleGetFormFeedbacks`
Tests have been written for all new functions.
Note that integration tests are not written yet as the router is not yet migrated.

ref: migrate get feedback flow to TypeScript

---

src/app/modules/submission/submission.errors.ts
src/app/utils/field-validation/index.ts
src/types/response/guards.ts
src/types/response/index.ts
tests/unit/backend/controllers/email-submissions.server.controller.spec.js
tests/unit/backend/utils/field-validation/attachment-validation.spec.js
tests/unit/backend/utils/field-validation/checkbox-validation.spec.js
tests/unit/backend/utils/field-validation/date-validation.spec.js
tests/unit/backend/utils/field-validation/decimal-validation.spec.js
tests/unit/backend/utils/field-validation/dropdown-validation.spec.js
tests/unit/backend/utils/field-validation/email-validation.spec.ts
tests/unit/backend/utils/field-validation/home-num-validation.spec.js
tests/unit/backend/utils/field-validation/mobile-num-validation.spec.js
tests/unit/backend/utils/field-validation/nric-validation.spec.js
tests/unit/backend/utils/field-validation/number-validation.spec.js
tests/unit/backend/utils/field-validation/radio-button-validation.spec.js
tests/unit/backend/utils/field-validation/rating-validation.spec.js
tests/unit/backend/utils/field-validation/table-validation.spec.js
tests/unit/backend/utils/field-validation/text-validation.spec.js
tests/unit/backend/utils/field-validation/yesno-validation.spec.js

Closes #732
- Add check for isVisible in validateField()
- Also updated unit tests

fix: backend validation does not prevent responses on hidden fields

---

src/app/controllers/admin-forms.server.controller.js
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/admin-forms.server.routes.js
src/types/form.ts
tests/unit/backend/controllers/admin-forms.server.controller.spec.js
tests/unit/backend/models/form.server.model.spec.ts

This PR migrates the `DELETE /{formId}/adminform` endpoint to TypeScript
**Features**:
- add `FormModel.archive()` instance method
- add `AdminFormSvc#archiveForm` service function
- add `AdminFormCtl#handleArchiveForm` handler function
- use new \^ handler function in AdminFormRoutes to handle archiving of form
Tests have been written for all new functions. 
Integration tests have not been written for the router since it has not been migrated yet.

ref: migrate DELETE /{formId}/adminform endpoint flow to TypeScript

---

jest.config.js

The team's effort in refactoring and writing tests has raised the test coverage threshold from 25% to 38%.
Given that around half of the codebase comprises of backend code, this also means that backend test coverage currently stands at ~70% (not counting Jasmine tests).

test: raise test coverage threshold

---

src/app/modules/spcp/spcp.util.ts
src/app/modules/submission/__tests__/submission/submission.service.spec.ts
src/app/routes/admin-forms.server.routes.js
src/app/routes/public-forms.server.routes.js
src/app/utils/field-validation/field-validation.guards.ts
src/app/utils/field-validation/index.ts
src/shared/resources/basic/index.ts
src/types/field/index.ts
src/types/response/guards.ts
src/types/response/index.ts
tests/unit/backend/controllers/email-submissions.server.controller.spec.js
tests/unit/backend/helpers/generate-form-data.ts
tests/unit/backend/helpers/jest-db.ts
tests/unit/backend/utils/field-validation/dropdown-validation.spec.js
tests/unit/backend/utils/field-validation/email-validation.spec.ts
tests/unit/backend/utils/field-validation/table-validation.spec.js
tests/unit/backend/utils/field-validation/yesno-validation.spec.js

Field validation has various related issues (described below) which allow responses with invalid shapes to slip past. This means that code after the validation step incorrectly assumes that the responses have a fixed shape, which can lead to null pointer exceptions.
**Joi validation on field types**
The Joi validation on the submission endpoints enforces that `fieldType` is a string, but not that it matches one of our valid field types. Subsequent code simply assumes that the field type is a valid member of our `BasicField` enum.
The solution was to add the list of valid field types to our Joi validation on the `fieldType` key in each response.
**Joi validation on admin preview endpoint**
The preview submissions endpoint did not have any Joi validation, even though it called the same …

feat: tighten submission validation

---

docs/MONGODB.md

dangling commas cause the mongo shell to throw invalid syntax errors
closes #772

docs: remove dangling commas from mongo scripts

---

src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/admin-forms.server.routes.js
src/types/form.ts

This PR migrates `GET /adminform` to the new layered architecture and Typescript.
Additional refactor to remove extraneous information of admin/agency when retrieving the populated form version.
**Features**:
- feat(FormModel): remove unneeded agency/admin keys in `getFullFormById` such as the document version, the referenced admin and agency's creation or last modified dates
- add `handleGetAdminForm` handler fn
- use new `handleGetAdminForm` handler fn to handle `GET /adminform` endpoint
Relevant tests have been added.

ref: migrate endpoint for getting admin form to TypeScript 

---

src/app/controllers/admin-forms.server.controller.js
src/app/modules/auth/__tests__/auth.service.spec.ts
src/app/modules/auth/auth.service.ts
src/app/modules/form/__tests__/form.service.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.utils.ts
src/app/modules/form/form.service.ts
src/app/routes/admin-forms.server.routes.js
src/public/modules/forms/services/form-factory.client.service.js
tests/unit/backend/controllers/admin-forms.server.controller.spec.js

This PR builds upon #789
This PR adds a separate controller for copying of templates. Unlike the controller in #789 (which checks if the currently logged in user has read permissions to the form), this handler only checks if the form is public prior to allowing the duplication of the form.
In addition, this PR also removes the usage of `isTemplate`, and updates frontend clients to stop sending that parameter. Tracked by issue #792.
**Features**:
- feat(AuthSvc): add `getFormIfPublic` service fn
- feat(AdminFormCtl): add `handleCopyTemplateForm` handler fn
- feat(AdminFormRoutes): add Joi validation to the `/adminform/copy` endpoint
- feat: remove and track sending of isTemplate param when using template 
- ref(AdminFormRoutes): use new `handleCopyTemplateForm` handler …

ref: migrate copy template form flow to TypeScript 

---

src/public/modules/forms/base/components/field-date.client.component.js

Closes #805
- Setting vm.dateOptions.initDate = vm.dateOptions.minDate directly leads to a bug whereby after a date is selected on the datepicker,minDate is set to the start of the month of the selected date.
- This is possibly because init date is automatically updated to the month of the latest date selection (did not find more details in documentation); since object properties are passed by reference, this led to dateOptions.minDate also being updated to the start of the selected month
- Wrap value of vm.dateOptions.initDate in a new Date object to avoid reference to vm.dateOptions.minDate
**(Tested on IE)**

fix: disallow past date and custom min date sets min date incorrectly

---

src/public/modules/forms/admin/controllers/create-form-modal.client.controller.js

Small fix to close modal on any errors instead of leaving the modal open with a perpetual spinning loader. The error can be triggered by duplicate or create form backend failure.

fix: close create form modal when create form fails

---

src/public/modules/core/css/core.css
src/public/modules/forms/admin/componentViews/form-emails-input.client.view.html
src/public/modules/forms/admin/components/form-emails-input.client.component.js
src/public/modules/forms/admin/controllers/activate-form-modal.client.controller.js
src/public/modules/forms/admin/directiveViews/configure-form.client.view.html
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/translations/en-SG/main.json

This PR finally closes the first issue created in this repo.
Closes #1
**Features**:
**Settings page**
- when only 1 recipient email is entered, display "Recommended: at least 2 recipients to prevent response loss from bounced emails" info box.
- update 'Read about email reliability' link to Guarding against bounces' with new valid link
- change the toaster under 'authentication' to say 'Deactivate your form to change authentication method'
**Create form modal**
- amend copy of email mode slightly to "...**Not recommended** usually, especially for high volume forms...
**Activation** Email mode only
- New toaster messaging for email mode form activation that lasts for 10 seconds with link to autoarchive help.
- update deactivation toast messaging
**Create form (Display text on only 1 …

feat: improve email mode messaging

---

src/app/modules/auth/__tests__/auth.service.spec.ts
src/app/modules/auth/auth.service.ts
src/app/modules/form/__tests__/form.service.spec.ts
src/app/modules/form/__tests__/form.utils.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/form.errors.ts
src/app/modules/form/form.service.ts
src/app/modules/form/form.utils.ts
src/app/modules/form/public-form/__tests__/public-form.controller.spec.ts
src/app/modules/form/public-form/public-form.controller.ts
src/app/routes/admin-forms.server.routes.js

This PR migrates the `GET /:formId/adminform/template` use case to Typescript. 
Further improvements to the handling of the requests to this endpoint is also made. Form admins' extraneous details (leaving agency, which is needed for showing the form logo) are stripped from the returned form to be used as a template. This increases the consistency of the form shape returned from the other endpoints such as /publicform.
**Features**:
- feat(formUtils): add removePrivateDetailsFromForm utility function
- feat: add formTitle variable to PrivateFormError and remove override
- The error message should default to the form's inactive message, and should be separately handled by the controller if that is not the expected behavior.
- feat(AdminFormCtl): add (and use) handleGetTemplateForm handler …

ref: migrate GET adminform/template endpoint to TypeScript

---

src/public/modules/forms/admin/directiveViews/verify-secret-key-activation.client.view.html
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/forms/admin/directives/verify-secret-key.client.directive.js
src/public/modules/forms/admin/views/create-form.client.modal.html
tests/end-to-end/helpers/util.js

A bunch of small UX fixes. 
Closes #571
- feat: change storage mode form typed declaration from "i understand the consequences and have stored my secret key in 2 other places" to a simpler "I have shared my secret key with a colleague"
- remove verified toast on secret key verification success so only one success toast shows on activation
- feat: update storage mode guide link styling to not include the parenthesises 
- feat: add spacing between each email in email form email list
**BEFORE**:
Initial load has no spacing
Original text
Two toasts on storage activation
Link to guide includes parenthesis
**AFTER**:
Initial load now separates emails by a space.
Shorter storage mode confirmation text
SIngle toast on storage activation
Link to guide now excludes the parenthesis

feat: misc UX fixes

---

.travis.yml
jest.config.js
tests/jest-global-setup.js

Our Jest tests are failing and require multiple retries due to tests encountering timeout due to only starting the mongo binary download in the tests themselves (if the binary does not exist). 
This change allows for the binary to be downloaded if not yet cached before the individual tests even run
Also remove travis_retry, since the flaky form model test has been fixed.
See:

fix: Travis Jest test not downloading mongo binary fast enough

---

src/app/controllers/email-submissions.server.controller.js

_(to rebase after #755)_
Undefined answers are being passed into submission
Part of #808
- Not immediately apparent where the validation gap is as unable to replicate
- Propose to log errors from concatResponse first so that we have more details to replicate and debug
- TODO: Review logs in 1 weeks' time

chore: log errors from concatResponse

---

src/public/modules/users/css/examples-card.css

This PR correctly aligns our covid template layout on ie11.
Closes #775
**Bug Fixes**:
- Correctly align COVID templates layout in IE11
**BEFORE**:
(in ie11)
**AFTER**:
(in ie11)

fix: add ie11 specific styling for new template forms

---

package-lock.json
package.json
src/app/modules/submission/email-submission/__tests__/email-submission.service.spec.ts
src/app/modules/submission/email-submission/email-submission.middleware.ts
src/app/modules/submission/email-submission/email-submission.service.ts
src/types/vendor/json-stringify-deterministic.d.ts

Tears out the response hashing in `receiveEmailSubmission` which is causing staging to fail on attachments >5MB.

fix: tear out response hash

---

src/app/modules/spcp/spcp.service.ts
src/app/modules/submission/email-submission/email-submission.middleware.ts

Release 4.49.1 caught null pointer exceptions when `answer` was undefined, but the logging does not allow us to pinpoint exactly which question has an undefined answer.
1. Log the keys in the payload of the JWT when it does not have the correct shape.
2. Log the truthiness of `answer` and `answerArray` for each question when `createEmailData` fails.

chore: improve logging when answer is undefined

---

package-lock.json

The `ini` package was flagged as causing 4 low-severity security vulnerabilities due to prototype pollution to the following packages:
- bcrypt
- bson-ext
- stylelint
- webpack-cli
These have been automatically fixed via `npm audit fix`.

fix: automatic security patches from NPM

---

src/shared/util/phone-num-validation.ts

Some legit office landline numbers are being marked as invalid due to not being labeled as FIXED_LINE numbers by google's libphonenumber, but as FIXED_LINE_OR_MOBILE. This PR loosens the homeno validation to allow for the latter type.
**Features**:
- feat: add FIXED_LINE_OR_MOBILE numbers to pass homeno validation
**BEFORE**:
**AFTER**:

feat: add FIXED_LINE_OR_MOBILE numbers to pass homeno validation

---

src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/admin-forms.server.routes.js

Remove reliance on `authActiveForm` middleware and inline form permission checks in their respective controller handler functions.
- ref(AdminFormCtl): inline middleware for create presigned img url
- ref(AdminFormCtl): inline middleware for create presigned logo url
Additional tests have been added to the controller tests due to the inlining of checks.

refactor: inline form permissions check for presigned POST URL endpoints

---

src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.controller.ts
src/app/utils/__tests__/limit-rate.spec.ts
src/app/utils/limit-rate.ts
src/config/schema.ts
src/public/modules/users/controllers/authentication.client.controller.js

We currently do not limit the number of submissions per IP per minute. Instead, we only log a message when a threshold is exceeded. This means that in case of a DDoS attempt, there is a risk of downstream systems (particularly those linked via webhook) being affected indirectly.
Harden the rate-limiting by return HTTP 429.
Some UI issues surfaced as a result of this change. In particular, the `/auth/sendotp` and `submissions` endpoints return different error message shapes. As a result, it was not clear what shape the `limitRate` message should return, since it is shared between those two endpoints.
I decided to change the `/auth/sendotp` endpoint to return an object with a `message` key instead of a plain string since this gives us the flexibility to return more error metadata in future. …

feat: harden rate limits

---

src/app/routes/public-forms.server.routes.js

The team may not be aware that TemperatureSG relies on the `GET /publicform` endpoint to retrieve the master list of personnel for temperature reporting.
Document its existence as a warning, and in preparation for future backend API refactoring.

doc(public-form): add warning comment to GET /publicform endpoint in case of API refactor

---

src/app/modules/submission/email-submission/email-submission.middleware.ts

This PR adds the request metadata to the error log message for `createEmailData`, which I missed out previously.

fix: add request metadata to email data error log

---

src/public/modules/forms/admin/componentViews/share-form.client.view.html
src/public/modules/forms/admin/views/edit-start-page.client.modal.html

HTML links that open in a new tab or window allow the target page to access the DOM of the origin page using window.opener unless link type noopener or noreferrer is specified. This protection is applied by default in modern browsers, but may not in legacy browsers.
Closes https://github.com/datagovsg/formsg-private/issues/100
**Fixes**:
- Prevent potential exposure of the window object via `rel='noopener noreferrer'`

fix: protect against potentially unsafe external links

---

src/app/modules/submission/email-submission/__tests__/email-submission.routes.spec.ts
src/app/modules/submission/email-submission/__tests__/email-submission.test.constants.ts
tests/unit/backend/helpers/generate-form-data.ts

Adds integration tests for Joi validation at the email submissions endpoint, in anticipation of merging all the middleware into a single controller.

test: add Joi integration tests for email submissions

---

src/app/models/user.server.model.ts
src/app/modules/bounce/__tests__/bounce-test-helpers.ts
src/app/modules/bounce/__tests__/bounce.controller.spec.ts
src/app/modules/bounce/__tests__/bounce.model.spec.ts
src/app/modules/bounce/__tests__/bounce.service.spec.ts
src/app/modules/bounce/bounce.controller.ts
src/app/modules/bounce/bounce.model.ts
src/app/modules/bounce/bounce.service.ts
src/app/modules/bounce/bounce.types.ts
src/app/modules/bounce/bounce.util.ts
src/app/modules/form/__tests__/form.utils.spec.ts
src/app/modules/form/form.utils.ts
src/app/modules/user/__tests__/user.service.spec.ts
src/app/modules/user/user.service.ts
src/app/services/sms/__tests__/sms.factory.spec.ts
src/app/services/sms/__tests__/sms.service.spec.ts
src/app/services/sms/__tests__/sms_count.server.model.spec.ts
src/app/services/sms/sms.factory.ts
src/app/services/sms/sms.service.ts
src/app/services/sms/sms.types.ts
src/app/services/sms/sms.util.ts
src/app/services/sms/sms_count.server.model.ts
src/types/bounce.ts
src/types/user.ts
tests/unit/backend/models/user.server.model.spec.ts

High operational workload due to need to contact email mode form admins when their form responses bounce.
Closes #903 and #949 
Text form admins and collaborators at their emergency contact numbers when responses are lost, and when their forms are automatically deactivated due to permanent bounces.
Notifications for lost submissions are limited to one email and one SMS a day via the `hasAutoEmailed` and `hasAutoSmsed` fields in the `Bounce` collection. However, SMSes for form deactivation are sent every time the form is deactivated.

feat: send SMS notification when submissions bounce

---

src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.controller.ts
src/public/modules/users/controllers/authentication.client.controller.js
src/public/modules/users/views/authentication/signin.client.view.html
tests/integration/helpers/express-auth.ts

Closes #629
At the finally clause of the send OTP function, add a timeout function which sets the show OTP delay notification flag to true after 20 seconds.
Priority of `vm.signInMsg.isMsg`, `vm.showOtpDelayNotification` and `vm.isOtpSending` is described in the conversation below ([link](https://github.com/opengovsg/FormSG/pull/748#discussion_r537451785)).
**AFTER**:
https://user-images.githubusercontent.com/14961285/103256818-84c9bd80-49c9-11eb-9a4e-afa63584e3ac.mov

Show OTP delay notification

---

src/public/modules/users/controllers/authentication.client.controller.js

Small fix for #748, prevents timeout from firing when page has already changed.
Also change the timeout to only be fired when sendOtp succeeds in the `then` clause rather than the `finally` clause

fix(AuthClientCtl): cancel timeout promise on page change

---

scripts/20200106_remove-custom-logo/delete-custom-logo-key.js
src/app/controllers/admin-forms.server.controller.js
src/app/controllers/forms.server.controller.js
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/admin-form.types.ts
src/public/modules/forms/admin/constants/covid19.js
src/public/modules/forms/admin/controllers/edit-start-page-modal.client.controller.js
src/public/modules/forms/admin/views/edit-start-page.client.modal.html
src/public/modules/forms/helpers/logo.js
src/types/form.ts
tests/unit/backend/controllers/forms.server.controller.spec.js

Closes https://github.com/opengovsg/FormSG/issues/787
- Remove `form.customLogo` which was no longer being used
- Remove `form.hasheader` which was no longer being used
- Remove `form.logo` which was no longer being used
- Create script for deletion of `form.customLogo`
_Notes_
- Once `form.customLogo` has been deleted, such forms with either default to the config in `startPage.logo` or if `startPage.logo` is non-existent (i.e. for all new forms), default to the agency logo.
- Script should be run before the code is merged.

chore: remove custom logo

---

src/public/modules/forms/helpers/decryption.worker.js
src/public/modules/forms/services/submissions.client.factory.js

Currently, the decryption worker returns an ad-hoc CsvRecord struct for consumption that is constructed in a piecemeal basis in the business logic.
We unify the logic to generate the `CsvRecord` struct in a class with the appropriate methods. 
Note that we cannot post a full-fledged object (i.e. including JS methods on the object) using `postMessage`, so we construct the appropriate fields as properties of the original CsvRecord, so minimal modification to `submission.client.factory.js` is necessary.
Ensure that CSV and attachment downloads continue to work as expected.

refactor: Add CsvRecord class instead of using adhoc CsvRecord struct

---

src/public/modules/core/views/landing.client.view.html
src/public/translations/en-SG/landing.json
src/public/translations/en-SG/main.json

Closes #995
Added an additional link to the landing page.
A future improvement could be to use the github icon instead of text, but that would necessitate a design change for the user guide button as well.
**Features**:
- Links to encourage greater awareness to our GitHub repository
- Refactored duplicate and unused `id` attribute
**BEFORE**:
See [form.gov.sg](https://form.gov.sg)
**AFTER**:
Desktop
Mobile

feat/github - Landing page links to this repository

---

src/public/modules/forms/base/directives/ng-intl-tel-input.js

Closes #1018
- PlaceholderNumberType property was set to FIXED_LINE if there was a home number field, but this was not reset when the next field is a mobile number field
- This led to placeholderNumberType persisting as FIXED_LINE when there is a home number field created before a mobile number field
- Fixed by setting placeholderNumberType as MOBILE when there is a mobile number field
**BEFORE**:
**AFTER**:
(tested on IE)

fix: incorrect mobile number placeholder

---

package-lock.json
package.json
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/admin/views/decrypt-progress.client.modal.html
src/public/modules/forms/services/submissions.client.factory.js
src/public/polyfills.js

Users can only cancel attachment downloads by closing the tab right now.
Closes #922
Adds a `AbortController` and hooks up the abort controller with the right links in the modal. Also terminates WebWorkers if there are any workers running (since downloads can continue to run even if the main `fetchStream` is cancelled if there are many outstanding download events queued up in the WebWorker queues.
Make sure downloads are properly canceled, and that future downloads from the same page (both CSV and attachments) are not affected.
- `abortcontroller-polyfill` : Provides AbortController functionality for IE11

feat: Add cancel download attachment feature

---

src/public/robots.txt

Crawlers may be overly aggressive and parse bundle.js for possible links.
This results in the crawler trying to request paths from FormSG that do not
actually exist
There are no real URLs in bundle.js, so don't let crawlers
read and parse the file lest they start to mistakenly query
for paths that don't exist

chore(robots): disallow NLB crawler to parse beyond loading the frontend

---

src/app/modules/webhook/webhook.utils.ts

Blocks TypeScript upgrade in #1009
Change the return type to `Promise<void>` from `Promise<any>`.

fix(webhook): change type from any to void, re-order imports

---

src/public/modules/forms/services/submissions.client.factory.js

Minor refactoring for the submissions client factory.
I suspect a more substantial rewrite will be needed for major refactoring, as there is a lot of global variable capture and usage which makes it hard to decompose existing functions.
* Pulled `generateDownloadUrl` into its own function
* Used `killWorker` function instead of calling worker terminate by itself.

refactor: Minor refactoring of the submissions client factory

---

src/public/modules/forms/base/directives/submit-form.directive.js
src/public/modules/forms/viewmodels/Form.class.js

Addresses #1044 
I did not manage to reproduce the bug in question. This is not a surprise as concurrency bugs are indeterministic by definition. However, based on the symptom and rarity of the bug, it is possible that the behavior is a result of edge cases caused by poor integration with AngularJS. Multiple code paths were thoroughly examined, and the appropriate refactor performed to improve code clarity and reduce the likelihood of bugs.
1. **controllerState variable refactor**
The `controllerState` variable is used to store the cloned form object in the `savedForm` property before fields were locked/disabled. It was previously not attached to the directive scope, but simply as a `const` which makes it a possible candidate to resolve the concurrency bug as AngularJS would not be …

refactor/submit-form: reduce possibility of race conditions in submission flow

---

src/public/main.js
src/public/modules/forms/helpers/decryption.worker.js
src/public/modules/forms/helpers/ndjsonStream.js
src/public/polyfills.js
webpack.common.js
webpack.prod.js

There was user feedback that CSV decryption is taking unusually long.
> For instance, I had to wait for >2 hours for surveys with 179 responses and 32 responses respectively. Both survey forms are of standard 15 mins type.
It is possible that some of the degraded performance is the result of overzealous polyfills in #981.
Instead of polyfilling functionality for all browsers, we detect the runtime browser by testing for the `window.document.documentMode` property, which is unique to Internet Explorer from version 5 onwards. Non-IE browsers will not have the native API replaced, even though `bundle.js` will still contain the polyfill.
The polyfills in question are:
- `web-streams-polyfill`
- `whatwg-fetch`
- `abortcontroller-polyfill`
- `text-encoding`
Chrome, Firefox and Safari all …

refactor/polyfills: browser detection, other fixes for performance gains

---

src/app/controllers/encrypt-submissions.server.controller.js

We do not have log messages linking storage mode submission IDs to request metadata (IP address, trace ID etc).
Add a log message which has submission ID and request metadata.

chore: log encrypt submission ID with request meta

---

tests/unit/backend/modules/webhook/webhook.utils.spec.ts

Jest tests are failing due to the following error:
The test uses `https://some.nonsense.website` to cover the case where the URL does not resolve to any valid IP, but apparently now that URL does actually exist.
Mock the DNS module in webhook tests so this issue does not crop up again.

test: mock DNS in webhooks tests

---

src/app/controllers/admin-forms.server.controller.js
src/public/modules/forms/admin/css/settings-form.css
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html

1. Form does not save if the schema has more than one nested key. The bug shows up if one were to expand `form.webhooks` beyond the single `url` property.
2. `<input>` elements on the settings panel did not have opacity set
3. Divider elements on the settings panel were not reusable
- Refactored divider CSS on the Settings page to be re-usable
**Bug Fixes**:
- Nested fields can be extended
- Opacity on input elements

fix/updates: bugs and refactors after building payments demo

---

.travis.yml

Builds are failing in Travis.
Remove the reliance on Travis [workspaces](https://docs.travis-ci.com/user/using-workspaces), which allow build stage environments to be shared, but is a beta feature for Travis CI that broke.
The downside is that webpack and Typescript compilation is now duplicated throughout the build stages.
If and when Travis restores workspace functionality, we can simply revert this PR to recover the faster build.

fix/travis: wean off Travis workspaces

---

src/public/modules/forms/admin/directives/edit-form.client.directive.js

The following MyInfo fields are set to return empty strings, and therefore should be deprecated:
- Home number
- Billing address
- Mailing address
- Highest education level
- School name
- Graduation year
The deprecation requires 3 steps:
1. Stop allowing admins to add these fields
2. Database migration to convert these fields to regular (non-MyInfo) fields
3. Drop support for these fields
This PR addresses step 1. We need to hide these fields from the admin panel while still supporting existing fields, so we simply filter out the fields in the form builder.

feat: deprecate MyInfo fields for V3 (step 1 - frontend)

---

src/public/modules/forms/base/componentViews/field-table.client.view.html

In table fields, whenever dropdown fields are opened in the last 2 rows, we add padding to the bottom of the field so the dropdown options do not get hidden. This is broken in mobile view, likely since #894, resulting in dropdown options being hidden for the last row.
The problem is that table rows in mobile are `display: block;` as opposed to `display: flex;` like in desktop, resulting in the padding being applied incorrectly. The fix was to apply the padding on the table field as a whole instead of just the last row, which has the same effect but works properly in mobile.

fix: apply dropdown padding on whole table

---

src/shared/util/file-validation.ts

Allows .oa files in attachments.

feat: allow .oa attachments

---

src/public/modules/forms/base/directives/submit-form.directive.js
src/public/modules/forms/viewmodels/Fields/CheckboxField.class.js
src/public/modules/forms/viewmodels/Fields/SingleAnswerField.class.js

Blank submissions in storage mode, likely due to a bug arising due to the interaction of the Safari browser with AngularJS.
The existing form validation is clearly not working with Safari, otherwise blank submissions would be prevented. Hence add the following additional layers of checks:
1. Throw an error when attempting to get a response from a field which is visible and required but empty.
2. Check for the `$invalid` property of individual fields in addition to the form as a whole.
Closes #1044

fix: interrupt submission if field is blank

---

src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.util.ts
src/app/modules/submission/email-submission/__tests__/email-submission.util.spec.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/app/modules/submission/email-submission/email-submission.util.ts
src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/public/modules/forms/helpers/process-decrypted-content.js
src/types/field/fieldTypes.ts
tests/end-to-end/helpers/util.js
tests/unit/backend/controllers/email-submissions.server.controller.spec.js

Closes [#101](https://github.com/datagovsg/formsg-private/issues/101)
- Mask UID NRIC before generating autoreply using a function
- To be refactored in #1104 
**BEFORE**:
**AFTER**:

feat: mask cp uid in autoreply to respondent

---

src/app/controllers/admin-forms.server.controller.js

Logic fields cannot be deleted (and probably other buggy behaviour yet to be uncovered).
In the form updating code on the server, a `_.extend` was changed to a `_.merge` in #1061. However, the two functions behave very differently, as illustrated in this example:
The fix is to revert to `_.extend`.

fix: fix updating of forms

---

docker-compose.yml

Upgrades local development to use MongoDB 4.0 as part of https://github.com/datagovsg/formsg-private/issues/27
Change the image used in `docker-compose.yml` to `mongo:4.0`.
Note that the local development Docker volume is not compatible and should be removed via e.g. `docker volume prune`. This will wipe your existing local development database and start your local development environment on a clean slate.

build: upgrade development to use mongo:4.0 image

---

.template-env
docker-compose.yml
tests/.test-full-env

The `SPCP_COOKIE_MAX_AGE` environment variable is unused, but still remains in the development and test environment.
Addresses https://github.com/datagovsg/formsg-private/issues/112
Remove it from the codebase.

refactor: remove SPCP_COOKIE_MAX_AGE

---

package-lock.json
package.json
src/app/modules/auth/auth.utils.ts
src/app/modules/billing/billing.controller.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/types/vendor/express.d.ts

The types for express-session has finally (??? 3 months ago) been fixed to allow for better session data types.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#diff-0d13c95494fa97febecd0fbc1fb1b8f6e17bbcaedb8c88d10a0b655046e1c97b
This PR updates the types for session user data stored in our application. I don't really see an alternate path without asserting that session is non-null (due to auth middleware), with the exception of maybe inlining the middleware into the controller... which basically defeats the point of the discussion the team had a couple months ago about using auth as a middleware.

chore: update package and typings for express session

---

.travis.yml

This reverts commit 7e55066731ad51430e27c02472f129453ea90886.
Repeated builds in the CI pipeline was wasteful but necessary due to a bug with Travis workspaces that was in beta.
As the problem appears to have been fixed by Travis, revert the original PR for faster tests and builds.

Revert "fix/travis: wean off Travis workspaces (#1067)"

---

src/public/modules/forms/base/resources/icon-types.js

Home number field icon was accidentally deleted in #1073 as `'homeno'` is both a MyInfo attribute and a field type.
Add the icon back.

fix: add back home number field icon

---

src/app/utils/field-validation/validators/mobileNoValidator.ts

- Mobile number signature validation was dropped during migration to ts for mobile number validator
- Add signature validation to mobile number validator

fix: Release 4.58.1 hotfix - mobile signature validation

---

src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html
tests/end-to-end/helpers/util.js

We may expect users to have many Checkbox options and adding them one-by-one to FormSG is troublesome. As such, we want Checkbox options to follow Dropdown options so that Checkbox options can be edited by a `textarea` with each option in each line in the `textarea`.
Closes #743
Only frontend changes. Edit the conditional rendering (i.e. `ng-if`) such that Dropdown and Checkbox show the same `textarea` for Options and Radio button will show its usual one-by-one options.
In the controller, edit the `if` clauses so that we now transform `fieldOptions` into `fieldOptionsFromText` when rendering Options and we check for `fieldOptionsFromText` instead of `manualOptions` when saving `fieldOptions`.
**BEFORE**:
**AFTER**:
Note: I have not checked for test breakages yet.

feat: use textarea for providing checkbox options

---

init-mongo.js

The MongoDB initialisation script was providing the wrong URL to the `agency.form.sg` S3 bucket, so logos were not working for the longest time.
**Bug Fixes**:
Fixed the URL to `agency-logo.form.sg` S3 bucket instead.

fix: agency logos on development environment

---

src/app/modules/billing/__tests__/billing.factory.spec.ts
src/app/modules/billing/__tests__/billing.service.spec.ts
src/app/modules/billing/billing.errors.ts
src/app/modules/billing/billing.factory.ts
src/app/modules/billing/billing.service.ts
src/app/modules/spcp/__tests__/spcp.controller.spec.ts
src/app/modules/spcp/__tests__/spcp.factory.spec.ts
src/app/modules/spcp/__tests__/spcp.service.spec.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.factory.ts
src/app/modules/spcp/spcp.service.ts

The `addLogin` function is part of the SPCP module, but it really belongs to the Billing module as it relates to tracking logins for e-service IDs. This is blocking #1175 as the MyInfo module needs to share the code for adding logins.
Move the `addLogin` function to the Billing module.

refactor: move addLogin method to Billing module

---

src/app/routes/admin-forms.server.routes.js

> Note that this PR merges into release candidate branch `release-v4.59.0`.
This PR fixes a bug (on staging, not on prod yet) where only a single collaborator can be added to a form. This arises due to the Joi validator for the updateform endpoint not accounting for current collaborator objects in `form.permissionList` having an `_id` key due to the database schema.
- add `_id` key in permissionList object for updateForm validator

fix: add _id key in permissionList object for updateForm validator

---

src/app/modules/myinfo/myinfo.adapter.ts
src/app/modules/myinfo/myinfo.factory.ts
src/app/modules/myinfo/myinfo.service.ts
src/app/modules/myinfo/myinfo.types.ts
src/app/modules/myinfo/myinfo.util.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html

Contains the following changes:
1. Makes MyInfo vehicle number always editable to preserve behaviour between MyInfo V2 and V3
2. Clears MyInfo cookie at the point of submission
3. Refactors settings page frontend to use `.includes` instead of an extended series of `||`
4. Extracts type guard for relay state in the backend

feat: update editable fields and clear cookie upon submission

---

src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/myinfo/myinfo.adapter.ts
src/app/modules/myinfo/myinfo.format.ts
src/app/modules/spcp/spcp.controller.ts
src/config/feature-manager/spcp-myinfo.config.ts
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/users/controllers/billing.client.controller.js
src/public/modules/users/views/billing.client.view.html
src/types/express.locals.ts
tests/end-to-end/helpers/selectors.js

Workpass status returned by MyInfo is now converted to TitleCase before setting it as the field value. This is because MyInfo staging returns the value in uppercase, whereas the documentation says that it should be in TitleCase, and the allowed values in the dropdown field are in TitleCase.
Preview submission emails were previously not including the NRIC for MyInfo forms. This was fixed by adding the relevant cases in the preview submissions pipeline.
Label of the MyInfo auth type on the Settings tab was changed to "SingPass (MyInfo)". However, this broke e2e tests as spaces are not allowed in CSS selectors, so some adjustments to the CSS classes had to be made.
Label of the MyInfo auth type in the Billing panel was changed to "SingPass (MyInfo)" in desktop view and "SP(MI)" in mobile …

fix: format workpass status correctly, preview submissions, copy changes

---

src/public/main.css
src/public/modules/forms/base/componentViews/end-page.html
src/public/modules/forms/base/components/end-page.client.component.js
src/public/modules/forms/base/css/end-page.css
src/public/modules/forms/base/css/start-end-page.css

Shows form submission timestamp above "Thank you for..." upon successful form submission.
Closes #1103 
The timestamp shown may not be equal to the actual form submission timestamp in the database (difference of at most 1 min unless very poor network conditions after submission), because this rendered timestamp is generated on the fly upon render. Let me know if this is not okay.
**BEFORE**:
**AFTER**:

feat: add timestamp to form submission end page

---

src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.service.spec.ts
src/app/utils/handle-mongo-error.ts
tests/unit/backend/utils/handle-mongo-error.spec.ts

This PR removes msgSrvcName validation from the form schema, and improves database error message shown to front end.
Closes #1208

fix: remove form.msgSrvcName validation and add human error recovery message

---

src/app/services/captcha/captcha.service.ts

Incorrect captcha errors are polluting our logs by being leveled as error logs when they are more of an info/warning level.
This PR changes the error level from "error" to "warn"

feat: change logging of incorrect captcha response from error to warn

---

src/app/modules/submission/email-submission/__tests__/email-submission.service.spec.ts
src/app/modules/submission/email-submission/__tests__/email-submission.util.spec.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/app/modules/submission/email-submission/email-submission.middleware.ts
src/app/modules/submission/email-submission/email-submission.service.ts
src/app/modules/submission/email-submission/email-submission.util.ts
src/app/modules/submission/submission.service.ts
src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/app/services/mail/mail.types.ts
src/app/views/templates/submit-form-email.server.view.html
src/types/express.locals.ts
tests/unit/backend/controllers/email-submissions.server.controller.spec.js
tests/unit/backend/helpers/generate-email-data.ts

Part 1 of #1104
- This PR addresses the comments made in #1070 and refactors the implementation of #1109 into class methods instead of a standalone masking function
- As per the objectives stated in #1104, subsequent PR will encapsulate the data processing functions in the middlewares`EmailSubmissionsMiddleware.validateEmailSubmission`, `AdminFormController.passThroughSpcp`, 
`SpcpController.appendVerifiedSPCPResponses` into the same class

refactor: encapsulate parsed responses (part 1)

---

package-lock.json
package.json
src/app/modules/myinfo/__tests__/myinfo.service.spec.ts
src/app/modules/myinfo/__tests__/myinfo.test.constants.ts
src/app/modules/myinfo/myinfo.adapter.ts
src/app/modules/myinfo/myinfo.format.ts

Upgrades to the latest beta release of `@opengovsg/myinfo-gov-client`, which enforces stricter type-checking of the data returned by MyInfo.
The MyInfo adapter layer was updated with the necessary additional type checks.

feat: upgrade to beta version of myinfo-gov-client

---

src/app/modules/spcp/__tests__/spcp.controller.spec.ts
src/app/modules/spcp/__tests__/spcp.routes.spec.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.middlewares.ts
src/app/modules/spcp/spcp.util.ts

The SingPass and CorpPass /redirect and /validate endpoints currently support MyInfo forms for backwards compatibility. Since clients should all be updated to the version of the frontend post-MyInfo migration, this support can now be removed.
Closes #1116

feat: remove MyInfo support from SPCP endpoints

---

src/app/modules/myinfo/__tests__/myinfo.adapter.spec.ts
src/app/modules/myinfo/__tests__/myinfo.controller.spec.ts
src/app/modules/myinfo/__tests__/myinfo.factory.spec.ts
src/app/modules/myinfo/__tests__/myinfo.routes.spec.ts
src/app/modules/myinfo/__tests__/myinfo.service.spec.ts
src/app/modules/myinfo/__tests__/myinfo.test.constants.ts
src/app/modules/myinfo/__tests__/myinfo.test.data.ts
src/app/modules/myinfo/myinfo.controller.ts
src/app/modules/submission/email-submission/__tests__/email-submission.routes.spec.ts

Adds unit tests for new code introduced during MyInfo V3 migration, as well as integration tests for MyInfo routes as well as on the email submissions endpoint for MyInfo forms.
Part of #1234

test: add tests for new MyInfo functionality

---

src/public/translations/en-SG/main.json

Link in frontend was accidentally deleted in https://github.com/opengovsg/FormSG/pull/825/files
**Bug Fixes**:
- Restore missing email reliability link by pointing it to http://go.gov.sg/form-email-reliability

fix: restore link for email reliability

---

package-lock.json
package.json
src/app/modules/myinfo/myinfo.controller.ts

When the MyInfo consent flow returns an error, we support both `error-description` (note hyphen) and `error_description` (note underscore) in the query parameters. This is because we were previously unsure which one would be returned - the [documentation](https://public.cloud.myinfo.gov.sg/myinfo/api/myinfo-kyc-v3.1.0.html#operation/getauthorise) says that it should be `error_description`, but the sandbox and staging APIs both returned `error-description`. Now that we have confirmed that production returns `error-description` as well, we can drop support for `error_description`.
Part of #1234 
Drop support for `error_description`. For safety, in case MyInfo decides to add other query parameters, also add `unknown(true)` to the Joi validation.
Mockpass previously returned …

feat: remove MyInfo error_description support

---

src/app/modules/spcp/__tests__/spcp.service.spec.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.service.ts
src/app/modules/spcp/spcp.types.ts

In the past, SPCP SAML artifacts were not URL-encoded when we received them at our login endpoints. This means that Express would automatically parse `+` characters as spaces, and we had to manually change them back to `+`.
SAML artifacts are now URL-encoded so this is no longer necessary.
Closes #1322 
Remove the code which replaced spaces with + in the SAML artifact.
Once this change was made, the `parseOOBParams` function was taking in the SAML artifact as a parameter and returning it unchanged. This made little sense, so the function signature was changed to stop returning the SAML artifact.

refactor: stop replacing spaces in SAML artifact

---

src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/auth.errors.ts
src/app/modules/core/core.errors.ts
src/app/modules/submission/submission.errors.ts
src/app/modules/submission/submission.service.ts
src/app/modules/user/user.errors.ts
src/app/modules/webhook/webhook.errors.ts
src/app/services/sms/sms.errors.ts
src/app/services/sms/sms.service.ts

This PR removes the unused `status` class variable in `ApplicationError` class that may sometimes cause confusion when poring through logs for issues, since the default value is `500`.
Also updates the `meta` key in `ApplicationError` to accept anything, since we may want to store more info from the creation of the error; e.g. storing original error that resulted in an `ApplicationError` being created for logging purposes.
**Features**:
- remove `status` key in `ApplicationError` class and all its usages
- update `meta` key in `ApplicationError` to unknown type

feat: remove status key in ApplicationError class, update meta key to unknown type

---

tests/unit/backend/helpers/generate-form-data.ts
tests/unit/backend/utils/field-validation/mobile-num-validation.spec.ts

Closes #1171 
- Ports over jasmine tests to jest tests for mobile number validator
- Adds test for mobile number signature validation

test: Expand test cases for mobile number validator to cover signature validation

---

src/public/modules/forms/admin/views/edit-fields.client.modal.html

added rows attribute to email confirmation body textarea to increase height to something reasonable for an email
email confirmation > email body textarea is too short. even if your email is very short, it is difficult to scroll to where you want to edit and there is a tendency to miss it. 
Before:
After:

fix: add rows attr to email confirmation email body textarea

---

src/app/modules/analytics/analytics.controller.ts
src/public/services/AnalyticsService.ts
src/types/analytics.ts

It just occurred to me that `AnalyticStats` was in fact a _data transfer object_ that presents a specific data format to the client, so I renamed it. I'm leaving the file in `/types/analytics` instead of `/shared` so that the cleanup can happen all in one go in a future PR.

refactor: rename type to AnalyticStatsDto

---

src/app/modules/bounce/__tests__/bounce.service.spec.ts
src/app/modules/bounce/bounce.service.ts
src/app/modules/bounce/bounce.util.ts
src/app/modules/submission/email-submission/__tests__/email-submission.routes.spec.ts
src/app/modules/submission/email-submission/__tests__/email-submission.service.spec.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/app/modules/submission/email-submission/email-submission.middleware.ts
src/app/modules/submission/email-submission/email-submission.service.ts
src/app/modules/submission/email-submission/email-submission.util.ts
src/app/modules/submission/submission.errors.ts
src/app/modules/user/user.utils.ts
src/app/modules/verification/verification.service.ts
src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.errors.ts
src/app/services/mail/mail.service.ts
src/app/services/mail/mail.utils.ts
src/app/services/sms/__tests__/sms.factory.spec.ts
src/app/services/sms/__tests__/sms.service.spec.ts
src/app/services/sms/sms.errors.ts
src/app/services/sms/sms.factory.ts
src/app/services/sms/sms.service.ts
src/app/services/sms/sms.util.ts
src/public/modules/forms/base/components/verifiable-field.client.component.js
tests/unit/backend/controllers/email-submissions.server.controller.spec.js
tests/unit/backend/modules/verification/verification.service.spec.ts

This PR improves the type safety and error handling of `MailService` and `SmsService` by refactoring the exposed functions into their `neverthrow`n variants.
Sorry for the huge PR, they were pretty interconnected; I tried to make the commits as concise as possible for ease of reviewing commit-by-commit.
Closes #1260
- convert `MailService` functions to neverthrown variant
- convert `SmsService` functions to neverthrown variant
- use new neverthrown fns from mail and sms services in `VerificationService`
- store original thrown Twilio send errors in `SmsSendError` for logging purposes
- store original thrown mail send errors in `MailSendError` for logging purposes
- All affected tests have been updated to conform to the new refactored functions.
**For mail service**
1. …

ref: convert mail and sms services into neverthrown variants

---

src/app/modules/spcp/__tests__/spcp.controller.spec.ts
src/app/modules/spcp/__tests__/spcp.service.spec.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.service.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/config/feature-manager/spcp-myinfo.config.ts
src/config/feature-manager/types.ts

CorpPass is cutting over to its new cloud infrastructure, and part of the migration process involves a rehearsal on production. While this rehearsal is happening, we don't want any public users to be able to log in to CorpPass, but we still need to be able to test the new cloud infrastructure with our own test form.
Switch to CorpPass Cloud only for a specific test form ID.
The cloud migration involves two changes:
- Changing to a new OOB verification endpoint (`CORPPASS_IDP_ENDPOINT` env var)
- Changing to a new CorpPass public key (`CP_IDP_CERT_PATH` env var)
The approach is to get all forms to use the old env vars, while using the new env vars _only_ for a specific form that we choose.
Why does this work? **Outside of the rehearsal hours**, the _old_ CorpPass infrastructure will be up. …

feat: switch to CorpPass Cloud for test form

---

src/app/controllers/forms.server.controller.js
src/app/services/intranet/__tests__/intranet.factory.spec.ts
src/app/services/intranet/__tests__/intranet.service.spec.ts
src/app/services/intranet/intranet.factory.ts
src/app/services/intranet/intranet.middleware.ts
src/app/services/intranet/intranet.service.ts
src/app/utils/request.ts
src/config/feature-manager/index.ts
src/config/feature-manager/intranet.config.ts
src/config/feature-manager/types.ts
src/loaders/express/index.ts
src/public/modules/forms/base/controllers/submit-form.client.controller.js
tests/unit/backend/controllers/forms.server.controller.spec.js

SingPass/CorpPass do not work on the intranet due to an issue with SIS cookies, but nothing in the UI alerts users to this. When they attempt to log in to SingPass/CorpPass, everything seems to be successful, but when they are redirected back to the form, they are not logged in.
Show a permanent Toastr when users access a SPCP/MyInfo form from the intranet.
Detection of requests from the intranet was implemented by reading in a list of intranet IPs from a static file, which must be transferred into the server.
In addition, the opportunity was taken to log intranet usage for analytics purposes.
In the `createReqMeta` utility function, we use the `req.url` property to log the URL of the request. However, this does not work well with Express Router, as only the path after the router is …

feat: show error Toastr for intranet users on SPCP forms

---

.github/.mergify.yml

This project has over 200 dependencies, resulting in around 5-10 dependency upgrades a day. All these upgrades are currently manually approved and merged by engineers, which requires time and effort.
Use [mergify](https://mergify.io/) to merge dependabot PRs which pass tests, except major version changes.
This screenshot from the Mergify [config editor](https://dashboard.mergify.io/github/opengovsg/config-editor) demonstrates that PR #1417 (patch version change, CI passing) would be automatically merged using this config:
Whereas this screenshot shows that PR #1422 (patch version change, CI failing) would not be merged:
And this screenshot shows that PR #1423 (major version change, CI passing) would not be merged:

build: automate dependency upgrades using mergify

---

src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.service.ts
src/app/modules/auth/auth.utils.ts
src/app/modules/user/__tests__/user.controller.spec.ts
src/app/modules/user/user.service.ts
src/app/modules/user/user.utils.ts
src/app/utils/hash.ts
src/app/utils/otp.ts

1. In `src/app/utils/hash`, we have utility functions which wrap calls to `bcrypt.hash` and `bcrypt.compare` in `ResultAsync`. However, we return a generic `ApplicationError` when these functions fail. This means that downstream functionality has to deal with the error as a generic `ApplicationError` without context of where it came from, e.g. when deciding what status code and message to return in `mapRouteError`. Developers have to search through all the service functions called in controllers one by one until they find where the `ApplicationError` was returned.
2. We have a `generateOtp` utility, but all the times when we need to call it, we have to create not just the OTP but a hash of it as well. Since these two bits of functionality always come together, it makes sense to have a …

refactor: return custom error from utils when bcrypt fails

---

src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/admin-forms.server.routes.js

Remove dangling unused key in Joi validation for `/adminform/copy` endpoint. 
Checked via Cloudwatch logging and no instances of the `isTemplate` key being sent for the past month.
Closes #792

feat: remove isTemplate validation on duplicate template api

---

src/public/modules/forms/base/components/verifiable-field.client.component.js

Across nearly all APIs in this repo, the server returns a JSON with a `message` key when an error occurs. However, the Verification module is an exception, as it returns one of a set of custom strings (e.g. `'SEND_OTP_FAILED'`, '`INVALID_OTP`'), and the frontend contains a switch statement to determine what error message to display.
We want APIs to behave consistently, so it would be good for the Verification module to return error objects in the form `{ message: 'some error message' }`. However, this would be a backwards-incompatible change as the current frontend would render the entire JSON object instead of just the message string. 
This PR ensures that the API change will be backwards-compatible by checking for a `message` property on the error. #1440 will address the actual API …

refactor: check for .message in verification error

---

src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.service.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts
src/app/routes/admin-forms.server.routes.js

This PR cleans up the janky `authEncryptedResponseAccess` middleware used in the `/adminform/submissions/download` endpoint and collapses the used middlewares in the `handleStreamEncryptedResponses` controller handler.
This PR is just one of the few PRs needed to remove total usage of the `authEncryptedResponseAccess` middleware.
Related to #1434
- feat: collapse middlewares for submission download endpoint
- unit tests have been added (where possible) for the refactored controller handler function

ref: collapse middlewares of /adminform/submissions/download

---

src/app/services/sms/sms.util.ts

a user reported that an OTP SMS cut off at 153 characters. after investigation, it appears that SMSes longer than 153 chars are sent in 153-char chunks and rebuilt by the recipient's device. 
to avoid future device-specific errors, have shortened the otp sms copy to below 153 chars. 
https://www.twilio.com/docs/glossary/what-sms-character-limit

fix: shortened sms otp copy for accessibility

---

src/app/controllers/frontend.server.controller.js

Google analytics currently does not work if a form is embedded on a different site.
- Set GA cookies to SameSite=None; Secure to allow iframe tracking
- Browsers have recently tightened cookie rules by ensuring the top-level domain (the domain in your browser navbar) is the same as the domain of the request before sending cookies in that request. In our case, the default SameSite=Lax for GA cookies meant that GA cookies were not being sent as the top-level domain eg. https://ogp-checkfirst-test-staging.netlify.app/ differed from the requests to http://www.google-analytics.com. SameSite=None tells the browser to ignore this same-domain check and attach the cookies on the GA request.
- As far as I can tell, setting SameSite=None has minimal security implications
- Because SameSite=None can …

feat: add samesite GA cookie property to enable GA in iframe

---

src/app/controllers/admin-forms.server.controller.js
src/app/routes/admin-forms.server.routes.js
src/public/modules/forms/base/components/feedback-form.client.component.js
src/public/modules/forms/services/form-feedback.client.factory.js

feat: remove passThroughFeedback

---

src/public/modules/forms/admin/views/decrypt-progress.client.modal.html
src/public/modules/forms/admin/views/download-all-attachments.client.modal.html
src/public/modules/forms/admin/views/view-responses.client.view.html

csv and attachments download has been stable for some time now. we no longer need to communicate that it is a beta feature.
(in comparison, still keeping webhooks as beta due to lack of retries)

chore: take csv and attachments download out of beta

---

src/types/field/numberField.ts
tests/unit/backend/helpers/generate-form-data.ts
tests/unit/backend/utils/field-validation/date-validation.spec.ts
tests/unit/backend/utils/field-validation/decimal-validation.spec.ts
tests/unit/backend/utils/field-validation/dropdown-validation.spec.ts
tests/unit/backend/utils/field-validation/home-num-validation.spec.ts
tests/unit/backend/utils/field-validation/nric-validation.spec.ts
tests/unit/backend/utils/field-validation/number-validation.spec.ts
tests/unit/backend/utils/field-validation/radio-button-validation.spec.ts
tests/unit/backend/utils/field-validation/rating-validation.spec.ts
tests/unit/backend/utils/field-validation/text-validator.spec.ts

Part of #7
- Migrates all the field validator tests from jasmine to jest / typescript
- Jasmine tests to be deleted after 12 Apr 2021

refactor: migrate field validator tests to typescript

---

src/app/modules/spcp/__tests__/spcp.controller.spec.ts
src/app/modules/spcp/__tests__/spcp.service.spec.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.service.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/config/feature-manager/spcp-myinfo.config.ts
src/config/feature-manager/types.ts

#1392 added custom handling code for a CorpPass test form specifically to accommodate the CorpPass Cloud migration rehearsal. This code is no longer necessary as the rehearsal went successfully.
Delete the custom handling code.

feat: revert custom code for CorpPass cloud migration

---

src/app/modules/verification/__tests__/verification.controller.new.spec.ts
src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.model.spec.ts
src/app/modules/verification/__tests__/verification.service.new.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.errors.ts
src/app/modules/verification/verification.factory.ts
src/app/modules/verification/verification.middleware.ts
src/app/modules/verification/verification.model.ts
src/app/modules/verification/verification.routes.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.util.ts
src/types/verification.ts

Builds on #1450
See #1450
This is the 2nd part of the solution, which focuses on the `GET /transaction/:transactionId` endpoint. It has the following additional changes:
- Renames the old `verification.factory` to `verification.middleware`, and adds an actual `verification.factory` to export service methods
See #1450

refactor: use neverthrow in /transaction/:transactionId (part 2)

---

src/app/modules/verification/__tests__/verification.controller.new.spec.ts
src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.model.spec.ts
src/app/modules/verification/__tests__/verification.service.new.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.factory.ts
src/app/modules/verification/verification.middleware.ts
src/app/modules/verification/verification.model.ts
src/app/modules/verification/verification.routes.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.util.ts
src/types/verification.ts

Builds on #1451
See #1450
This is the 3rd part of the solution, which focuses on the `POST /transaction` endpoint.
See #1450

refactor: use neverthrow in /transaction (part 3)

---

src/app/modules/verification/__tests__/verification.controller.new.spec.ts
src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.model.spec.ts
src/app/modules/verification/__tests__/verification.service.new.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.factory.ts
src/app/modules/verification/verification.middleware.ts
src/app/modules/verification/verification.model.ts
src/app/modules/verification/verification.routes.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.util.ts
src/types/verification.ts

Builds on #1452
See #1450
This is the 4th part of the solution, which focuses on the `POST /transaction/:transactionId/reset` endpoint.
See #1450

refactor: use neverthrow in /:transactionId/reset (part 4)

---

src/app/modules/verification/__tests__/verification.controller.new.spec.ts
src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.model.spec.ts
src/app/modules/verification/__tests__/verification.service.new.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.factory.ts
src/app/modules/verification/verification.middleware.ts
src/app/modules/verification/verification.model.ts
src/app/modules/verification/verification.routes.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.types.ts
src/app/modules/verification/verification.util.ts
src/types/verification.ts

Builds on #1453
See #1450
This is the 5th part of the solution, which focuses on the `POST /transaction/:transactionId/otp` endpoint.
See #1450

refactor: use neverthrow in /:transactionId/otp (part 5)

---

src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.utils.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts
src/app/routes/admin-forms.server.routes.js
src/types/submission.ts

This PR cleans up the janky `authEncryptedResponseAccess` middleware used in the `/adminform/submissions` endpoint and collapses the used middlewares in the `handleGetEncryptedResponse` controller handler.
This PR is just one of the few PRs needed to remove total usage of the `authEncryptedResponseAccess` middleware.
Related to #1434
- feat: inline auth middlewares for `handleGetEncryptedResponse`
- unit tests have been added for the refactored controller handler function

ref: collapse middlewares of GET /:formId/adminform/submissions route

---

src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.service.ts
src/app/routes/admin-forms.server.routes.js
src/types/submission.ts

This PR cleans up the janky `authEncryptedResponseAccess` middleware used in the `/adminform/submissions/metadata` endpoint and collapses the used middlewares in the `handleGetMetadata` controller handler.
This PR is just one of the few PRs needed to remove total usage of the `authEncryptedResponseAccess` middleware.
Related to #1434
- feat: inline auth middlewares for `handleGetMetadata`
- move `withUserAuthentication` middleware of submissions count API route to execute first
- unit tests have been added for the refactored controller handler function

ref: collapse middlewares of GET /adminform/submissions/metadata route

---

src/app/modules/form/__tests__/form.service.spec.ts
src/app/modules/form/form.service.ts
src/app/modules/submission/email-submission/email-submission.util.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts

The `checkFormSubmissionLimitAndDeactivateForm` function returns a `Promise<Result>` instead of `ResultAsync`, making it impossible to chain with other async operations using `andThen`.
Refactor the function to return a `ResultAsync` instead. In the process, the return type was expanded to include `PossibleDatabaseError`. This made it necessary to include all the `PossibleDatabaseError` types in the respective `mapRouteError` functions used by controllers which depend on `checkFormSubmissionLimitAndDeactivateForm`.

refactor: convert submission limit service function to ResultAsync

---

src/public/modules/forms/admin/directiveViews/settings-form.client.view.html
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/forms/admin/views/activate-form.client.modal.html
src/public/modules/forms/admin/views/edit-myinfo-field.client.modal.html
src/public/modules/forms/base/componentViews/end-page.html
src/public/modules/forms/base/componentViews/start-page.html
src/public/modules/forms/base/css/start-end-page.css
src/public/translations/en-SG/landing.json
tests/end-to-end/helpers/selectors.js
tests/end-to-end/helpers/util.js

Make appropriate UI updates to FormSG to prepare for Corppass migration.
Closes #1446
**Features**:
- update copy for ui
- update all mentions of singpass and corppass to use new casing
- make necessary frontend changes for corporate singpass button
- add tooltip beside corppass option in settings > enable authentication
- update e2e tests for new changes
<details>
<summary> Click here to show screenshots </summary>
**BEFORE**:
**AFTER**:
</details>

refactor(corppass-ui): make ui changes for corppass

---

src/app/modules/verification/verification.controller.ts

Adds our standard logging info to controllers in the Verification module, as this was previously left out.

chore: add createReqMeta to verification module logging

---

src/app/routes/api/v3/auth/__tests__/auth.routes.spec.ts
src/app/routes/api/v3/auth/auth.routes.ts
src/app/routes/api/v3/auth/index.ts
src/app/routes/api/v3/v3.routes.ts
src/public/modules/users/services/auth.client.service.js

Updates current user auth endpoints to their `/api` rooted endpoints to follow a RESTful hierarchy.
Closes #1499 
**Features**:
- duplicate auth endpoint functionality and update endpoints
- duplicated integration tests for new endpoint
- update v3 router to use new endpoints
- update frontend api calls to use new endpoints

ref(auth-api): duplicate auth endpoints to new /api/v3 router

---

src/shared/util/stringify-safe.ts
tests/unit/backend/utils/stringify-safe.spec.ts

Fix bug where bigints > MAX_INTEGER would lose fidelity. Convert to string instead.
Also converted the test for stringift-safe.ts to Typescript.
Closes #1552

fix: convert bigint to string, not number to avoid losing fidelity

---

src/app/modules/form/admin-form/__tests__/admin-form.routes.spec.ts

Two tests are flakey, one because of Date checks and one because of an indeterministic result from query. This PR fixes both issues

fix: /adminform integration tests being flakey by loosening some checks

---

src/public/modules/forms/services/submissions.client.factory.js

When storage mode responses are downloaded consecutively, the `workerPool` array is not being cleared properly and thus CSV responses are being piped to workers that have already been killed in a previous run.
This PR fixes the issue by clearing the worker pool on invoking the download function.
Closes #1502
First run: push 3 workers
[ alive, alive, alive ]
End of first run, all killed
[ dead, dead, dead ]
Start of second run: push 3 more workers without clearing
[ dead, dead, dead, alive, alive, alive ]
posting message to dead workers in round robin fashion means that some csv responses will be piped to dead workers that will never respond, resulting in infinite loop in the final conditional check
```ts
experimentalCsvGenerator.length() + errorCount + unverifiedCount >= …
```

fix: fix consecutive storage mode responses downloads from failing

---

src/app/modules/form/admin-form/__tests__/admin-form.routes.spec.ts

Tests seems to still be failing for a particular test.
This PR (attempts) to fix the flakiness by using hardcoded dates instead of using relative dates for the affected test, which may behave differently in different machines (like CI/CD)

test: fix flakiness (again) by hardcoding created dates

---

src/app/modules/form/public-form/__tests__/public-form.controller.spec.ts
src/app/modules/form/public-form/__tests__/public-form.routes.spec.ts
src/app/modules/form/public-form/public-form.controller.ts
src/types/api/core.ts
tests/unit/backend/helpers/jest-db.ts

current public form end point does not have any integration tests and only has unit tests on the controller. this PR adds integration tests for HTTP errors.
Part of #1513 
Added integration tests for `GET /:formId/publicform` endpoint.

Test: publicform integration tests

---

src/app/modules/feedback/__tests__/feedback.service.spec.ts

Form feedback unit tests have been flaking for months because of a non-deterministic `expect` statement. The issue is that form feedback is sorted by creation order when it is retrieved, but the feedback documents in the test are created asynchronously, so sometimes the array of documents is not in the expected order.
Sort the array of feedback documents before comparing.

test: fix flaky form feedback test

---

src/app/modules/form/admin-form/admin-form.controller.ts

The current `admin-form/controller` uses `if/else` within the file, which makes it difficult to understand and maintain.
Rewrote the `handleEncryptPreviewSubmission` function to use a neverthrow chain, which makes it simpler to understand and parse. 
**Design Considerations** 
1. rewriting to neverthrow chains means that there are no explicit unwrapping and no more "wrapper-variables", whose sole function is to denote a `result` type and then unwrap it. 
2. simpler error handling - `mapErr` at the end makes it clear what happens rather than having control flow cut short halfway within the controller

Refactor(admin-form.controller): encrypt preview submission

---

.eslintrc
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts

Disables the `no-await-without-trycatch` `eslint` plugin, which is no longer necessary as `neverthrow` is used throughout the backend.

chore: disable no-await-without-trycatch in backend

---

src/public/modules/core/controllers/edit-contact-number-modal.client.controller.js

updating admin user's contact number would fail since the generation and verification of OTP endpoint is incorrect
**Bug Fixes**:
- call correct user update emergency contact endpoints

fix: call correct user update emergency contact endpoint

---

src/app/modules/form/admin-form/admin-form.routes.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.submissions.routes.spec.ts
src/app/routes/api/v3/admin/forms/admin-forms.submissions.routes.ts
src/public/modules/forms/services/submissions.client.factory.js

This is part 1 of #1520. This PR addresses the fact that URL query parameters should not be used to identify a resource. rather, they should be used to identify _properties_ of a resource. Hence, there is a new controller + endpoint set up so that the api endpoint is restful.
1. Remove request parameter from `RequestHandler` and shift it to the url isntead. 
2. Ports over existing controller unit tests and changes it so that the parameter is in the url 
3. Ports over existing integration tests and changes it so that the parameter is in the url
1. Create a new storage mode form and make it public. Go to the form and submit a few responses. Go to the admin panel and click on data and click on any response. The panel should be populated with the information of the responses
1. Shifted from …

refactor: migrate GET /submission to new endpt

---

src/app/modules/verification/__tests__/verification.service.spec.ts
tests/unit/backend/helpers/jest-db.ts

For a long time, we had been getting a warning from Jest after our tests:
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
```
This was due to our `MongoMemoryServer` instance continuing to run after every test. There was also a missed call to the `dbHandler.closeDatabase` function in one of the test suites.
This has also been more of a problem of late, with many tests failing in TravisCI due to running out of memory, or failing to start a new database instance.
This PR fixes (hopefully?) the memory leak by closing `MongoMemoryServer` when `dbHandler.closeDatabase` is called.
**Bug Fixes**:
- Fix `jest` memory leak.
**BEFORE**:
Leak warning in …

fix: jest memory leak

---

src/app/utils/field-validation/validators/__tests__/home-num-validation.spec.ts
src/shared/util/phone-num-validation.ts

Fixes the problem of sg home numbers starting with '666' being incorrectly rejected.

fix: loosen validation for sg home numbers

---

src/app/modules/form/admin-form/admin-form.routes.ts
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.controller.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.submissions.routes.spec.ts
src/app/routes/api/v3/admin/forms/admin-forms.submissions.routes.ts
src/public/modules/forms/services/submissions.client.factory.js

This is part 2 of #1520. 
This PR migrates the old API to the new API rooted at `/api/v3/admin/forms`. The current implementation is ported over as is and something to note is that currently, we are not validating that there is either submission or formId, and that formId should be at least 1. 
This will be rectified in a future PR to avoid scope creep here and this PR should be reviewed as an almost direct port over. 
Closes #1520 
1. Adds new endpoint to `AdminFormSubmissions` router for metadata and changed client callsites
2. Ported over integration tests
- Verify that clicking on any page returns a list of responses  
- Verify that searching on any single response id returns exactly that response   
- Verify that searching on any substring of a response id returns nothing

refactor: migrate submissions metadata

---

src/app/models/form.server.model.ts
src/app/modules/auth/auth.service.ts
src/app/modules/form/__tests__/form.service.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/form.service.ts
src/app/routes/api/v3/admin/forms/admin-forms.settings.routes.ts
src/types/form.ts

the retrieval counterpart to #1383 is missing
Fixes #1496 
[form]
- augment `FormSchema.getFullFormById()`,
which will partially populate an IPopulatedForm with specified keys,
if given
- feed the `fields` argument supplied in the abovementioned fn as
the projection arg of `Schema.findById()`
- implement `FormSchema.pick()`, allowing one to pick only the fields
we want out of a given IFormSchema
[auth-service]
- implement `getFormFieldsAfterPermissionChecks()`, exploiting
type-generic parameters to allow callers to specify the shape
of the return value
- take care to only return fields specified by the caller
[admin-form]
- declare and implement `handleGetSettings()` in controller and route,
taking inspiration from `handleUpdateSettings()`
- import `FORM_SETTING_FIELDS` from …

feat(admin-forms): implement retrieval of form settings

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/public/modules/forms/admin/constants/update-form-types.ts
src/public/modules/forms/admin/controllers/admin-form.client.controller.js
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/controllers/edit-myinfo-field-modal.client.controller.js
src/public/services/AdminFormService.ts
src/types/api/form.ts
src/types/form.ts

Integration tests will be added to a separate PR to prevent PR size from becoming too big
This PR cannot be rolled back after release due to the invocation of the new endpoint on the client side.
This PR adds a specific endpoint to create a single form field, and updates the frontend client to use that endpoint when creating fields.
Closes #1484
**Features**:
- feat(AdminFormCtl): add handleCreateFormField controller and router fn
- feat(FormModel): add insertFormField model instance method
- Unable to use model static function due to usage of `this.getParent()` method in some field validators which is not available when using MongoDB's `update` methods.
- NOTE: This is a change from using the globalId to do field comparisons, and we are doing comparisons with _id instead.
- feat(client): …

feat(api-refactor): implement specific create field api

---

src/app/models/__tests__/submission.server.model.spec.ts
src/app/models/submission.server.model.ts
src/app/modules/webhook/__tests__/webhook.service.spec.ts
src/app/modules/webhook/webhook.service.ts
src/app/modules/webhook/webhook.utils.ts
src/types/submission.ts

The webhook response data stored in the database has a couple of superfluous fields:
1. `errorMessage` is useless because it is always a standard `axios` error message, e.g. "Request failed with status code 400".
2. `statusText` is useless because it is just the standard HTTP status text, e.g. `'OK'` for 200
Furthermore, fields that should always be present (webhook URL, signature, status code) are not marked as required in the database schema.
Remove the superfluous fields and mark the rest as `required` where appropriate. `headers` and `data` were not made required as they may be empty strings.

feat(webhooks): streamline webhook response data

---

src/app/modules/submission/email-submission/email-submission.util.ts

In the submission emails sent to form admins, verified fields have the [verified] prefix. However, this prefix is also present for optional verified fields that were left blank.
Closes #844
Include an extra check to ensure that the field is not blank before adding the [verified] prefix.
**BEFORE**:
**AFTER**:

fix: remove verified prefix on blank verified fields

---

src/app/modules/form/admin-form/__tests__/admin-form.utils.spec.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/form/admin-form/admin-form.utils.ts
src/app/utils/field-validation/field-validation.guards.ts
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/directives/is-verifiable-save-interceptor.directive.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html

> This is the first PR of our journey to remove `emailField.hasAllowedEmailDomains` from the schema. 
Currently, it is somehow possible (and we have some states in the database where this is so) to have the following email field states:
|`hasAllowedEmailDomains`|`allowedEmailDomains`| Remarks|
|---|---|---|
|`true`| `[]`| Not ideal, since the source of truth is muddled, but no real harm since there are sanity checks in the code where isVerifiable && hasAllowedEmailDomains && allowedEmailDomains.length must all be true before restricting domains|
| `false` | `["@someDomain.com", "@anotherDomain.com"]` | Was supposed to be a feature such that admins will be able to toggle restriction on/off and have their previously entered domains. Scrapping this state for cleanliness|
| `true`| …

fix: sync email field state between hasAllowedEmailDomains and allowedEmailDomains

---

src/app/routes/api/v3/admin/forms/admin-forms.routes.ts

Currently, there is a redundant `DELETE /admin/forms/:formId/logic/:logicId` endpoint defined in the `admin-forms-routes` file. This endpoint already exists in `admin-forms.logic.routes`.
- Remove redundant endpoint

chore(admin-forms-routes): remove duplicate logic route endpoint

---

src/app/modules/myinfo/__tests__/myinfo.routes.spec.ts
src/app/modules/spcp/__tests__/spcp.routes.spec.ts
src/app/modules/spcp/__tests__/spcp.service.spec.ts
src/app/modules/spcp/__tests__/spcp.test.constants.ts
src/app/modules/spcp/spcp.service.ts

Singpass e-service ID validation relies on parsing the HTML of the login page. The login page recently added a semicolon in the line showing the error code, resulting in the FormSG server returning `null` for the error code. This causes the frontend to show an error message saying "Could not connect SingPass to validate the e-service ID", instead of showing that the e-service ID is invalid.
Add the semicolon to the parsing code, and also make the comparison case-insensitive.

fix: show correct error message for e-service ID validation

---

src/app/config/feature-manager/spcp-myinfo.config.ts

Past feedback that 1h was too short for some long forms
Closes #1674 
Modify the config's default for SP session age to 3 hours, up from the original 1 hour. Corp pass already has their session age to be 6 hours, so no change required on that front.

feat(spcp): raise sp cookie max age to 3 hrs

---

src/public/modules/core/services/gtag.client.service.js
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/services/captcha.client.service.js

This PR adds a Google Analytics logging invocation on any recaptcha instantiation failure
Closes #1306 
- feat: log client form reCAPTCHA failure to GA
**GA Logging screenshot**

feat(client): log client form reCAPTCHA failure to GA

---

src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html

An enum called `DateSelectedValidation` was introduced during a typescript migration task #749, but the frontend codebase has not been updated to make use of this enum.
Closes #777 
Remove the naming conflict between `DateValidationOptions` and `DATE_VALIDATION_OPTIONS`. The former is actually a list of options and the latter is the enum. The former is now called DateValidationOptionList.
Edit usages of the enum from lower-case to title-case to match the new enum. i.e. `DateValidationOptions.custom` to `DateValidationOptions.Custom`
@tshuli appreciate if you could take a quick look to see if these changes are indeed what you had intended.

refactor: use shared DateSelectedValidation enum instead of DATE_VALIDATION_OPTIONS

---

src/public/modules/forms/admin/controllers/admin-form.client.controller.js

1. When user attempts to save more MyInfo fields than is allowed, a generic error message shows in the Toastr, rather than the specific one returned by the backend.
2. On the build tab, MyInfo field count does not update upon creation of MyInfo field.
The initial error message was:
This was fixed by accessing `error.response.status` rather than `error.status`, since `error` is now an `AxiosError`.
The error message then changed to this:
This was because we return a 422 when an error occurs while editing fields, and the `switch` case handles 422s by attempting to access `error.data.message`. This was fixed by accessing `error.response.data.message` instead.
This finally fixed the error message:
This was fixed by assigning to `$scope.myform.form_fields` instead of pushing to the array, …

fix: update MyInfo field count correctly, show correct error

---

src/public/modules/core/css/core.css
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/css/edit-form.css
src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/public/modules/forms/base/componentViews/field-textfield.client.view.html
src/public/modules/forms/base/css/form-field.css
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/base/directives/submit-form.directive.js

Closes #1593
Forms guide PR [here](https://github.com/opendocsg/opendoc-formsg-faq/pull/78) 
- Add prefill toggle for short text field and highlight prefills for public user
- Note that fieldId is generated only upon field create
**Admin page - Create Field**
**Admin Page - Edit Field**
**Public Form View**

feat: prefill mainstream launch

---

src/public/modules/forms/admin/controllers/admin-form.client.controller.js
src/public/modules/forms/admin/controllers/edit-myinfo-field-modal.client.controller.js

This PR fixes a bug (not in prod as of this PR) where calling the new form field manipulation APIs created in #1640, #1671, #1726 was
1. Not stripping MyInfo field data before saving it into the database. 
2.  Not converting returned form field JSON objects into their class based implementation.
The PRs above replaced the previous method of updating form fields in `FormApi#update`, where there was an interceptor function to
1. modifying outgoing requests by removing MyInfo field data, and 
2. transforming incoming form responses into an Form class with specific Field classes for the form fields.
However, with the update form field refactors, the interceptor is not invoked (and return shapes are different); thus causing the form field object responses to not be transformed into their Field …

fix: convert form field responses to field class 

---

src/public/modules/forms/admin/controllers/edit-myinfo-field-modal.client.controller.js

This PR fixes a UI bug where the inject MyInfo field values disappears for a split second before modal closes, or disappears fully on field save error. See gif.

fix(client): clone field to save before removing myinfo field info

---

.github/mergify.yml

The [Mergify documentation](https://docs.mergify.io/conditions/#validating-all-status-checks) states that `#check-failure=0` should not be used as a condition because of a possible race condition where the PR might be merged before any service reports its status check.
Credit to @lamkeewei for pointing this out.
Remove the `#check-failure=0` condition. We can rely on branch protections to ensure that all status checks pass before PRs can be merged (which is what we were implicitly doing in the first place).

chore(mergify): remove 0 check failure condition

---

src/app/views/templates/bounce-notification-permanent.server.view.html
src/app/views/templates/bounce-notification-transient.server.view.html
src/public/modules/forms/admin/controllers/activate-form-modal.client.controller.js
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/public/sitemap.xml
src/public/translations/en-SG/main.json

feat: update form guide links to go links

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/public/modules/forms/admin/constants/update-form-types.ts
src/public/modules/forms/admin/controllers/admin-form.client.controller.js
src/public/modules/forms/admin/directives/edit-form.client.directive.js
src/public/services/AdminFormService.ts
src/types/form.ts

Integration tests will be added to a separate PR to prevent PR size from becoming too big
This PR cannot be rolled back after release due to the invocation of the new endpoint on the client side.
This PR adds a new admin-form server endpoint for form fields deletion, and updates the frontend client to use that endpoint when deleting fields.
Closes #1485
**Server Features**:
- feat(FormModel): add deleteFormFieldById static method
- feat(AdminFormSvc): add deleteFormField service fn
- feat(AdminFormCtl): add handleDeleteFormField controller handler fn
- feat(AdminFormsRoutes): add route for deleting form field
**Client Features**
- feat(AdminFormService): add deleteSingleFormField fn
- feat: use new server endpoint for deleting of fields
**To be added**

feat(api-refactor): implement specific delete form field api

---

src/app/routes/api/v3/forms/__tests__/public-forms.auth.routes.spec.ts

This PR is a follow up to the previous one (#1725 )  and this PR solely adds integration tests
**notes**:
1. testing for `/validate` when `createRedirectURL` is not done at the moment. By right, we should mock the external library but due to how `SpcpAuthClient` is implemented, this is extremely tedious to do. Advice for how to test this is welcome ;--;

test(integration): integration tests for /validate endpoint

---

src/app/routes/api/v3/admin/forms/__tests__/admin-forms.settings.routes.spec.ts

This is a follow-up to #1762, which does not have integration tests 
This PR adds integration tests for increased reliability.

test(adminform): integration tests for GET /admin/forms/:formId/collaborators

---

src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts

We allow admins to specify the email sender for email confirmations. However, when the sender contains a comma, the text before the comma gets cut off.
**Specifying an email sender with a comma**
**Actual email sender**
According to [this issue](https://github.com/nodemailer/nodemailer/issues/377), sender names containing commas must be wrapped in quotes. This fixed the problem.
**Specifying an email sender with a comma**
**Actual email sender**
Note that for senders without special characters, the email headers actually remain unchanged, so this change is backwards compatible even for receivers which are manually parsing email headers. For senders with special characters, the email headers get fixed by the inclusion of quotes.
**Without comma, before (production)**
**Without comma, after …

fix: allow commas in email confirmation sender

---

src/public/modules/forms/admin/components/edit-logic.client.component.js

- The digest cycle wasn't triggered to update the build tab after logic is deleted in #1586. This is because in the previous implementation, the form_logic object is replaced on delete logic, while with the refactor, only the form_logic array is spliced.
- This means that after deleting a logic, user will need to refresh before the build tab will be updated
- Trigger digest cycle on delete logic

fix: trigger digest cycle for delete logic

---

src/public/modules/forms/admin/controllers/admin-form.client.controller.js
src/public/modules/forms/admin/controllers/edit-end-page-modal.client.controller.js
src/public/modules/forms/admin/directives/edit-form.client.directive.js
src/public/modules/forms/admin/views/edit-end-page.client.modal.html
src/public/modules/forms/base/directives/validate-url.client.directive.js
src/public/modules/forms/config/forms.client.routes.js
src/public/services/AdminFormService.ts
src/shared/util/url-validation.ts

Note that this PR is building on #1760
This PR **cannot be rolled back** due to new endpoints being called on the client.
This is the second PR to use the new endpoint in the frontend. Also added URL validation to the client due to the new endpoint having stricter Joi validation on whether the button link is a valid URL or not.
Also also remove unused functions in the controller left behind when `endPage.buttons` was removed from the schema a long time ago.
See #1487
**Features**:
- feat(client): add updateFormEndPage to call API
- feat(client): add scoped function to call update end-page API
- feat(client/validate-url): add non-https mode validation
- feat(client): add url validation to end page button link
- feat(client/edit-end-page-modal): remove unused functions …

feat(client): use update endpage api in client, add button link url validation

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/public/modules/forms/admin/controllers/admin-form.client.controller.js
src/public/modules/forms/admin/controllers/edit-end-page-modal.client.controller.js
src/public/modules/forms/admin/directives/edit-form.client.directive.js
src/public/modules/forms/admin/views/edit-end-page.client.modal.html
src/public/modules/forms/base/directives/validate-url.client.directive.js
src/public/modules/forms/config/forms.client.routes.js
src/public/services/AdminFormService.ts
src/shared/util/url-validation.ts
src/types/api/form.ts
src/types/form.ts

This PR adds a specific endpoint `PUT /api/v3/admin/forms/:formId/end-page` for updating of the form's end page subslice.
The client changes will continue in a separate PR for ease of review.
Note that this new endpoint has stricter Joi validation than before: 
```ts
celebrate({
[Segments.BODY]: {
title: Joi.string(),
paragraph: Joi.string().allow(''),
buttonLink: Joi.string().uri().allow(''), // model validation did not test for `uri`-ness
buttonText: Joi.string().allow(''),
},
})
```
Previously, there was no route level validation, and instead relying on model level validation, which did not test whether a buttonLink was an URI.
Closes #1487
**Features**:
- feat(FormModel): add updateEndPageById form static method
- feat(AdminFormSvc): add updateEndPage fn
- feat(AdminFormCtl): add …

feat(api-refactor): add specific update end page endpoint in server

---

src/public/modules/core/componentViews/sg-govt-banner.html
src/public/modules/core/components/sg-govt-banner.client.component.js
src/public/modules/core/css/sg-govt-banner.css
src/public/modules/forms/base/componentViews/start-page.html
src/public/modules/forms/base/views/submit-form.client.view.html

Closes #969 
**BEFORE**:
**AFTER**:
**With info banner**
**Without**
The indentation of the text `A Singapore Government Agency Website` looks strange on form pages.

feat: add <sg-govt-banner-component> to top of public forms

---

.gitignore

IntelliJ IDEs generate a .idea directory for metadata.
Would like to add the entry to gitignore so I won't accidentally commit these metadata files.

chore: gitignore intellij metadata directory

---

src/public/modules/forms/admin/directiveViews/edit-form.client.view.html

Removes the broken link, since there is no section on the MyInfo field limit in the guide.
Closes #1801

fix: remove Learn More link for MyInfo field limit

---

src/app/modules/submission/email-submission/email-submission.controller.ts

Currently, the first two stages of the submission pipeline have their errors logged jointly.
This could be confusing if we have to debug error messages. It is also inconsistent from the rest of the pipeline.
Introduce a `mapErr` after the fetching of the form which logs the database errors, and add another `mapErr` during the state checking step with its own error message.
Would appreciate KR's help in checking if i'm using `neverthrow` properly in this case.

feat(email-submission): separate error logging for db and state checks

---

.husky/pre-commit
package.json

We have been installing a fresh version of lint-staged every precommit due to the script in `husky/pre-commit`. This caused every commit to take ~1 second at least and we pretty bad dev-exp.
This PR instead runs an npm script to use the installed lint-staged module, thus greatly(?) speeding up the pre-commit hook.

fix: speed up precommit hooks

---

src/app/models/form.server.model.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/types/form_logic.ts

- This PR builds off #1695 and replaces the typings for joi validation for logic endpoint to align to the schema
- Also closes #1810

fix: align joi validation types to schema

---

.github/workflows/ci.yml
.travis.yml

Unit tests on Travis CI have been intermittently failing due to memory issues with Jest. It does not seem like the issue is with the tests themselves, since running `jest --logHeapUsage` shows that the memory usage does not increase consistently as more tests pass. This suggests that the memory limitation is with Travis.
Part of #1864 
This PR migrates only the frontend and backend unit tests to GitHub Actions (GA) to test whether the tests pass consistently. If they do, we can consider migrating the entire CI pipeline to GA.

build: migrate unit tests to GitHub Actions

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/form/form.utils.ts
src/app/routes/api/v3/admin/forms/admin-forms.logic.routes.ts
src/public/modules/forms/admin/components/edit-logic.client.component.js
src/public/modules/forms/admin/controllers/edit-logic-modal.client.controller.js
src/public/modules/forms/admin/directives/edit-form.client.directive.js
src/public/services/AdminFormService.ts
src/types/form.ts

- Closes #1489
- Also refactors edit logic client controller to use $watchCollection to track changes in form_logic
**Create Logic Endpoint**
Test using manual API calls
**$watchCollection Refactor**

refactor: extract create logic endpoint / refactor $watchCollection

---

src/app/modules/form/admin-form/admin-form.controller.ts
src/public/modules/forms/admin/controllers/edit-start-page-modal.client.controller.js
src/public/modules/forms/admin/views/edit-start-page.client.modal.html

See #1885 for a description of the problem
Closes #1885 
Added extra functionality to `vm.updateLogoUrl` to remove extra parameters on each button click because each button calls that upon change.

fix(start-page): remove extra logo props when logo type is not custom

---

.github/pull_request_template.md

Devs are supposed to indicate breaking changes for easier rollback if hiccups occur on the release day. This makes it prone to human error, where the devs forget. 
adds a breaking change section to the PR template

chore(pull_request_template): adds breaking changes section to github template

---

src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/routes/api/v3/forms/__tests__/public-forms.verification.routes.spec.ts
src/app/routes/api/v3/forms/public-forms.verification.routes.ts
src/public/modules/forms/base/componentViews/field-email.client.view.html
src/public/modules/forms/base/componentViews/field-mobile.client.view.html
src/public/modules/forms/base/components/field-email.client.component.js
src/public/modules/forms/base/components/field-mobile.client.component.js
src/public/modules/forms/base/components/verifiable-field.client.component.js
src/public/modules/forms/base/directiveViews/field.client.directive.view.html
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/base/directives/field.client.directive.js
src/public/services/FieldVerificationService.ts
src/public/services/__tests__/FieldVerificationService.test.ts

Restructures the endpoints so that the our endpoints follow a RESTful hierarchy because the verification state is part of fields, which is in turn part of the form. 
Part of #1522 
tested on staging

refactor(verification): reset field verification state when field changes

---

src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/app/services/mail/mail.types.ts
src/app/views/templates/submit-form-autoreply.server.view.html
src/public/modules/forms/admin/css/edit-form.css
src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/public/modules/forms/base/componentViews/end-page.html
src/public/modules/forms/base/components/end-page.client.component.js
src/public/modules/forms/base/css/end-page.css
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/base/directives/submit-form.directive.js
src/public/modules/forms/services/submissions.client.factory.js

This PR adds the response ID to the Thank You page. For details, see #1409.
Closes #1409
- **Create email field in email mode and submit form**
- **Create email field in storage mode and submit form**

feat: add response ID to thank you page

---

package-lock.json
package.json
src/app/modules/myinfo/myinfo.format.ts

Upgrades `@opengovsg/myinfo-gov-client` to the latest version, and makes the necessary update to accommodate the breaking changes.
The latest version includes a breaking change which makes nested scope data optional (see [PR](https://github.com/opengovsg/myinfo-gov-client/pull/30)). This is because there is no way of knowing whether a given `MyInfoPerson` data object contains the given nested scopes without knowing which scopes were requested in advance.
In FormSG's case, `vehicles.vehicleno` is the only nested scope we deal with, and this property is only accessed if the `vehicleno` field is requested, so the property access is safe. Hence the additional `?` optional chain was added purely to accommodate the new types from `myinfo-gov-client`.

feat: upgrade myinfo-gov-client to 4.0.0

---

docker-compose.yml

Dev environment logs mostly comprise large chunks of database container logs which are never useful. This mutes the logs from the database container so developers can focus on the important parts of the logs.

build: mute database container logs

---

src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts

The guard to prevent submisison of non-storage mode forms in storage mode submission endpoint is located very low in the pipeline, when it should have been one of the first checks made.
Reordering this above will also help reflect the typing of the `form` object accurately, earlier in the pipeline.
Copy paste, with changes in wording of the log messaging

fix(encrypt-submission): shift encrypt mode form guard higher up the pipeline

---

frontend/.eslintrc
frontend/.storybook/main.js
frontend/__tests__/storyshots/axe-tests.runner.ts
frontend/__tests__/storyshots/config/setup-storyshots.ts
frontend/__tests__/storyshots/jest.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/test-utils.tsx
frontend/tsconfig.json

We can currently see a11y compliance via [Storybook's a11y addon](https://storybook.js.org/addons/@storybook/addon-a11y), but the addon itself  will not throw any errors even if there are a11y violations. When multiple developers are working on several components, it is easy to overlook those a11y warnings (or even ignore them).
Thus, this PR adds an a11y check to the frontend tests pipeline to ensure that our rendered components are somewhat accessible, using `@storybook/addon-storyshots-puppeteer` which uses [axe](https://www.deque.com/axe/) under the hood to catch the most common a11y violations.
Also clean up Storybook versions to use the stable version and clean up s ome storybook configuration.
(Also also to experiment with this for the a11y talk I'm about to start writing) …

chore: add a11y checks to test pipeline

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts

**!! Will probably need a DB migration script to populate old forms (that did not update their start pages) with a default form logo state**
Creating a new form does not create a default startPage.logo nested document, resulting in a new form not having a default form logo state.
This PR populates `startPage.logo` with its default state.
- Details ...
- If rolled back... just means new documents don't have a default state
- fix: set default form logo schema on form document creation
- tests have been updated

fix: set form logo default value when creating form document

---

src/app/modules/verification/verification.util.ts
src/shared/util/verification.ts

Closes #1923, see issue for detailed explanation of problem
Add a tolerance of 2 seconds to the OTP waiting time check. This means the server allows OTPs to be requested every 28 seconds.
- Details ...
No tests to be updated. Current service tests check that the OTP requests are rejected if made within 25 seconds of each other, which is still true _(pats self on the back)._

fix(verification): loosen OTP waiting time by 2 seconds

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.settings.routes.spec.ts
src/app/routes/api/v3/admin/forms/admin-forms.settings.routes.ts
src/types/api/form.ts
src/types/form.ts

Second in a series of PRs to enable webhook retries. This PR adds a `webhook.isRetryEnabled` key to the `Form` model, which determines whether retries are enabled for a form. It also makes the necessary changes to ensure that this key can be updated as part of the current form settings update APIs.

feat(webhook-retries): add isRetryEnabled to model (2)

---

src/public/modules/forms/admin/directiveViews/settings-form.client.view.html

This PR changes the placeholder text for entering e-service IDs. 
Closes #1675

feat: display different e-service placeholder text for singpass and corpass

---

src/app/utils/handle-mongo-error.ts

MongoDB validation error messages may be duplicated in specific cases. This deduplicates those error messages.
Closes #1694 
Adds a simple de-duplication to the error messages.

feat: Deduplicate Mongodb Error Messages

---

.github/workflows/ci.yml
.travis.yml
Dockerfile.development
Dockerfile.production
README.md
docs/TROUBLESHOOTING.md
package.json
src/app/modules/submission/encrypt-submission/__tests__/encrypt-submission.service.spec.ts

The current base node Docker image used in our application has a possible security vulnerability as flagged by Snyk ([Improper certificate validation](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15604)), which can cause the Node process to terminate. This can result in denial of service.
This PR upgrades the Docker image to `node:fermium-alpine3.13`, which upgrades our node version used to v14. The image does not seem to have any known vulnerabilities [flagged](https://snyk.io/test/docker/node%3Afermium-alpine3.13).
Tested on staging.
Closes #2027 
- Upgrade base docker image to node:fermium-alpine3.13.

build: upgrade application node version to v14 (by updating Docker image)

---

package-lock.json
package.json
src/app/config/feature-manager/types.ts
src/app/config/feature-manager/webhook-verified-content.config.ts
src/app/constants/timezone.ts
src/app/models/submission.server.model.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/app/modules/submission/submission.errors.ts
src/app/modules/webhook/__tests__/webhook.service.spec.ts
src/app/modules/webhook/webhook.constants.ts
src/app/modules/webhook/webhook.consumer.ts
src/app/modules/webhook/webhook.errors.ts
src/app/modules/webhook/webhook.factory.ts
src/app/modules/webhook/webhook.message.ts
src/app/modules/webhook/webhook.producer.ts
src/app/modules/webhook/webhook.service.ts
src/app/modules/webhook/webhook.types.ts
src/app/modules/webhook/webhook.utils.ts
src/app/utils/random-uniform.ts
src/types/submission.ts

Third in a series of PRs to enable webhook retries. This PR contains the bulk of the application logic for the production and consumption of messages from the queue.
Can be reviewed by commit.

feat(webhook-retries): produce and consume retries (3)

---

src/app/models/__tests__/submission.server.model.spec.ts

Adds unit tests for the Submission model modifications introduced in #1940.

test(webhook-retries): add unit tests for retrieveWebhookInfoById (5)

---

src/app/modules/webhook/__tests__/webhook.service.spec.ts

- Cleans up the existing webhook service tests by removing reliance on the model layer
- Adds tests for the new `createInitialWebhookSender` function

test(webhook-retries): add unit tests for webhook service (6)

---

src/app/modules/webhook/__tests__/webhook.consumer.spec.ts
src/app/modules/webhook/__tests__/webhook.message.spec.ts
src/app/modules/webhook/__tests__/webhook.producer.spec.ts
src/app/modules/webhook/__tests__/webhook.utils.spec.ts
src/app/modules/webhook/webhook.consumer.ts
src/app/modules/webhook/webhook.producer.ts

Adds unit tests for the following:
- `WebhookQueueMessage` class
- Handler for webhook consumer
- `WebhookProducer` class
- Important utils for calculating time of next retry attempt and queue delay

test(webhook-retries): add unit tests for message, producer, consumer (7)

---

src/app/models/field/emailField.ts

Refer to issue #1222 for details. This PR only replaces the set hook in `emailField`'s `includeFormSummary`. Two set hooks remain in `form.server.model.ts`. Conversion of these hooks is slightly more complicated due to the use of functions such as `findByIdAndUpdate`, `findOneAndUpdate` amongst others, which write directly to the database. The validator is therefore not able to access the object to perform the needed validation.
Ensure existing unit tests still pass.

refactor: replace set hook with validator hook in emailField model

---

README.md

Remove active contributors from the relevant section in the README, 
since their contributions are now present in the commit log

docs(readme): remove active contributors

---

src/app/models/form_feedback.server.model.ts
src/app/models/submission.server.model.ts
src/types/submission.ts

Some typings were accidentally removed in #2046 when replacing some static methods' declaration from assigning a function to inlining their methods. This PR fixes that.
**Bug Fixes**:
- fix: restore typings to some model static methods

fix: restore typings to some model static methods

---

src/public/modules/forms/admin/css/settings-form.css
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/translations/en-SG/main.json

Last in a series of PRs to enable webhook retries. This PR adds a toggle on the frontend to enable or disable retries.

feat(webhook-retries): enable toggling retries on frontend (4)

---

src/app/modules/form/admin-form/admin-form.controller.ts
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/forms/admin/directives/view-feedback.client.directive.js
src/public/modules/forms/services/submissions.client.factory.js
src/public/services/AdminFormService.ts
src/public/services/AdminSubmissionsService.ts
src/public/services/__tests__/AdminFormService.test.ts
src/public/services/__tests__/AdminSubmissionsService.test.ts
src/types/api/submission.ts

`submissions.client.factory` client-side service that determines the performance and safety of many key features, but has two separate areas of concern - the public form facing submissions and the admin form retrieval of submissions. 
Part 1 of #1874 
This extracts out all the straight forward client submission methods to `AdminFormService`, and replaces old method calls with the new one.
The download related methods will be in a separate PR for closer scrutiny!
- Details ...
This adds unit tests for all new methods added.
This has been already tested on staging
Create a storage mode form with any field and activate it. Submit the form >= 11 times. Go to the data section and unlock responses.

refactor(submissions.client.factory): extract admin form features

---

package-lock.json
package.json

Downgrades TypeScript to version 4.2 due to incompatibility of [zod](https://www.npmjs.com/package/zod) with version 4.3+, which is blocking several open PRs. TypeScript can be upgraded once this issue is resolved.
See: colinhacks/zod#473, microsoft/TypeScript#44299

fix(deps): downgrade typescript to 4.2.4

---

package-lock.json
package.json

#2092 did not pin the TypeScript version, resulting in dependabot automatically upgrading it again. Oops.

fix(deps): downgrade typescript to 4.2.4 and pin

---

src/public/modules/forms/helpers/CsvMergedHeadersGenerator.js

Currently, when a CSV of responses are downloaded (in storage mode), the responses are not sorted according to date. Refer to issue #1721
Closes #1721
The naive approach was adopted to solve this problem. Specifically `Array.prototype.sort()` was used to sort the responses. This solution seems satisfactory even for a large number of responses. When tested with 100,000 responses, the sorting duration ranged from 1 to 2 seconds. With approximately 500,000 responses, the sorting duration ranged from 9 to 10 seconds, which is not significant compared to the decryption duration of approximately 3 minutes. Throughout the download, the following modal is displayed and no obvious freezes or slowdowns in the spinner were observed. The short clip below shows the condition of the spinner before and …

feat: sort responses for csv download according to creation date

---

scripts/20210706_remove-endpage-buttons/delete-endpage-buttons.js
src/public/modules/forms/admin/constants/covid19.js

This PR contains a db script to remove the deprecated `endPage.buttons` key in forms. `buttons` are also removed from the covid templates.
Closes #1895

chore: remove endPage.buttons key from database 

---

src/app/modules/auth/auth.middlewares.ts
src/app/routes/api/v3/admin/forms/admin-forms.routes.ts

feat: log form updates

---

src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/services/AdminSubmissionsService.ts
src/public/services/__tests__/AdminSubmissionsService.test.ts

renamed metadata related methods to be for submissions because they are related to submissions and not form

chore(adminsubmissionsservice): renamed metadata methods

---

src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/services/submissions.client.factory.js

**Discovered on staging, has not hit production yet**
Wrong param shape was being passed into `AdminSubmissionsService.countFormSubmissions` introduced in #1983, resulting in a failure to retrieve the number of documents in a date range. This prevented the downloading of submissions when a date range is given if the number of responses to download does not equal number of total responses.
This PR fixes the bug.

fix: use correct argument key when counting form submissions

---

src/app/models/__tests__/encrypt-submission.server.model.spec.ts
src/app/models/submission.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.routes.spec.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.utils.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.submissions.routes.spec.ts
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/helpers/decryption.worker.js
src/types/submission.ts

Currently, the encrypted submission object returned does not return the version number, whilst `formsg-javascript-sdk#decrypt` requires the version number in the param (but not used since we only have 1 version so far).
**This bug does not affect prod**, since the `version` parameter is actually unused by the SDK. This is to prevent future updates from breaking and to correctly return expected required parameters when retrieving storage mode responses.
This PR returns the version number when retrieving submission (meta)data regardless so that the decrypt call doesn't need a mock version number parameter.
Closes #2029
**Bug Fixes**:
- add version key when retrieving storage mode submission data
- pass version on client when decrypting storage mode responses
Tests have …

fix: return storage mode submission version when when retrieving from server

---

src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/auth.controller.ts
src/app/modules/auth/auth.utils.ts
src/app/modules/billing/billing.controller.ts
src/types/vendor/express.d.ts

feat: store only user ID in session

---

src/public/modules/users/controllers/authentication.client.controller.js
src/public/modules/users/services/auth.client.service.js
src/public/modules/users/views/authentication/signin.client.view.html
src/public/services/AdminAuthService.ts
src/public/services/AuthService.ts
src/public/services/__tests__/AuthService.test.ts

This PR is part 1 of migrating auth.client.js to Typescript. This PR extracts out the first two functions
- `checkIsEmailAllowed` for verifying whether email domain is whitelisted, and
- `sendLoginOtp` for sending the login OTP
Related to #2057
**Features**:
- add `AuthService` file containing the first two service functions for admin login flow
- replace old `auth.client.service.js` function calls with new `AuthService` functions.
Unit tests have been added for the new `AuthService` functions.
(Verification of OTP not tested because not in this PR)

refactor(auth.client): (1) extract email validation and send login otp flow to Typescript

---

src/app/modules/auth/auth.middlewares.ts
src/app/routes/api/v3/admin/forms/admin-forms.routes.ts

Removes the temporary fix introduced in #2047 to block form updates from admins who had been erroneously onboarded.

chore: remove blocking of SP and RP admin updates

---

src/app/routes/api/v3/admin/forms/__tests__/admin-forms.form.routes.spec.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/public/services/AdminViewFormService.ts
src/public/services/__tests__/AdminViewFormService.test.ts

Seems to have been missed out when duplicating the current APIs into their `/api/v3` counterparts. This PR adds the new endpoint, calls the new endpoint, and adds missing tests for the endpoint.
- Client calls new endpoint
**Features**:
- feat: add v3 API for retrieving admin form by id
- feat(AdminViewFormService): call v3 API to retrieve admin form
New integration tests have been added for the new endpoint.

feat: add and call v3 API for retrieving individual admin form

---

tests/end-to-end/helpers/util.js

End-to-end tests are intermittently failing due to the following:
```
AssertionError: expected
'http://localhost:5000/60c068423668141b03289c84#!/' to deeply equal
'http://localhost:5000/#!/60c068423668141b03289c84'
+ expected - actual
-http://localhost:5000/60c068423668141b03289c84#!/
+http://localhost:5000/#!/60c068423668141b03289c84
```
This is probably because the test checks the URL in the browser before the browser redirects to the form.
Loosen the URL check so it checks for the presence of the form ID in the URL instead of an exact string. If the redirect does not occur correctly then the subsequent assertions will fail anyway.

test: loosen URL check in e2e test

---

src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.routes.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.settings.routes.spec.ts
src/app/routes/api/v3/auth/__tests__/auth.routes.spec.ts
src/app/routes/api/v3/auth/auth.routes.ts
tests/integration/helpers/express-auth.ts

#2084 introduced a bug where non-lowercase emails could not be used to log in to the admin dashboard.
The frontend used to mutate `vm.credentials.email` to lowercase at the point of sending the OTP, then use the lowercased string when subsequently verifying the OTP. This is important because the email domains in the Agencies collection are all in lowercase, so only lowercase email domains are considered to be valid. However, #2084 removed this mutation, resulting in OTP verification breaking for non-lowercase emails.
This exposes a source of bugs in the authorisation flow, namely that the backend implicitly relies on the frontend to send email strings in the correct case.
For all authorisation endpoints, lowercase email addresses at the edge of the application using Joi validation. This …

fix(auth): make login emails case-insensitive

---

src/public/modules/core/components/avatar-dropdown.client.component.js
src/public/modules/users/services/auth.client.service.js
src/public/services/UserService.ts
src/public/services/__tests__/UserService.test.ts

Chain: [`sendOtp`](https://github.com/opengovsg/FormSG/pull/2084) <--- [`verifyOtp`](https://github.com/opengovsg/FormSG/pull/2086) <-- `fetchUser` (you are here)
This PR is part 3 of migrating auth.client.js to Typescript. This PR extracts out the fetch user function
Related to #2057
**Features**:
- feat(UserService): add fetchUser function
- use new fetchUser function
- remove old unused refreshUser function
Unit tests have been written for `UserService.fetchUser`

refactor(auth.client): (3) extract fetch user service function to Typescript

---

src/public/modules/core/componentViews/avatar-dropdown.html
src/public/modules/core/components/avatar-dropdown.client.component.js
src/public/modules/users/services/auth.client.service.js
src/public/services/AuthService.ts
src/public/services/UserService.ts
src/public/services/__tests__/AuthService.test.ts

Chain: [`sendOtp`](https://github.com/opengovsg/FormSG/pull/2084) <--- [`verifyOtp`](https://github.com/opengovsg/FormSG/pull/2086) <-- [`fetchUser`](https://github.com/opengovsg/FormSG/pull/2089) <- `logout` (you are here)
This PR is part 4 of migrating auth.client.js to Typescript. This PR extracts out the logout admin function
Related to #2057
**Features**:
- feat(AuthService): add and use logout function
- feat(UserService): add clearUserFromLocalStorage fn
- test(AuthService): add unit test for logout
- test(UserService): add tests for clearUserFromLocalStorage
- test(UserService): update tests for fetchUser

refactor(auth.client): (4) extract admin logout service function to Typescript 

---

src/public/services/__tests__/AdminSubmissionsService.test.ts

#2054 had no unit tests for the newly added method
Adds unit tests to download related methods for AdminSubmissionService
- Details ...

test(adminsubmissionservice): unit tests for download methods

---

src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/services/captcha.client.service.js

#2118 broke the submissions pipeline because of an overlooked dependence of the frontend Captcha service on the feature toggles. This was not caught by end-to-end tests because captcha is always disabled for those tests.
Remove the dependence on the feature toggles.
Functionality can be verified by submitting a form with captcha enabled.

fix(submissions): remove captcha dependence on feature toggle

---

docker-compose.yml
src/app/config/feature-manager/index.ts
src/app/config/feature-manager/sentry.config.ts
src/app/config/feature-manager/types.ts
src/app/loaders/express/__tests__/helmet.spec.ts
src/app/loaders/express/helmet.ts
src/app/loaders/express/locals.ts

Part of #1842 
Removes Sentry configuration from feature manager.
- Details ...
- Server-side only
**Note that the server will now crash in the absence of the following environment variables:**
- `SENTRY_CONFIG_URL`
- `CSP_REPORT_URI`

feat(feature-manager): remove Sentry from feature manager

---

src/app/modules/frontend/frontend.controller.ts
src/app/modules/frontend/frontend.routes.ts
src/app/routes/api/v3/client/client.routes.ts

Old clients make API calls to the /features endpoint in order to retrieve the list of features currently enabled in the application. However, since the feature manager is being deprecated, all features are always enabled. This means the dependence of this API endpoint on the feature manager is blocking the deprecation of the feature manager.
Part of #1842 
Hardcode the API response from the /features endpoint until old clients stop calling it. This allows the rest of feature manager to be safely deprecated.

feat(feature-manager): hardcode /features API response

---

src/app/modules/verification/verification.constants.ts
src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/app/services/mail/mail.types.ts
src/app/services/mail/mail.utils.ts
src/app/views/templates/sms-verification-disabled.server.view.html

Admins who have breached their limit of allowable verified SMS should have an eamil sent out to them 
1. Adds a method to mail service to send templated disabled emails out to users.

feat(sms-limiting): email for disabling sms verification

---

docker-compose.yml

Localstack outputs repeated "Waiting for all LocalStack services to be ready" logs for a long time after the dev server starts up, even though the health endpoint reflects that all its services are running. This is annoying.
Mute Localstack container logs.

build: mute Localstack logs

---

src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/app/services/mail/mail.types.ts
src/app/services/mail/mail.utils.ts
src/app/views/templates/sms-verification-warning.view.html

This PR is part 1 of #1935 - warning emails should be sent out at certain pre-defined threshold
1. Adds a method to mail service to send templated warning emails out to users. 
- the method **does not** care about the current count - that part will be done by verification service in an upcoming PR

feat(sms limit): sms warning for different limits

---

package-lock.json
package.json
src/public/main.js
src/public/modules/forms/admin/controllers/admin-form.client.controller.js
src/public/modules/forms/admin/controllers/list-forms.client.controller.js
src/public/modules/forms/admin/controllers/view-responses.client.controller.js
src/public/modules/forms/base/components/end-page.client.component.js

As we prepare for the React migration, we should minimise the number of 
AngularJS-specific libraries that are currently in use.
As we have no need for the AngularJS filters and directives that
angular-moment provides, remove it completely, referencing moment
as a CommonJS module instead.
Verify that date formatting remains correct for:
- Admin dashboard form list
- Form builder heading
- Viewing responses in storage mode
- On form submission

refactor(angularjs): remove angular-moment

---

src/shared/util/uen-validation.ts

Simplifies the logic to validate UENs. Implementation can be cross-referenced against the [docs](https://www.uen.gov.sg/ueninternet/faces/pages/admin/aboutUEN.jspx).
Manual tests as per #2100.

refactor: simplify isUenValid logic

---

src/public/modules/users/controllers/authentication.client.controller.js

Missing undefinedness check for email resulted in `validator` throwing an error.  This PR fixes that.
**Bug Fixes**:
- fix(auth.client.controller): add missing undefinedness check

fix(auth.client.controller): add missing undefinedness check

---

src/app/config/logger.ts
src/app/modules/webhook/webhook.consumer.ts
src/app/modules/webhook/webhook.producer.ts

Closes #2180 
Makes the following changes:
- When a webhook is no longer retried, log as an error instead of warning. This is for better monitoring, since widespread retry failures could be a symptom of a bug.
- Log the form ID in error logs in the webhook consumer wherever possible.
- Log the message content in the webhook producer.

chore: improve logging for webhook retries

---

frontend/.eslintrc
frontend/.storybook/preview.tsx
frontend/src/app/App.tsx
frontend/src/components/Button/Button.stories.tsx
frontend/src/components/Button/Button.tsx
frontend/src/components/IconButton/IconButton.stories.tsx
frontend/src/components/IconButton/IconButton.tsx
frontend/src/components/IconButton/index.ts
frontend/src/components/Spinner/Spinner.tsx
frontend/src/index.tsx
frontend/src/theme/components/Button.ts
frontend/src/theme/foundations/colours.ts

This PR adds styling for the button active state. Stories have also been updated.
Also add `colorScheme` theming for `outline`, `clear`, and `reverse` variants after discussion with @pearlyong 
The colorScheme update is to prepare the theming for `IconButton` component coming in a next PR
Closes #1997
**Features**:
- feat(button): add active state styling to buttons
- feat: update button stories
- feat: update button theme to take into account color scheme

feat(design-system): complete Button, add IconButtons and update stories

---

scripts/20210616_remove-permissionList-read/remove-permissionList-read.js

Script to remove permissionList.read key from the database.
The key is already removed from the schema, so old/new clients should not matter. 
Any updates by old forms (with the deprecated key already saved in client) will not affect the database.
Related to #2177
**New scripts**:
- add script to remove permissionList.read key from the database.

docs(script): add script to remove permissionList.read key from the db

---

scripts/20210517_validation-object/script.js
src/app/models/field/common/textValidationOptionsSchema.ts
src/app/models/field/longTextField.ts
src/app/models/field/numberField.ts
src/app/models/field/shortTextField.ts
src/app/utils/field-validation/validators/__tests__/number-validation.spec.ts
src/app/utils/field-validation/validators/__tests__/text-validator.spec.ts
src/app/utils/field-validation/validators/numberValidator.ts
src/app/utils/field-validation/validators/textValidator.ts
src/public/modules/forms/admin/constants/covid19.js
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html
src/public/modules/forms/base/componentViews/field-number.client.view.html
src/public/modules/forms/base/componentViews/field-textarea.client.view.html
src/public/modules/forms/base/componentViews/field-textfield.client.view.html
src/public/modules/forms/viewmodels/Fields/MixIns.js
src/types/field/baseField.ts
src/types/field/longTextField.ts
src/types/field/numberField.ts
src/types/field/shortTextField.ts
src/types/field/utils/textField.ts
src/types/field/utils/virtuals.ts
tests/unit/backend/helpers/generate-form-data.ts

Restores changes from #2040, which were reverted in #2169.
- New client incompatible with old server

refactor: restore redundant ValidationOptions removal

---

src/app/routes/api/v3/admin/forms/__tests__/admin-forms.form.routes.spec.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/public/services/AdminViewFormService.ts
src/public/services/__tests__/AdminViewFormService.test.ts

Restores changes from #2113, which were reverted in #2169.
- New client incompatible with old server due to new API endpoint

feat: restore v3 API for retrieving individual admin form

---

src/app/modules/submission/encrypt-submission/__tests__/IncomingEncryptSubmission.class.spec.ts

Moved the encrypt-mode-specific test-cases from the `getProcessedResponses` scope of the submissions test suite.

feat(incoming-encrypt-submission): add more tests

---

src/public/modules/core/css/landing.css
src/public/modules/core/views/landing.client.view.html

The current numbers on the home page is hard to read (too many digits). This right-aligns numbers and adds commas per locale settings.
Fixed the CSS and added Angular's `DecimalPipe`.
**BEFORE**:
**AFTER**:
Verify that the home page loads and looks as expected.

fix: Clean-up and right-align home page statistics

---

src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/submission/__tests__/submission/submission.service.spec.ts
src/app/modules/submission/email-submission/ParsedResponsesObject.class.ts
src/app/modules/submission/email-submission/__tests__/ParsedResponsesObject.class.spec.ts
src/app/modules/submission/email-submission/email-submission.controller.ts
src/app/modules/submission/email-submission/email-submission.types.ts
src/app/modules/submission/submission.service.ts

This is a quick refactor that encapsulates the `parsedResponses` object in the email-form submission flow.
Parsed responses array gets passed into functions which can freely modify it. Certain methods also rely on an implicit ordering of the array in order to function properly, creating a tight coupling to the sequence in which middlewares are chained.
See #1104
The `getProcessedResponses` function has been moved into the `parseResponses` method of the `ParsedResponsesObject`. This object also tracks a separate array of NDI responses, which used to be directly appended to the end of the `parsedResponses` array.
Copy this [email-mode form](https://staging.form.gov.sg/60d0086fcf8dc0001197b48d/use-template).

refactor(email-submission): encapsulate parsedResponses

---

docker-compose.yml
src/app/config/feature-manager/index.ts
src/app/config/feature-manager/sms.config.ts
src/app/config/feature-manager/types.ts
src/app/services/sms/__tests__/sms.factory.spec.ts
src/app/services/sms/sms.factory.ts

Removes the SMS feature from feature manager.
Part of #1842
The implementation is along the same lines as all previous PRs related to #1842. Note that the `.factory` file in the `sms` service was maintained due to the function signatures in `sms.service` requiring a default Twilio config.
However, there was a slight wrinkle when deciding how to mock Twilio credentials in the dev environment. Twilio does provide [test credentials](https://www.twilio.com/docs/iam/test-credentials) which are not linked to the data in the production account. However, the test credentials are specific to each account, and the Twilio console still says to keep the test credentials secure. Hence the test credentials were not added as dev environment defaults.
- Details ...
**Note that the …

feat(feature-manager): remove sms from feature manager

---

src/app/modules/feedback/__tests__/feedback.service.spec.ts

One of the unit tests for form feedback is still flaky despite many attempts to fix it (#1620, #2217).
I finally realised that the array of form feedback returned is inherently non-deterministic. This is because form feedback with identical timestamps can be returned in any order, but the service being tested subsequently adds an `index` key depending on the order. This means there is no way for the test to exactly predict what the contents of the form feedback array should look like.
The solution was to omit the `index` key when checking for the shape of the form feedback array.

test: fix flaky form feedback test again

---

scripts/20210622_sync-allowedEmailDomains-with-hasAllowedEmailDomains/script.js

As mentioned in https://github.com/opengovsg/FormSG/pull/1698#issuecomment-864894628, we will be sunsetting the hasAllowedEmailDomains key in email form fields in 3 stages. This PR is stage 1 of 3.
This PR will handle
1. Correcting state inconsistency in DB that will arise when we switch from using `hasAllowedEmailDomains` as the source of truth to `allowedEmailDomains`.
2. After DB migration is complete, possible inconsistencies should be fixed.
- all `hasAllowedEmailDomains = false` will have `allowedEmailDomains = []`
- all `hasAllowedEmailDomain = true` must have non-empty `allowedEmailDomains`
See #1312.
- DB migration, not backwards compatible, though will not have any issues on a roll back since there is still a source of truth.
**New scripts**:
docs(script): …

docs(script): add script to sync (has)AllowedEmailDomains

---

src/public/modules/forms/admin/views/edit-start-page.client.modal.html

Closes #1279 
**BEFORE**:
**AFTER**:

feat: Admin form UI changes to "Edit Welcome" fields

---

scripts/20210628_create-isOnboardedAcc/create-isOnboardedAcc.js
scripts/20210628_create-isOnboardedAcc/delete-isOnboardedAcc.js
src/app/services/sms/sms_count.server.model.ts

querying smscounts is slow, even when we index on `formAdmin` and `msgSrvcId`. This PR aims to solve that by creating a boolean key to index on, so that we can speed up the query.
Creates a boolean key in `smscounts` that tracks whether the `msgSrvcSid` used in the verification is formSG's own.

chore(db): db script to create index on smscounts

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/types/database.ts
src/types/form.ts

The backend needs a way to disable sms verifications easily. This should also be done in a single query, so that we avoid overloading the database with requests, which can be non-ideal under load. 
This PR accomplishes the above through using an `updateMany` function defined on the schema. Some points are noted below for discussion
1. avoid updating timestamps on disabling. this is **intentional** and done to avoid confusion on the admin side. the reason for doing so is because admins expect their own actions to alter the last modified state of the form, and not something beyond their control. (informed @syan-syan on this already)
2. Returning `true` on service level - done because the service has no idea of the actual count it's supposed to update (and it should not). unable to return …

feat(verified-sms): disabling sms verifications

---

src/app/constants/filesize.ts
src/app/models/form.server.model.ts
src/app/modules/submission/email-submission/__tests__/email-submission.receiver.spec.ts
src/app/modules/submission/email-submission/email-submission.receiver.ts
src/app/utils/field-validation/validators/attachmentValidator.ts
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/controllers/edit-start-page-modal.client.controller.js
src/public/modules/forms/admin/views/edit-start-page.client.modal.html
src/public/modules/forms/base/componentViews/field-attachment.client.view.html
src/public/modules/forms/base/components/field-attachment.client.component.js
src/shared/constants.ts

refactor: ensure consistent filesize const

---

src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.routes.ts
src/public/main.js
src/public/modules/forms/admin/componentViews/form-emails-input.client.view.html
src/public/modules/forms/admin/components/form-emails-input.client.component.js
src/public/modules/forms/admin/directives/validate-form-emails-input.directive.js

Closes #2189 
- https://github.com/opengovsg/FormSG/commit/dd7bd161a89beb93884156749f63b0f924e8268d: refactor the form emails input to use `ng-message` with a validation directive instead of manually validating on `ng-change`
- https://github.com/opengovsg/FormSG/commit/aa4d6423968336c401616fe034d408960e7f34a1: update the validation directive to return true for all validators as long as the response mode is not `'email'`
- https://github.com/opengovsg/FormSG/pull/2263/commits/f55660530e269cac30b148b55f316e221bef5824: update Joi validation on all form creation (including duplication and copy) endpoints to allow empty strings or arrays for the `emails` key if the response mode is not email mode
- No input
- Any invalid email present
- Duplicate emails present
- More than 30 non-duplicate …

fix: allow creation of storage form when emails are invalid

---

src/app/modules/bounce/__tests__/bounce-test-helpers.ts
src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/app/views/templates/submit-form-email.server.view.html
src/app/views/templates/submit-form-summary-pdf.server.view.html
src/public/modules/forms/admin/views/view-responses.client.view.html
src/public/modules/forms/helpers/CsvMergedHeadersGenerator.ts
tests/end-to-end/helpers/email-mode.js
tests/end-to-end/helpers/encrypt-mode.js
tests/unit/frontend/forms/helpers/CsvMergedHeadersGenerator.test.js

The UI uses various terms to refer to the submission ID. It would be less confusing to users if we standardised the terminology.
Closes #2187
Update all user-facing references to the submission ID to "Response ID".

feat: rename "Reference Number" to "Response ID"

---

src/app/modules/form/public-form/__tests__/public-form.controller.spec.ts
src/app/modules/form/public-form/__tests__/public-form.routes.spec.ts
src/app/modules/form/public-form/public-form.controller.ts
src/app/modules/spcp/__tests__/spcp.controller.spec.ts
src/app/modules/spcp/spcp.controller.ts
src/app/modules/spcp/spcp.service.ts
src/app/modules/spcp/spcp.types.ts
src/app/modules/spcp/spcp.util.ts
src/app/routes/api/v3/forms/__tests__/public-forms.form.routes.spec.ts
src/app/routes/api/v3/forms/public-forms.auth.routes.ts
src/public/modules/forms/base/componentViews/end-page.html
src/public/modules/forms/base/componentViews/start-page.html
src/public/modules/forms/base/controllers/submit-form.client.controller.js
src/public/modules/forms/base/directives/submit-form.directive.js
src/public/modules/forms/services/spcp-session.client.factory.js
src/public/services/PublicFormAuthService.ts
src/public/services/__tests__/PublicFormAuthService.test.ts
src/types/api/auth.ts
src/types/spcp.ts

Closes #2065
- App is updated to use `/logout` endpoint to delete sp/cp jwt cookie.
- New frontend client expects `/logout` endpoint to be available and will not be able to logout from sp/cp upon rollback

feat: Set SP/CP JWT cookie to HttpOnly

---

src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/api/v3/admin/forms/admin-forms.settings.routes.ts
src/public/modules/forms/admin/controllers/collaborator-modal.client.controller.js
src/public/modules/forms/admin/views/collaborator.client.modal.html
src/public/services/UpdateFormService.ts

Enables writers and readers to remove themselves from the collaborator list.
Closes #33
Added a new `DELETE /:formId([a-fA-F0-9]{24})/collaborators/self` route that removes the current user from the collaborator list, and wired up the appropriate parts of the front-end for this.
Create a new form with collaborators, then login as the collaborators and manually remove themselves. It should succeed.

feat: Remove self from collaborator list

---

src/app/models/field/__tests__/emailField.spec.ts
src/app/models/field/emailField.ts

Bug was due to regression caused in #1971 where the set hook was converted to a validator hook. Upon further examination, the set hook was needed to set includeFormSummary to false on encrypt-mode forms.
The pre-validate hook will always pass if storage mode forms's email.includeFormSummary is always set to true, and is thus redundant and kept deleted.
Closes #2283
- Details ...
**Bug Fixes**:
- fix: allow duplicating email field with PDF to storage mode
Add unit tests for emailField to check that storage mode forms set `includeFormSummary` to false regardless

fix: allow duplicating email field with PDF to storage mode

---

package.json

Allows TypeScript version to be upgraded since the bug with `zod` has been [fixed](https://github.com/colinhacks/zod/releases/tag/v3.2).

fix(deps): unpin typescript

---

src/types/api/user.ts

Beta flags are returned by the backend, but the Zod types used by the frontend
does not recognise them. Make the appropriate change to do so.

fix(types): recognise User.betaFlags in zod

---

src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.form.routes.spec.ts

`AdminFormService.duplicateFormField` occasionally returns the wrong error type. This is because the underlying schema method returns null when either the field or the form was not found.
Insert a check after calling `form.duplicateFormFieldById` to see if there is a field and return the error appropriately.
- Details ...
This also fixes an erroneous integration test where the property being tested was when teh field wasn't found but the `expect` block checks that the _form_ was not found.

fix(admin-form.service): fixed logical error in duplicate form field

---

src/app/config/features/spcp-myinfo.config.ts
src/app/loaders/express/locals.ts
src/public/modules/forms/services/spcp-session.client.factory.js

- Server was unable to delete spcp cookie in production due to different domain name (cookies had . prefix)
- Env vars will be updated to remove . prefix
- However, server will not still be able to remove existing cookies as they were set with (.) domain. These cookies may remain valid for up to 30 days (SP remember me option)
- To resolve this, client will continue to attempt to delete cookie upon clicking 'logout', in addition to calling `/logout` endpoint. TODO: Remove in #2329
- new env var of `OLD_SPCP_COOKIE_DOMAIN` should be set to .form.gov.sg for prod at the time of deployment
- existing env var of `SPCP_COOKIE_DOMAIN` should be changed to blank for prod at time of deployment
- Added new env var `OLD_SPCP_COOKIE_DOMAIN` for client to delete old cookie.

feat: client to delete spcp cookie

---

src/app/modules/form/admin-form/__tests__/admin-form.routes.spec.ts
src/app/modules/form/form.errors.ts
src/app/modules/form/public-form/__tests__/public-form.controller.spec.ts
src/app/modules/form/public-form/__tests__/public-form.routes.spec.ts
src/app/modules/form/public-form/public-form.utils.ts
src/app/routes/api/v3/forms/__tests__/public-forms.feedback.routes.spec.ts
src/app/routes/api/v3/forms/__tests__/public-forms.form.routes.spec.ts

Visiting archived form URL shows uninformative error message
Closes #1759
Instead of getting the HTTP Reason code for 410 Gone, using the exception's `message` property.
**Bug Fixes**:
Shows the correct error message!
**BEFORE**:
**AFTER**:
A unit test has been updated, also for manual testing,
1. Create a form.
2. Get the link.
3. Archive it.
4. Visit the link.
5. See the error message in all its glory.

fix: visiting archived form URL to show correct error message

---

src/public/modules/users/controllers/authentication.client.controller.js
tests/end-to-end/login.e2e.js

Some emails pass the front-end validation, however, fail the backend validation with `Joi`. The response format is not plain text. Thus, `linky` cannot render the error properly as the correct message is lodged deep in `response.data.validation.body.message`.
Closes #2250
I updated the error message capture method in the frontend, to look for `Joi` error messages first, then to fall back on treating the entire response body as the plain-text error message.
- Details ...
**Bug Fixes**:
For certain emails that fail frontend validation, a correct error message is displayed.
**BEFORE**:
**AFTER**:
I did add an e2e-test. You can get creative with emails to test to make sure the frontend validator fails. Make it *sneaky*.

fix: read email validation error message from Joi response

---

src/app/modules/examples/__tests__/helpers/prepareTestData.ts
src/app/modules/examples/examples.queries.ts
src/public/modules/forms/admin/controllers/list-forms.client.controller.js
src/public/modules/forms/admin/directives/settings-form.client.directive.js
src/public/modules/users/controllers/examples-card.client.directive.js
src/public/services/BetaService.ts
src/public/services/__tests__/BetaService.test.ts

#2370 happened because the frontend `BetaService` is coupled to beta _fields_, as opposed to form-level beta features such as SGID.
Closes #2370 
Generalise `BetaService` to be able to apply to any _form_-level feature. Also, return the form `authType` from the examples page queries so we are able to check the auth type when seeing whether the user has permissions to duplicate the form.

fix(BetaService): make SGID form-level beta feature

---

src/app/modules/form/public-form/__tests__/public-form.controller.spec.ts
src/app/modules/form/public-form/__tests__/public-form.service.spec.ts
src/app/modules/form/public-form/public-form.controller.ts
src/app/modules/form/public-form/public-form.service.ts
src/app/modules/sgid/__tests__/sgid.controller.spec.ts
src/app/modules/sgid/__tests__/sgid.routes.spec.ts
src/app/modules/sgid/sgid.constants.ts
src/app/modules/sgid/sgid.controller.ts
src/app/modules/spcp/spcp.types.ts
src/app/routes/api/v3/forms/public-forms.auth.routes.ts

Closes #2360
- Allow MyInfo authtype for `/logout` endpoint and update `JwtName` type to include MyInfoCookie
**(tested on staging)**

fix: allow myinfo authtype for logout

---

.github/workflows/ci.yml
.travis.yml
package.json
tests/end-to-end/helpers/encrypt-mode.js
webpack.dev.js

End-to-end tests are extremely flaky on Travis, and have been failing every other build.
Part of #573
Migrate the end-to-end tests to GitHub Actions. I encountered a series of problems which are explained in the commit messages.

build: move end-to-end tests to GitHub Actions

---

package-lock.json

Note: opening PR in draft mode to get feedback first
Multiple dependencies are out of date, and have vulnerabilities reported against them. 
Running a fresh `npm audit` gives the following warning:
```
found 176 vulnerabilities (1 low, 166 moderate, 6 high, 3 critical)
run `npm audit fix` to fix 162 of them.
4 vulnerabilities require semver-major dependency updates.
10 vulnerabilities require manual review. See the full report for details.
```
Fix the low hanging fruits first in this PR by running `npm audit fix`.
This had the following results:
```
fixed 162 of 176 vulnerabilities in 3047 scanned packages
10 vulnerabilities required manual review and could not be updated
3 package updates for 4 vulnerabilities involved breaking changes
```
The other dependency upgrades should be done …

chore(audit-fixes): fix 162 vulnerability

---

src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/form/admin-form/admin-form.utils.ts
src/app/modules/form/form.utils.ts
src/app/modules/verification/verification.errors.ts
src/app/modules/verification/verification.util.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.form.routes.spec.ts
src/shared/util/verification.ts
src/types/field/mobileField.ts
src/types/field/utils/guards.ts
src/types/form.ts

This PR addresses the edge case when the admin wishes to perform some operation on the form field but should be prohibited from doing so because their sms limit has been exceeded. This PR is dependent on #2276 
The solution consists of 2 portions. 
**Checking if the operation should be prohibited**
- this is done though a service method called `shouldUpdateFormField`, where the applicable scenario is checked - the field is of type Mobile and it's verifiable. When this occurs, the free sms counts used of the admin is retrieved and checked to see if the limit has been exceeded, and a `Result` is returned accordingly. 
**Preventing operation if it should be prohibited**
- because the type returned in the error case is `Err<some base type>`, the error returned will be propagated and …

feat(sms-limiting): disable sms verifications toggling

---

src/app/modules/submission/IncomingSubmission.class.ts
src/app/modules/submission/email-submission/ParsedResponsesObject.class.ts
src/app/utils/logic-adaptor.ts

As a lead up to the checkbox logic feature in #2389, an adapter layer is added in between the logic module and the rest of the backend. In this PR, the adapter simply calls the functions in the logic module but returns `neverthrow`'s `Result`.

refactor(logic): add adaptor layer to backend and refactor getVisibleFieldIds and getLogicUnitPreventSubmit callers

---

package.json

Add postinstall script to also install node modules inside the root shared folder.
There is no issue yet since all the shared folders' node_modules are also installed in the root package.json, but might be an issue in the future. Pre-emptively adding postinstall step first.

chore: add postinstall script to install /shared modules

---

shared/types/response.ts
src/public/.eslintrc
src/public/modules/forms/viewmodels/Form.class.js
src/public/services/EncryptionService.ts
src/public/services/__tests__/EncryptionService.test.ts

Storage mode submissions saved to the database cannot be updated due to end-to-end encryption. This means that submissions saved in the wrong format can be difficult or impossible to salvage.
This PR introduces `EncryptionService` which contains a validation function, enforcing the shape of the submission response. Using this service with the present AngularJS code in production and subsequently reusing it with React can assure us that it the encryption is being performed correctly in the new frontend.
To implement the above service, various field response zod schema constants are created in the new rooted `/shared` folder and used for the validation.
Closes #2209
- Pure client side validation
**Features**:
- feat: add shared field response types with zod validation …

feat(client): add EncryptionService to validate encrypt submission responses

---

.template-env
docker-compose.yml
docs/DEPLOYMENT_SETUP.md
src/app/config/features/spcp-myinfo.config.ts
src/app/loaders/express/locals.ts
src/app/modules/spcp/__tests__/spcp.test.constants.ts
src/public/modules/forms/base/controllers/submit-form.client.controller.js
src/public/utils/injectedVariables.ts

We have had to use the basic IS_GENERAL_MAINTENANCE environment variable for MyInfo specific banners for a couple times now, and thus should really have a MyInfo specific banner environment variable.
Closes #1779

feat: add MYINFO_BANNER_CONTENT env var for bannering myinfo forms

---

package-lock.json
package.json
src/app/modules/auth/auth.middlewares.ts
src/app/modules/auth/auth.utils.ts
src/app/modules/billing/billing.controller.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
src/types/vendor/express.d.ts

The package [`@types/express-session`](https://www.npmjs.com/package/@types/express-session) introduced a breaking change between `1.17.0` and `1.17.1` when it cleaned up its type definition. See discussion [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#r44080605).
Although our `package.json` declaration is `^1.17.0`, we have been protected from typescript compilation errors thanks to the version being locked in `package-lock.json`.
Doing a fresh install from scratch based on package.json alone however yields typescript compilation errors on type isses like these:
```
src/app/modules/auth/auth.controller.ts:163:21 - error TS2339: Property 'user' does not exist on type 'Session & Partial<SessionData>'.
163         req.session.user …
```

fix: Fix express session types based on latest definitions

---

package-lock.json
package.json

An open redirect issue was flagged in [`url-parse@1.5.1`](https://github.com/opengovsg/FormSG/pull/2469#issue-699316411) used by [twilio@3.66.0](https://www.npmjs.com/package/twilio)
closes [this snyk issue](https://app.snyk.io/org/open-government-products/project/d5cee0f2-80bf-4efc-9f84-61ab911f7cef#issue-SNYK-JS-URLPARSE-1533425)
Upgrade Twilio to next patch version 3.66.1 (released 12h ago! 💪 ), which upgrades the offending dependency (url-parse 1.5.1 -> 1.5.3)

fix(snyk): Fix vulnerability in Twilio

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts

SGID is currently not enabled in storage mode, and the settings tab UI prevents users from enabling SGID on a storage mode form. However, SGID email-mode forms can still be duplicated into storage mode while preserving the SGID auth type, resulting in invalid forms which cannot be submitted.
Closes #2390 
Add model-level validation which sets the `authType` to `NIL` when attempting to create an SGID form in storage mode.

fix(SGID): disallow SGID authentication in storage mode

---

src/app/modules/auth/__tests__/auth.routes.spec.ts
src/app/modules/auth/auth.routes.ts
src/app/routes/api/v3/auth/__tests__/auth.routes.spec.ts
src/app/routes/api/v3/auth/auth.routes.ts
src/public/modules/users/controllers/authentication.client.controller.js

Closes #2455 
- Correct casing in Joi OTP error message
- In the frontend, search for a Joi validation error and prioritise rendering it over the API response. This is because the presence of a Joi error message implies the absence of an API response.

fix(login): show Joi validation error correctly

---

shared/types/billing.ts
src/app/models/__tests__/login.server.model.spec.ts
src/public/services/BillingService.ts
src/types/api/billing.ts
src/types/login.ts

> Note that this PR builds on the typings exposed by #2385
This PR extracts out billing related types to the root shared folder
Related to #2066
- Only type changes
**Features**:
- move billing related types to root shared folder
- use relocated types in client and server

feat(shared-types): move billing related types to shared folder

---

src/app/loaders/express/locals.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/app/services/sms/sms.types.ts
src/types/api/form.ts
src/types/database.ts
src/types/form.ts

This PR is part 1 of `sms-limiting`; this PR does a few things. 
1. Adds in methods for sending warning/disabling mail
2. Adds in a new endpoint for count retrieval (`/:formId/verified-sms/count/free`) 
3. Adds in a db script for updating the `smscounts` table to have the `isOnboardedAcc` key. 
4. Adds in service/db method to disabling sms verifications for admin (this is **unused** here)
This PR should not have any observable interface by which we can perform manual testing, except for `/count/free`. 
**preconditions**
1. run this query to obtain your sms counts: 
```
db.getCollection('smscounts').countDocuments({
"formAdmin.userId": ObjectId("your userId here"),
smsType: 'VERIFICATION', 
isOnboardedAccount: false, 
})
```
2. the db should already be populated with the …

feat(sms-limiting): prerelease

---

src/app/config/features/sms.config.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/api/v3/admin/forms/admin-forms.form.routes.ts
src/app/services/sms/__tests__/sms.service.spec.ts
src/app/services/sms/__tests__/sms_count.server.model.spec.ts
src/app/services/sms/sms.service.ts
src/app/services/sms/sms.types.ts
src/app/services/sms/sms_count.server.model.ts
src/types/api/form.ts
src/types/form.ts

This PR adds a new key (`isOnboardedAccount`) to the database as well as a new (and unused) endpoint. This PR is a dependency of `sms-limiting`. 
This PR goes out 1 week in advance so that the db key can be created ahead of time. The `smscounts` database will then have all previous entries updated through running a db script (included in future PR) the night before the feature release. 
- Details ...

feat(sms-limiting): db dependencies

---

package.json

Adds scripts so that
- `storybook` can be run without `cd`-ing into the `frontend` directory
- `npm install` automatically covers frontend dependencies

chore: add root-level scripts for frontend

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/public/modules/forms/admin/directiveViews/settings-form.client.view.html

Closes #2466
- Unit tests have been added to form schema

feat: loosen esrvcId validation to only restrict whitespace

---

package-lock.json

package [bcrypt](https://www.npmjs.com/package/bcrypt) that we use has dependency on [tar](https://www.npmjs.com/package/tar) for which [2 vulnerabilities were reported by Snyk](https://app.snyk.io/org/formsg/project/7d2653ec-310a-4c60-a94a-eca85308e725#issue-SNYK-JS-TAR-1536531)
run 
```bash 
npm install bcrypt@latest
```
to update all of bcrypt dependencies
* Impact:High: Upgrade affects encryption, which is a fundamental aspect of Form
* Likelihood:Low: No application code changes

chore: update bcrypt dependencies in package-lock

---

src/app/config/features/spcp-myinfo.config.ts
src/app/loaders/express/locals.ts
src/public/modules/forms/services/spcp-session.client.factory.js

- Hotfix was introduced in #2328 to temporarily allow client to delete sp/cp cookie for backward compatibility
- As affected cookies have all expired, this PR removes the client code to delete the cookie
- Closes #2329
- Details ...
**New environment variables**:
- `env var` : env var details
`OLD_SPCP_COOKIE_DOMAIN` env var deleted

feat: remove frontend code to delete spcp cookie

---

src/public/modules/forms/admin/controllers/pop-up-modal.client.controller.js
src/public/modules/forms/admin/css/edit-form.css
src/public/modules/forms/admin/directiveViews/configure-mobile.client.view.html
src/public/modules/forms/admin/directives/configure-mobile.client.directive.js
src/public/modules/forms/admin/views/pop-up.client.modal.html

This changes the UI to be more polished.
This takes place on 3 fronts: 
1. adding a quota beneath the toggle so that users are able to see their sms counts. 
2. changing the sms counts modal button from red -> blue.
3. updating the sms counts modal description.
**Quota**
**Modal**

feat(sms-limiting): ui changes for modal

---

shared/utils/verification.ts
src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/__tests__/form.service.spec.ts
src/app/modules/form/form.service.ts
src/app/modules/form/form.utils.ts
src/app/services/mail/__tests__/mail.service.spec.ts
src/app/services/mail/mail.service.ts
src/app/services/mail/mail.types.ts
src/app/services/mail/mail.utils.ts
src/app/views/templates/sms-verification-disabled-admin.server.view.html
src/app/views/templates/sms-verification-disabled-collab.server.view.html
src/app/views/templates/sms-verification-warning.view.html
src/types/form.ts

We want to inform admins on the email sent out about forms that would be affected by SMS verification being disabled so that they are able to accurately assess the impact.
This solution has 3 parts. 
1. write a db query + wrapper to interface with the database and retrieve the forms of the admin that will be impacted.
2. Refactor disabled mail sending into 2 portions 
a. Send mail to admin - this includes all forms that will be impacted
b. Send mail to collaborators - only the forms that they are a part of 
3. Refactor warning mail sending - same as point 2a. 
**Disabled mail for admin**
**Disabled mail for collaborator**
**Warning mail for admin**

feat(sms-limiting): disabled email

---

package-lock.json
package.json

Also reverts opengovsg/FormSG#2572
The latest version is causing testcafe to be extremely slow, causing test failures due to tests running before the page renders. Revert and freeze to previous version. There is almost no point in updating testcafe as e2e tests are slowly becoming less and less useful due to the impending React migration. We will probably re-evaluate the e2e testing framework used then.

chore: freeze test-cafe package version to 1.15.1

---

frontend/src/components/Link/Link.stories.tsx
frontend/src/theme/components/Link.ts

Whilst styling for Footer, see that the links are of a different color. Extends Links to be styleable with colorScheme.

feat(design-system): allow colorScheme prop to be passed into Link components

---

src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.errors.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.util.ts

At the present moment, users that have already loaded the page can continue to verify their mobile number, even when the form then disables OTP verification 
Closes #2531
1. check if the form is onboarded 
2. check if the form has verifiable mobile fields
**Notes** 
users can request OTP from 2 endpoints - `handleGetOtp` or `handleGenerateOtp`. this check is only added on `handleGenerateOtp` because there are very few calls to `handleGetOtp` and we would have to query for actual form level data from the db to establish if the otp generation is valid.

fix(verification): prevents otp request when limit exceeded

---

src/public/modules/forms/admin/directiveViews/configure-mobile.client.view.html

1. Modal shows the counts when teh form is onboarded. 
1. Hide the count

fix(sms-limiting): hide counts when forms are onboarded

---

frontend/__tests__/storyshots/jest.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/Pagination/Pagination.stories.tsx
frontend/src/components/Pagination/Pagination.tsx
frontend/src/components/Pagination/PaginationDesktop.tsx
frontend/src/components/Pagination/PaginationMobile.tsx
frontend/src/components/Pagination/index.ts
frontend/src/hooks/usePaginationRange.ts
frontend/src/theme/components/Pagination.ts
frontend/src/theme/components/index.ts
frontend/tsconfig.paths.json

This PR adds the Pagination component, along with its stories. Uses a `usePagination` hook to generate the correct buttons.
Closes #2016 
**Features**:
- add Pagination component and stories
**Improvements**
- chore: move root path alias to bottom
- in a bid to let other paths resolve first before trying to use the root import, not sure if it works
In storybook
- "lodash": "^4.17.21"

feat(design-system): add Pagination component and stories

---

src/public/modules/forms/admin/directives/settings-form.client.directive.js

- Currently, the modal still pops up when SGID auth type is selected even though there is no need. This may cause confusion, especially if users have entered an invalid esrvcId and then toggled to SGID. The esrvcId check may fail and leave the admin user with no steps to rectify.
- Closes #2512
- Details ...

fix: disable eserviceid check modal for sgid forms

---

frontend/src/components/FormControl/FormLabel/FormLabel.tsx

Styling bug where height of label with optional text is different from one without the optional text. See gif of before and after.
**BEFORE**:
**AFTER**:

fix(react/FormLabel): remove extra height when optional indicator is shown

---

src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.util.ts

- Fixes bugs with #2586
- Checks for disabled verified mobile field using array length instead of falsyness
- Disallows OTP for fields which are not verifiable even if `msgSrvcName` is set
- Also fixes missing error message routing on `OtpRequestError` so that the correct error message is shown to user
- Reimplements check at the field level instead of form level because `handleGenerateOtp`  is used by both email and sms fields, and also because there may be more than one verified mobile field
- Also adds additional unit tests to prevent code regression

fix: prevents otp request when limit exceeded

---

frontend/src/assets/icons/BxCheckAnimated.tsx
frontend/src/components/Checkbox/Checkbox.stories.tsx
frontend/src/components/Checkbox/Checkbox.tsx
frontend/src/components/Checkbox/useCheckboxOthers.ts
frontend/src/theme/components/Checkbox.ts

- Fixes Checkbox component to use `forwardRef`
- Implements "Others" option for checkbox
- Omits unsupported SVG props from `BxCheckAnimated` to get rid of React warnings in console
Part of #2008, purely code review for now. Design review will be done on `form-v2/checkbox-radio` branch when it is complete.

feat(Checkbox): implement Others option

---

.github/workflows/ci-angularjs.yml
.github/workflows/ci-react.yml

Irrelevant (and sometimes flakey) CI builds are slowing down the reviewing and merging of PRs for the React migration.
This PR updates the current CI github actions to only run on non form-v2 branches, and adds a new  `ci-react` github action that only runs on form-v2 branches.

chore(v2): update Github actions for form-v2 branches

---

.github/workflows/chromatic.yml

Chromatic is not generating story differences properly as develop branch is not being kept up to date. This PR updates the CI workflow of Chromatic to also build on pushes to `form-v2/develop`

chore: enable chromatic to build on pushes to form-v2/develop branch

---

src/app/models/form.server.model.ts
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/admin/views/edit-fields.client.modal.html

Closes #1814 
As discussed, adds relevant checks for field size on the form field editor itself.

fix: Add 10 MB max length checks to form field editor

---

src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.model.ts
src/app/modules/verification/verification.service.ts
src/types/verification.ts
tests/unit/backend/helpers/jest-logger.ts

Some admins are receiving spammy emails about their free SMS OTP tier quota being hit when the public verifies their email in a verified email field. This is due to the sms check being applied on every OTP generation, regardless of whether the field to verify is a mobile or email field.
This PR fixes the bug by only processing any sms checking action on verified mobile fields.
- Details ...
**Bug Fixes**:
- Check mobile fieldType before processing admin sms email

fix: only check for sms quota on verified mobile field OTP verifications instead of all verified fields

---

src/public/modules/forms/base/componentViews/field-radiobutton.client.view.html

We append a `&nbsp;` (non-breakable space) to **all** radio fields, which can cause a rendering error on mobile when the radio text just about covers the available space, as reported by a user for [this form](https://form.gov.sg/#!/611d22357f4b5f0012537c4a) on mobile.
The empty line is caused by a non-breakable character forcefully added in code to **all** radio fields.
The code had the comment: "Empty space is to prevent visual bug when radio button is empty".
I am assuming that:
* that comment might no longer be applicable? (checkbox fields don't have the same `&nbsp;` for example)
* There shouldn't be empty options anyway?
~~A better option is probably to make the rendering conditional where `&nbsp;` is not appended to the value, it is instead the default when the value is falsy. I …

fix(radio): Remove unnecessary nbsp from option text

---

src/app/utils/otp.ts

We have received a report that our OTP generation method does not have a uniform distribution of digits. While is not a serious security issue, it is clearly not an intended behaviour.
Closes #2768 (issue contains more details description of the distribution problem)
Use the native API [`crypto.randomInt()`](https://nodejs.org/api/crypto.html#crypto_crypto_randomint_min_max_callback), which was introduced in node 14.10 / 12.19, to avoid quantisation issues.
This is **not** a breaking change and is fully backward compatible
**Bug Fixes**
Uniform distribution brings back the guarantee that a random OTP guess only has 1/10e6 of being right.
- Log in: Verify OTP flow is working

fix(otp): Ensure uniform distribution of digits

---

frontend/src/components/FormControl/FormLabel/FormLabel.tsx

When focusing on the input field, only the label is being spoken out loud. The description should also be spoken out loud. 
This PR uses Chakra's FormHelperText component instead of Text to render so the input's aria-describedby prop contains the description id too.

feat(design-system): use FormHelperText for label description so SRs are aware

---

shared/types/field/attachmentField.ts
src/public/modules/forms/admin/controllers/edit-fields-modal.client.controller.js
src/public/modules/forms/services/attachment.client.service.js

Adds 4MB attachment so that email attachment users can create a form with a 4MB field and a 3MB field.
Closes #2639 
Adds a 4MB parameter to the relevant places.
**AFTER**:
Make sure that the 4MB option is visible when a form is created and that the check for 4MB size when a user uploads a file is working.

feat: Add 4MB attachment support

---

shared/utils/nric-validation.ts

While following code from the NIRC component, I ended up on the nirc validation where I thought several minor  improvements could be made. Below are some (very minor) issues I thought about when seeing the code
* The regex is using unnecessary constructs like `{1}`
* Regexp specifies both lowercase and uppercase matches, while it would be simpler to uppercase the input prior to running the test
* The regexp captures groups, but these are not used because the format validation and checksum validation are disjointed
* The digits string is exploded to iterate over the characters, but that is unnecessary since the coefficients is an array of the same format that could be used instead
* We can us the string array operator to read digits from the input, and to read checksum markers (i.e. …

refactor: use modern JS constructs to validate NRIC

---

.github/mergify.yml

- Mergify config does not specify each status check explicitly, against the recommendations of the [docs](https://docs.mergify.io/conditions/#validating-all-status-checks)
- Snyk.io security upgrades are not included in the mergify config, so they have to be approved and merged manually
Closes #1749 
- Specify all status checks explicitly in mergify config
- Include a config rule to approve and major non-major Snyk security upgrades
Taken from [Mergify config editor](https://dashboard.mergify.io/github/opengovsg/config-editor?repositoryName=FormSG).
Note that the "potential rule" is because this PR was taken when our Snyk license was still under "Open Government Products", so the relevant GitHub branch protection doesn't pass. This should no longer be the case for newer PRs for which the …

build(mergify): specify checks and include Snyk

---

shared/utils/nric-validation.ts

Reverts opengovsg/FormSG#2785
The PR was not compatible with IE11, which is not acceptable for end users.
Reverting now, to keep `develop:HEAD` release-clean. The PR will be re-introduced once it has been made compatible.
@mantariksh @tshuli

Revert "refactor: use modern JS constructs to validate NRIC"

---

.travis.yml

Travis has been running for every push after adding it back in #2675. This PR allows Travis to only run on the staging-alt branch on form-v2/develop

chore: run travis only on staging alt branch

---

frontend/src/components/Toggle/Switch.tsx
frontend/src/components/Toggle/Toggle.stories.tsx
frontend/src/components/Toggle/Toggle.tsx

Sometimes toggles require a loading state due to asynchronous calls, such as when toggling on a form's active state. This PR adds that third state to the Toggle component.

feat(react): add loading state to toggle

---

package-lock.json
package.json
src/app/services/mail/mail.utils.ts

`tsc` literally only touches `.ts` and `.js` files, and there is no way to make it process other extensions. This means other files that the server depends on such as the `.html` server view files are not moved to the `/dist` build folder.
Since our Docker build file had been updated to only keep the necessary files (in #2675) (only /dist folder is copied over), this means the view files will not be accessible by the express server (since they are not available in the Docker image).
That results in errors like 
```
error.message | ENOENT: no such file or directory, open '/opt/formsg/src/app/views/templates/otp-email.server.view.html'
```
This PR updates the build pipeline to copy any HTML files in the backend source folder into the build folder using the `copyfiles` tool.  This is …

fix(v2): correctly copy html files to /dist build folder

---

frontend/src/app/PublicRoute.tsx

The application accesses the need to redirect from a public route to a private route if the user is already authenticated. The link to redirect to is done by checking the URL that could possibly be stored in `location.state.from`. However, `location.state` could be undefined if the page had not been redirected from the application, resulting in an error boundary being hit.
This PR correctly types the `location.state` variable as possibly undefined.

fix(v2): correctly assert that public route location shape may be undefined

---

src/public/modules/core/css/core.css
src/public/modules/forms/base/directiveViews/submit-form.directive.view.html
src/public/modules/forms/base/directives/submit-form.directive.js
tests/end-to-end/helpers/selectors.js
tests/end-to-end/helpers/util.js

Updates the error message when the form is disabled to be more friendly and less intimidating.
Closes #2561 
Updated relevant logic and CSS to remove the Toastr error and add an error message below the submission button where relevant.
**BEFORE**:
**AFTER**:
Make sure that a form that needs to be disabled remains disabled.

feat: Update form submission disabled button

---

frontend/src/components/Banner/Banner.tsx
frontend/src/components/FormControl/FormLabel/FormLabel.stories.tsx
frontend/src/components/FormControl/FormLabel/FormLabel.tsx
frontend/src/components/InlineMessage/InlineMessage.tsx
frontend/src/components/Link/Link.tsx
frontend/src/hooks/useMdComponents.tsx
frontend/src/theme/components/Modal.ts

Some designs in Figma contains Form label descriptions with links. This seemed easier to achieve in markdown and thus the ability for markdown in FormLabel.Description is implemented.
See 
Whilst doing so, realize the `Link` component cannot be re-morphed into another type using the `as` prop which is a common in ChakraUI.  This commit was cherry picked from commit 22faa66 in #2683.
**Features**:
- Add `useMarkdown` prop in FormLabel.Description and `useMarkdownForDescription` prop in the main FormLabel component to allow markdown in form label descriptions.
- Allow `as` prop in custom Link component
New story added in Storybook for markdown in form label description.

feat(react): allow markdown in FormLabel description, allow `as` prop in custom Link component

---

frontend/src/features/env/EnvService.ts
frontend/src/features/env/queries.ts
shared/types/core.ts
src/app/modules/frontend/frontend.controller.ts
src/app/modules/frontend/frontend.routes.ts
src/app/modules/frontend/frontend.service.ts
src/app/routes/api/v3/client/client.routes.ts

The old route was `/client/environment`, which sent back the appropriate env vars as a javascript file to be merged into some header in the html. This seems unnecessary in React and we can just send the environment variables as an object instead.
For backwards compatibility, create new service and endpoint.
- Details ...
**Features**:
- feat: add `api/v3/client/env` endpoint for sending client related env vars
- feat: add env service and query to retrieve env vars from server

feat(form-v2): add `/client/env` route for sending client env vars as JSON

---

frontend/src/components/Toast/Toast.stories.tsx
frontend/src/components/Toast/Toast.tsx
frontend/src/hooks/useToast.ts

Some toasts require something like links to be appended. This PR adds the capability to Toasts, much like on Banners and InlineMessage components
ChakraUI's default useToast hook also has quite a few toast-related functions, which should also be exposed by our custom hook. This PR also adds the relevant hook functions into our custom hooks.
A new story has been added for markdown usage in toasts

feat(react): allow markdown usage, other useToast functions in toasts

---

frontend/package.json

Some Chromatic builds (see #2888, #2891 before the fix commit) are failing due to having dependencies on some shared types and node modules.
This PR fixes that by installing shared dependencies in the Chromatic workflow (by adding installation of shared dependencies in the frontend/postinstall script)

chore: add postinstall step for including shared folder in frontend

---

frontend/src/features/admin-form/common/AdminFormPage.tsx
frontend/src/features/admin-form/settings/SettingsGeneralPage.tsx
frontend/src/features/admin-form/settings/SettingsPage.tsx
frontend/src/features/admin-form/settings/SettingsService.ts
frontend/src/features/admin-form/settings/components/EmailFormSection.tsx
frontend/src/features/admin-form/settings/components/FormDetailsSection.tsx
frontend/src/features/admin-form/settings/components/FormLimitToggle.tsx
frontend/src/features/admin-form/settings/mutations.ts

This PR adds in the last missing feature in the general (sub)page of form settings:
- Update form title
- Form mode (email/storage)
**Features**:
- feat: add update form title mutation and service fn
- add `FormDetailsSection` component for use in `SettingsGeneralPage`
- also update adminform query on settings update so navbar gets updated on settings changes
- update padding of admin subpages to be independent of panel 
Stories should automatically be updated

feat(v2): add ability to update form title in settings

---

frontend/src/features/admin-form/AdminFormBuilderPage.stories.tsx
frontend/src/features/admin-form/AdminFormResponsesPage.stories.tsx
frontend/src/features/admin-form/AdminFormSettingsPage.stories.tsx

Routes set in the MemoryRouter decorator of AdminFormPage stories were incorrect, resulting in the AdminFormNavbar always rendering the Create tab as active.
This PR fixes the story

feat(v2): correct set routes for AdminFormPage stories

---

frontend/src/app/AppRouter.tsx
frontend/src/constants/routes.ts
frontend/src/features/public-form/PublicFormPage.stories.tsx
frontend/src/features/public-form/PublicFormPage.tsx
frontend/src/features/public-form/components/FormStartPage/FormStartPage.stories.tsx
frontend/src/features/public-form/queries.ts

It was impossible to reach the public form page previously as `react-router-dom@6` removed regex path matching, will need to validate inside the route itself
See: https://reactrouter.com/docs/en/v6/upgrading/v5#note-on-route-path-patterns
**Bug Fixes**:
- fix: remove invalid regex route path for public forms

fix(v2): remove invalid regex route path for public forms

---

.github/semantic.yml

This PR adds config for our semantic PR checker github action.
The changes are to only validate titles since we only squash commits, and add ref type for refactor shorthand

chore(ci): add semantic.yml to modify CI behaviour

---

.github/mergify.yml
.github/workflows/ci.yml

Mergify CI stopped auto-approving due to the need of deployment checks introduced in #3120. This PR fixes that, whilst simultaneously fixing the lack of lint and build checks due to the removal of Travis CI in that same PR.
- Details ...
**Features**:
- chore(ci): add lint, build stages to github actions CI workflow 
- chore(ci): update mergify to ignore build_deploy_application, and check for new `build` workflow success instead of `build_deploy_application` workflow that will only be triggered on release branches.

chore(ci): add lint and build stages to GA CI, update mergify CI

---

.github/workflows/deploy-eb.yml

We use git commit messages as the description for our ELB deployment.
AWS has a hard limit of 200 characters, which may exceed when a commit message is longer (like this) and throw an error. This commit attempts to fix that by truncating the commit message if it is longer than 200 characters.

fix(ci/deploy): set truncated description during ELB deployment

---

src/app/utils/field-validation/validators/nricValidator.ts
src/public/modules/forms/base/directives/validate-nric.client.directive.js

Currently, M series FIN/NRIC validation has been implemented but is not being used.
Closes #3155
- Create a NRIC field on a form
- Type in M1234567K (or any other valid M series FIN value), there should be no warning displayed in the browser
- Submit a response to the form with M1234567K as the value in the NRIC field, no error should occur

feat: enable M series FIN validation

---

.github/workflows/ci.yml

Forked PRs (see #2819) seem to not be able to run our Github Action workflows due to missing trigger conditions.
This results in a bad experience for any open source contributors and should be fixed.
This PR adds a new `pull_request_target` workflow trigger to our CI workflow config.
New `pull_request_target` trigger on our `CI` Github workflow.

chore: allow forked PRs to run our github action workflows

---

.github/dependabot.yml

Dependabot has not been running on the `/shared` directory ever since it was shared out. This PR adds that in

chore: enable dependabot for /shared directory

---

frontend/src/components/Tile/Tile.stories.tsx
frontend/src/components/Tile/Tile.tsx
frontend/src/theme/components/Badge.ts
frontend/src/theme/components/Tile.ts

> Cherry picked commits from #3048 into its own smaller PR.
Our Tile and Badge components are not fully compliant with the design. This PR attempts to correct that variance.
- ref: reexport Tile subcomponents in Tile instead their own components
- style(Tile): add default color for tile icon
- style(Tile): simplify styles
- style(Badge): update styles according to design

feat(v2): update Tile and Badge styling to better fit design 

---

.github/workflows/ci.yml

Adding `pull_request_target` didn't work... now trying to add an explicit branch to run PR requests on similar to our CodeQL github action (that runs properly on forked PRs).

chore: attempt adding explicit branch to run PR actions on

---

frontend/src/features/admin-form/settings/SettingsGeneralPage.tsx
frontend/src/features/admin-form/settings/components/CategoryHeader.tsx
frontend/src/features/admin-form/settings/components/FormDetailsSection.tsx
frontend/src/features/admin-form/settings/components/FormStatusToggle.tsx
frontend/src/features/admin-form/settings/components/GeneralTabHeader.tsx
frontend/src/theme/components/Badge.ts

Design updated display of form mode to be shown on a badge beside the first header instead of being nested deeply in a subcategory. This PR updates SettingsGeneralPage to conform to the new design. 
Also fixes some a11y issues in `FormStatusToggle` component
**Features**:
- feat: add and use `GeneralTabHeader` component that displays form mode badge
- feat(FormDetailsSection): remove response mode display from component 
- ref(Badge): use color instead of textColor prop in theme 
**Bug Fixes**:
- fix: add aria-label to form status toggle for better a11y
should be captured in Chromatic snapshot

feat(v2): update form mode display in settings to conform to design

---

frontend/src/app/App.tsx
frontend/src/features/public-form/PublicFormPage.stories.tsx
frontend/src/features/public-form/PublicFormService.ts
frontend/src/features/public-form/components/FormAuth/AuthImageSvgr.tsx
frontend/src/features/public-form/components/FormAuth/FormAuth.tsx
frontend/src/features/public-form/components/FormAuth/index.ts
frontend/src/features/public-form/components/FormFields/FormField.tsx
frontend/src/features/public-form/components/FormFields/FormFields.tsx
frontend/src/features/public-form/components/FormFields/FormFieldsContainer.tsx
frontend/src/features/public-form/components/FormFields/FormFieldsSkeleton.tsx
frontend/src/features/public-form/components/FormStartPage/FormHeader.tsx
frontend/src/features/public-form/components/FormStartPage/FormStartPage.stories.tsx
frontend/src/features/public-form/mutations.ts
frontend/src/features/public-form/queries.ts
frontend/src/mocks/msw/handlers/public-form.ts
frontend/src/templates/Field/FieldContainer.tsx
frontend/src/templates/Field/Section/SectionField.tsx
frontend/src/templates/Field/Section/SectionFieldContainer.tsx

This PR adds the public form log in feature, with a few known issues that are not resolved to be completed in future PRs
Related to #2992
**Features**:
- feat(react-query): disable retry if error code is 404 globally
- feat: add AuthImageSvgr component
- feat: add FormAuth component and business logic to log in/log out
- also center form field div when FormAuth component is shown
- add `usePublicAuthMutations` hook for logging in/out of public forms with spcp/sgid
- ref: add colorTheme prop to all field components
- This will help in the future when we need to theme all (or some) form fields
- ref(SectionField): move dividerColor extrapolation to component and use colorTheme prop instead
- ref: extract all possible field render state into separate components 
**Bug …

feat(v2): add initial public form authentication feature

---

frontend/src/components/Button/Button.tsx
frontend/src/theme/components/Button.ts
frontend/src/theme/components/CloseButton.ts
frontend/src/theme/components/Pagination.ts
frontend/src/theme/components/Tile.ts

This PR goes through a second pass on the Button component to bring it more in line with the design in Figma, such as correcting the textStyle used to be `subhead-1` with the correct font size.
**Features**:
- fix(Button): remove fontWeight from baseProp in theme
- fix(Button): remove auto height styling from Button (this affects loading states with left/right icon, height will be incorrect)
- feat: update Pagination and Tile button height due to this change to preserve prior height styling
- fix(Button): remove Box wrapper from children
Should be captured in Chromatic

feat(design-system): update Button to be closer to design

---

frontend/src/app/AppRouter.tsx
frontend/src/assets/icons/BxsColorFill.tsx
frontend/src/assets/icons/BxsWidget.tsx
frontend/src/components/motion/MotionBox.tsx
frontend/src/components/motion/index.ts
frontend/src/features/admin-form-builder/BuilderContent.tsx
frontend/src/features/admin-form-builder/BuilderDrawer.tsx
frontend/src/features/admin-form-builder/BuilderDrawerContext.tsx
frontend/src/features/admin-form-builder/BuilderSidebar.tsx
frontend/src/features/admin-form-builder/DrawerTabIcon.tsx
frontend/src/features/admin-form-builder/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form-builder/FormBuilderPage.tsx
frontend/src/features/admin-form/AdminFormBuilderPage.stories.tsx

This PR adds the initial layout of the form builder page.
Included is the sidebar tabs, and the drawer that is expanded when the tabs are clicked. No real logic is included for now.
Part of #2792 
- Details ...
**Features**:
- feat: add BuilderDrawerContext for holding builder tab context
- feat: add BuilderSidebar component to show current builder tab state
- feat: add initial FormBuilderPage to render builder page and sidebar
- feat: add MotionBox motion component (for allowing slideout animation of the drawer)
- feat: init BuilderDrawer component to show current builder info
- feat: add BuilderContent and initial FieldRowContainer component
AdminFormBuilderPage stories have been updated to show the …

feat(builder/0): add initial form builder layout

---

frontend/src/components/DatePicker/Calendar/CalendarContext.tsx
frontend/src/components/DatePicker/Calendar/CalendarHeader.tsx
frontend/src/components/DatePicker/Calendar/CalendarPanel.tsx
frontend/src/components/DatePicker/Calendar/DayOfMonth.tsx
frontend/src/components/DatePicker/DatePicker.tsx
frontend/src/components/DatePicker/DateRangeInput.stories.tsx
frontend/src/components/DatePicker/DateRangeInput.tsx
frontend/src/components/DatePicker/DateRangePicker.tsx
frontend/src/components/DatePicker/utils.ts
frontend/src/theme/components/DateInput.ts
frontend/src/theme/components/Input.ts

> This PR builds upon #3185
This PR adds a DateRangePicker component with the appropriate multi-month calendar popover.
Related to #2006 
**Features**:
- render multiple months correctly in multi-cal display
- add DateRangePicker component
- add initial DateRangeInput component
- style: add gradient styling when range is across months 
**Bug Fixes**:
- fix: prevent spacebar from opening native date picker
New DateRangeInput stories have been added
SORRY

feat(v2): [Date1] add DateRangePicker/Input component

---

frontend/package-lock.json
frontend/package.json
frontend/src/features/admin-form-builder/BuilderContent.tsx
frontend/src/features/admin-form-builder/BuilderDrawer.tsx
frontend/src/features/admin-form-builder/BuilderDrawerContext.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditHeader.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/FormFieldDrawerActions.tsx
frontend/src/features/admin-form-builder/FieldRow/BuilderDrawerCloseButton.tsx
frontend/src/features/admin-form-builder/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form-builder/FieldRow/SectionFieldRow.tsx
frontend/src/features/admin-form-builder/FormBuilderPage.tsx
frontend/src/features/admin-form-builder/UpdateFormFieldService.ts
frontend/src/features/admin-form-builder/editFieldStore.ts
frontend/src/features/admin-form-builder/mutations.ts
frontend/src/features/admin-form-builder/utils.ts
frontend/src/templates/Field/Section/SectionField.tsx

This PR adds logic for allowing of real time (but debounced) preview on the field when it is being edited.
Part of #2792 
**Features**:
- feat: add editFieldStore to manipulate currently edited fields
- feat: add updateSingleFormField service function and mutations
- feat: add BuilderDrawerCloseButton to handle closing of builder drawer
- feat: add EditHeader (and container) component for edit example
- feat: add initial renderer for SectionField preview
- feat(BuilderDrawer): use EditFieldDrawer component
- feat: extract edit form field actions to FormFieldDrawerActions
- ref(BuilderDrawerContext): move clear active field logic into context
**Bug Fixes**:
- fix(SectionField): use whiteSpace=break-spaces …

feat(builder/1): add initial field preview (only SectionField) when editing field in form builder 

---

frontend/src/components/Toggle/Toggle.tsx
frontend/src/components/Toggle/index.ts
frontend/src/features/admin-form-builder/BuilderContent.tsx
frontend/src/features/admin-form-builder/BuilderDrawer.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/DrawerContentContainer.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditCheckbox.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditHeader.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/FormFieldDrawerActions.tsx
frontend/src/features/admin-form-builder/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form-builder/editFieldStore.ts
frontend/src/templates/Field/Checkbox/index.ts
frontend/src/theme/components/Tabs.ts

This PR is similar to #3130, but with a more involved CheckboxField example for future engineers (and me) to refer to.
Part of #2792
**Features**:
- feat: add EditCheckbox component to render drawer content
- feat: add DrawerContentContainer for consistent field drawer padding
- feat(Tabs): remove excess margin from first and last tab child
- feat: update layout of EditFieldDrawer to allow sticky save button
- feat: clear active field on component unmount
**Bug Fixes**:
- fix: use extend (shallow merge) instead of merge when updating field
- it was causing removing options to be wonky, and we don't have deep nested objects anyways
None... Will add :(

feat(builder/2): add checkbox field preview when editing field in form builder

---

frontend/src/features/admin-form-builder/BuilderContent.tsx
frontend/src/features/admin-form-builder/BuilderContentPlaceholder.tsx
frontend/src/features/admin-form-builder/BuilderDrawer.tsx
frontend/src/features/admin-form-builder/BuilderDrawerContext.tsx
frontend/src/features/admin-form-builder/CreateFieldDrawer/CreateFieldDrawer.tsx
frontend/src/features/admin-form-builder/CreateFieldDrawer/CreateFieldOption.tsx
frontend/src/features/admin-form-builder/CreateFieldDrawer/constants.ts
frontend/src/features/admin-form-builder/CreateFieldDrawer/index.ts
frontend/src/features/admin-form-builder/EditFieldDrawer/EditCheckbox.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/EditHeader.tsx
frontend/src/features/admin-form-builder/EditFieldDrawer/FormFieldDrawerActions.tsx
frontend/src/features/admin-form-builder/FieldRow/BuilderDrawerCloseButton.tsx
frontend/src/features/admin-form-builder/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form-builder/FormBuilderPage.tsx
frontend/src/features/admin-form-builder/UpdateFormFieldService.ts
frontend/src/features/admin-form-builder/constants.ts
frontend/src/features/admin-form-builder/editFieldStore.ts
frontend/src/features/admin-form-builder/mutations.ts
frontend/src/features/admin-form-builder/types.ts
frontend/src/features/admin-form-builder/useBuilderFormFields.ts
frontend/src/features/admin-form-builder/utils.ts
frontend/src/features/admin-form/common/queries.ts
frontend/tsconfig.json
shared/utils/immutable-array-fns.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/types/form.ts

This PR adds form field creation feature into the form builder. In addition, the create form field server API has been extended to accept a positional argument to facilitate this new feature. The API is backwards compatible as the new positional argument is optional.
Related to #3132 
Closes #1847, #3133
- New API for positional create. If rolled back, new created form fields will be set to the end of the form field array
**Features**:
- feat: render drawer contents according to drawer tab state
- feat: add copy-on-drag create form field behaviour in CreateFieldDrawer
- feat: set up logic and styling for drag and drop placeholder
- feat: extract BuilderContentPlaceholder component for different …

feat(builder/4): add form field creation feature in form builder, extend create field API with positional arg

---

secrets-check.sh

Fix for https://github.com/opengovsg/FormSG/issues/3283

ci: update secrets-check.sh

---

src/app/modules/submission/email-submission/__tests__/email-submission.receiver.spec.ts
src/app/modules/submission/email-submission/email-submission.receiver.ts
tests/unit/backend/resources/utf8-with-endash – test.txt

This PR fixes the file names being double/wrongly encoded when outside of latin1 encoding.
Closes #3299, since we didn't have to downgrade after all
Relevant issue where this change was suggested https://github.com/mscdex/busboy/issues/274
- Add unit test for verifying utf8 files are not being encoded wrongly
Also tested on staging

fix: correct busboy filename extraction when utf8 filenames are used

---

secrets-check.sh

- Fixes a typo in the secret check regex introduced in #3287 (additional caret `^` led to wrong patterns being matched)
Reference: Regex can be found here: https://aws.amazon.com/blogs/security/a-safer-way-to-distribute-aws-credentials-to-ec2/
Access Key ID: AKIAIOSFODNN7EXAMPLE
Secret Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

chore: fix secrets check

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/DatePicker/Calendar/CalendarHeader.tsx
frontend/src/components/DatePicker/Calendar/CalendarPanel.tsx
frontend/src/components/DatePicker/Calendar/CalendarTodayButton.tsx
frontend/src/components/DatePicker/DateInput.tsx
frontend/src/components/DatePicker/DateRangeInput.tsx
frontend/src/components/DatePicker/utils.ts
frontend/src/theme/components/DateInput.ts
frontend/src/theme/index.ts

> Note that this PR builds on #3199 
This PR adds the missing a11y alerts/tab indices to the DatePicker components
Closes #2006 
**Features**:
- feat: add aria labels wherever necessary for elaboration
- feat: add correct tabbing pattern outlined in design
- feat: use IconButton for calendar popover close
- feat: use table instead of grid for more semantic a11y
- style: add global reset styles
**Bug Fixes**:
- fix: remove extra margin due to wrap in CalendarPanel
Stories should be automatically updated
- `react-focus-lock`: lock focus inside calendar

feat(v2): [Date2] add a11y improvements to DatePicker components

---

src/app/modules/form/public-form/public-form.controller.ts
src/app/modules/myinfo/myinfo.controller.ts
src/app/modules/myinfo/myinfo.service.ts
src/app/modules/myinfo/myinfo.types.ts
src/app/modules/myinfo/myinfo.util.ts

Adds the relevant routes to pass relayState through to MyInfo forms.
Closes #3183 
Added handling for `encodedQuery` into the MyInfo controllers.
**Features**:
- Adds support for prefilled text for MyInfo forms.
Create a MyInfo form with a pre-fill textbox and ensure that the pre-fill text is carried over when the user logs in.

feat: pre-fill to support myinfo forms

---

frontend/.eslintrc

TOO DAMN ANNOYING
TODOs in the future could be to only be an error during a precommit hook (to prevent commits if there are unused vars). This could still allow for a faster and more experimental local developer experience without adding unused variables during review.

chore(v2/eslint): update unused vars rule to warn instead of error

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/modules/webhook/__tests__/webhook.validation.spec.ts
src/app/modules/webhook/webhook.validation.ts
src/public/modules/forms/admin/controllers/delete-form-modal.client.controller.js
src/public/services/UpdateFormService.ts

- Webhook url validation is done as part of the form model. This includes form archiving. As described in #3380, this means that if the webhook URL is invalid (i.e. DNS resolution fails), the document update cannot be saved - this is expected behavior
- However, for form archiving failure, previously the errors were not correctly mapped, resulting in a default `500` being returned from the server (instead of `422` in this case). The frontend also failed silently without any prompt to the admin
Closes #3380
- I considered if we should simply skip model validation for DELETE form endpoint. However, Delete does not remove the document permanently, it simply updates the `status` field, and the form could be revived in future. Therefore, model validation should continue to be applied as this …

fix: DNS resolution error causes 5xx on form deletion

---

frontend/src/components/DatePicker/Calendar/CalendarHeader.tsx

This PR changes an accidental esm import of date-fns to use the non-esm variant

fix(v2/CalendarHeader): use non-esm variant of date-fns function

---

README.md
src/app/modules/auth/__tests__/auth.controller.spec.ts
src/app/modules/auth/auth.controller.ts
src/app/modules/auth/auth.middlewares.ts
src/app/modules/auth/auth.routes.ts
src/app/modules/billing/__tests__/billing.controller.spec.ts
src/app/modules/billing/billing.controller.ts
src/app/modules/billing/billing.middlewares.ts
src/app/modules/billing/billing.routes.ts
src/app/modules/examples/__tests__/examples.controller.spec.ts
src/app/modules/examples/examples.controller.ts
src/app/modules/examples/examples.middlewares.ts
src/app/modules/examples/examples.routes.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.middlewares.ts
src/app/modules/frontend/__tests__/frontend.controller.spec.ts
src/app/modules/frontend/frontend.controller.ts
src/app/modules/frontend/frontend.middlewares.ts
src/app/modules/frontend/frontend.routes.ts
src/app/modules/user/__tests__/user.controller.spec.ts
src/app/modules/user/user.controller.ts
src/app/modules/user/user.middleware.ts
src/app/modules/user/user.routes.ts
src/app/routes/api/v3/admin/forms/admin-forms.settings.routes.ts
src/app/routes/api/v3/auth/auth.routes.ts
src/app/routes/api/v3/billings/billings.routes.ts
src/app/routes/api/v3/client/client.routes.ts
src/app/routes/api/v3/user/user.routes.ts

This PR is a copy of #2819. Reopening to trigger CI/CD 
Prevent developers from forgetting the use of validators when using a controller handler.
Closes #1642 
As suggested in the issue, put the original handler with a validation middleware in an array, and expose the final array for usage rather than the original handler
- Details ...
- Details ...
Ran a regression test using `npm run test-backend`, and ran happy-path testing locally with the changed routes

refactor: use combined route validators and handlers

---

docs/MONGODB.md

Product ops has to spend time manually archiving multiple forms.
Add a function to archive an array of strings containing form IDs. Note that this function is nearly identical to `unlistFormArrayFromExamples` which already exists in the docs. Only the update query is different.
Tested on staging:

feat: add script to archive multiple forms

---

frontend/src/features/admin-form/create/builder-and-design/utils.ts

Small refactor to reuse `FIELDS_TO_CREATE_META` instead of hardcoding new strings for the create and edit field drawer titles.

refactor: use FIELDS_TO_CREATE_META for create, edit title

---

README.md
package-lock.json
package.json

README documentation is not updated for Apple Silicon Macs on Mac OS Monterey for the v2 branch.
Update README file in the FormV2 branch for Mac OS Monterey and Apple Silicon. Also updates the `nan` package to 2.15 to resolve a build error on Apple Silicon.

chore: Update README file for Mac OS Monterey and Apple Silicon Macs

---

frontend/src/features/admin-form/create/builder-and-design/components/BuilderAndDesignDrawer/CreateFieldDrawer/CreateFieldDrawer.tsx

Currently, fields in the field creation drawer are disabled only as long as the admin form is still loading. This means that if there is an error while loading the admin form, the fields can be dragged. We should only let the form be editable if it has already loaded successfully.

feat: disable field creation on useAdminForm error

---

.github/workflows/deploy-eb.yml

Elastic Beanstalk application versions have a character limit of 200 for descriptions. Our deploy pipeline contains a line to grab the latest commit message and truncate it to 180 characters (#3147) but it uses the `cut` command which only cuts the specified number of bytes for each line. This means there can still be [deploy failures](https://github.com/opengovsg/FormSG/runs/5353731644?check_suite_focus=true) if the total number of characters across lines exceeds 200.
Change to `head -c 180` which gets the first 180 characters from the specified text.

fix(ci/deploy): truncate deploy description to 180 chars

---

src/app/models/__tests__/form.server.model.spec.ts
src/app/models/form.server.model.ts
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.service.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/modules/form/admin-form/admin-form.service.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.form.routes.spec.ts
src/types/form.ts

This PR adds a positional argument to create form field API at `POST /form/:formId/fields`, to allow for drag and drop field creation feature coming in React.
Part of #3472
Closes #1841
- Positional argument is optional; if not given will default to insertion at end of form field array.
**Features**:
- feat(Form): allow optional positional arg for inserting form field 
No changes in client -- will continue to call API without positional argument. Positional argument will be used in the React variant.
Tests have been added for this new feature. 
New unit tests have been added to 
- admin.form.service.spec
- admin-form.controller.spec
- form.server.model
New integration tests have been added to
- admin-forms.form.routes.spec

feat: add positional argument to create form field API 

---

shared/types/core.ts
src/app/modules/frontend/frontend.controller.ts
src/app/modules/frontend/frontend.routes.ts
src/app/modules/frontend/frontend.service.ts
src/app/routes/api/v3/client/client.routes.ts

Part of #3472, this PR adds a new API route `/api/v3/client/env` for returning client env vars as a JSON object instead of the current `/environment` route where a Javascript script is returned.
To be used in the React app.

feat: add `/client/env` API route for sending client env vars as JSON

---

frontend/src/features/admin-form/AdminFormCreatePage.stories.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent.tsx
frontend/src/features/admin-form/create/builder-and-design/components/BuilderAndDesignPlaceholder/BuilderAndDesignPlaceholder.tsx
frontend/src/features/admin-form/create/builder-and-design/components/BuilderAndDesignPlaceholder/EmptyFormPlaceholder.tsx
frontend/src/features/admin-form/create/builder-and-design/components/BuilderAndDesignPlaceholder/index.ts
frontend/src/features/admin-form/create/builder-and-design/components/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form/create/builder-and-design/utils.ts
frontend/src/mocks/msw/handlers/admin-form/form.ts

Currently the form builder renders an empty page when the form has no fields. This PR adds the placeholder for fields to be dragged in when the form is empty:
Moreover, previously, background colour of existing fields would change to `neutral.100` when a new field was being dragged over, even though they are not responsive to new fields being dropped over them. This is inconsistent with the [design system](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2584%3A107188). This PR fixes the issue by preventing the background colour of existing fields from changing when new fields are being dragged over.
- Mocks added for POST request to create field and PUT request to update field
These will be fixed in a future PR:
- After creating a new field, the `onSuccess` …

feat(v2): create droppable empty form placeholder

---

shared/constants/form.ts
shared/types/form/form.ts
shared/types/user.ts
shared/utils/file-validation.ts
src/app/modules/user/__tests__/user.controller.spec.ts
src/app/modules/user/__tests__/user.routes.spec.ts
src/app/modules/user/user.controller.ts
src/app/modules/user/user.utils.ts
src/app/routes/api/v3/user/__tests__/user.routes.spec.ts

This PR is part of #3472, where types that can be shared with client/server are exported.
In addition, update user route's `InvalidOtpError` to return `404` instead of `401` status code, due to React app logging user out automatically when 401 is retrieved.
Also also updates the fields SettingsDto returns to:
- Include `responseMode` in returned JSON
- include `publicKey` field in storage mode forms

feat: export shared types for use in client/backend, update user route error to return new status code, update SettingsDto return

---

frontend/src/components/Dropdown/MultiSelect/MultiSelectProvider.tsx
frontend/src/components/Dropdown/MultiSelect/index.ts
frontend/src/components/Dropdown/SelectContext.tsx
frontend/src/components/Dropdown/SingleSelect/SingleSelect.stories.tsx
frontend/src/components/Dropdown/SingleSelect/SingleSelectProvider.tsx
frontend/src/components/Dropdown/components/MultiSelectItem/MultiSelectItem.tsx
frontend/src/components/Dropdown/components/SelectCombobox/ComboboxClearButton.tsx
frontend/src/components/Dropdown/index.ts
frontend/src/theme/components/MultiSelect.ts

This PR cherry picks a bunch of `SingleSelect`/`MultiSelect` fixes that were encountered whilst working on #3556.
**Features**:
- feat(Select): allow setting of empty placeholder
- feat(MultiSelectItem): show icon in tag if it exists
**Bug Fixes**:
- fix(ComboboxClearButton): show active state if item has been selected
- Previously, the clear button will remain in inactive styling even if item has been selected
- fix(Single/MultiSelectProvider)!: allow control of selectedItem, refilter items whenever `items` prop changes
- Instead of using `initialSelectedItem` prop, allow users of the component to pass in current value for selection.
- fix(SingleSelectProvider): use label string as aria-live announcement 
- the value was used previously, which may cause screenreaders to read something …

fix(v2/Dropdown): allow controlled selectedItems, render icon in MultiSelectItem

---

frontend/src/features/public-form/PublicFormProvider.tsx
frontend/src/features/public-form/components/FormFields/FormSectionsContext.tsx
frontend/src/features/public-form/queries.ts

As originally raised by @mantariksh in https://github.com/opengovsg/FormSG/pull/3457#discussion_r816424658, we should not refresh the public form when the server state has changed. This may cause users to lose their currently filled in form fields. Instead, we should display a warning that form state has changed and the submission may fail due to such changes.
This PR implements that warning and prevents server side form changes from refreshing the current loaded form. 
This is done by storing the initially fetched form and never changing it, whilst displaying a toast if the newly fetched form does change.
The current methodology does a deep comparison between the current "cached" form and the form retrieved from the server, which may be inefficient. I don't think it will negatively …

feat(v2): warn public form filler when form has changed on server-side

---

frontend/src/features/admin-form/create/common/CreatePageSidebarContext/CreatePageSidebarContext.tsx

Previously, when the builder drawer was closed, clicking on a
form field would open the drawer to the field list instead of
directly to the editing page for that field. This was because
of a useEffect which set fields to inactive whenever the active
tab changed.
Instead, we want to set the fields to inactive only when the active
tab is not the builder.
Check that the currently active tab isn't the Build tab before setting
fields to inactive.

fix: ensure clicking field opens to field editor

---

frontend/src/features/admin-form/common/AdminViewFormService.ts
frontend/src/features/public-form/PublicFormProvider.tsx
frontend/src/features/public-form/PublicFormService.ts
frontend/src/features/public-form/components/FormFields/FieldFactory.tsx
frontend/src/features/verifiable-fields/VerifiableFieldService.ts
frontend/src/mocks/msw/handlers/public-form.ts
frontend/src/services/ApiService.ts
frontend/src/templates/Field/FieldContainer.tsx
frontend/src/typings/core.ts
frontend/src/utils/date.ts

Dates get automatically serialized into strings (e.g. `JSON.stringify(new Date())` => ` '"2022-03-14T09:05:44.694Z"'`) when crossing the server-client divide.
~~This PR re-serializes all strings into Date objects on the client when such requests are intercepted by our `ApiService` using `axios`. This maintains type parity in the shared types and reduces the need to re-convert all ISO strings into Dates before using them.~~
This issue was found when the rendered `DateField` in public forms was working improperly due to passing a stringified ISO date into `date-fns` functions. This means that DTO types were actually not 100% correct; all `Date` types should be some serialized string `JsonDate` type instead. However, this PR will convert those serialized dates at the source where DTOs hit …

feat(v2/date): correct transform ISO strings in DTOs to Date objects in certain APIs

---

frontend/package-lock.json
frontend/package.json
frontend/src/features/admin-form/settings/components/EmailFormSection.tsx
frontend/src/features/public-form/components/FormFields/FieldFactory.tsx
frontend/src/features/verifiable-fields/Email/VerifiableEmailField.stories.tsx
frontend/src/features/verifiable-fields/Mobile/VerifiableMobileField.stories.tsx
frontend/src/templates/Field/Attachment/AttachmentField.stories.tsx
frontend/src/templates/Field/Checkbox/CheckboxField.stories.tsx
frontend/src/templates/Field/Checkbox/CheckboxField.tsx
frontend/src/templates/Field/Date/DateField.stories.tsx
frontend/src/templates/Field/Decimal/DecimalField.stories.tsx
frontend/src/templates/Field/Dropdown/DropdownField.stories.tsx
frontend/src/templates/Field/Email/EmailField.stories.tsx
frontend/src/templates/Field/FieldContainer.tsx
frontend/src/templates/Field/HomeNo/HomeNoField.stories.tsx
frontend/src/templates/Field/LongText/LongTextField.stories.tsx
frontend/src/templates/Field/Mobile/MobileField.stories.tsx
frontend/src/templates/Field/Nric/NricField.stories.tsx
frontend/src/templates/Field/Number/NumberField.stories.tsx
frontend/src/templates/Field/Radio/RadioField.stories.tsx
frontend/src/templates/Field/Radio/RadioField.tsx
frontend/src/templates/Field/ShortText/ShortTextField.stories.tsx
frontend/src/templates/Field/Table/ColumnCell.tsx
frontend/src/templates/Field/Table/TableField.stories.tsx
frontend/src/templates/Field/Table/TableFieldContainer.tsx
frontend/src/templates/Field/Uen/UenField.stories.tsx
frontend/src/utils/fieldValidation.ts

Perf was HORRENDOUS due to global formState mutating on literally every single error, causing each keystroke to render every single field again.
This PR updates the performance by only monitoring a subslice of the form state, so each field does not rerender from other field changes.
Also adds rendering for Dropdown and Date fields in public form view, must have been removed again due to merge conflicts.
See the comparison videos below for the massive responsiveness boost.
- perf: use `useFormState` and `useWatch` over contextual counterparts
- perf: remove `dep` in validation, only trigger on OtherCheckbox/OtherRadio option change
**Bug Fixes**:
- fix(checkboxValidation): do not run length validation if empty value
**BEFORE**:
**AFTER**:
Should have no changes in tests …

perf(v2): massively optimize public form filling responsiveness

---

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/BuilderAndDesignContent.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/BuilderAndDesignDrawer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditCheckbox.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditHeader.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/common/DrawerContentContainer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/common/types.ts
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/common/useEditFieldForm.ts
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/common/utils.ts
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/index.ts

This PR reimplements the checkbox field editor originally implemented in #3131, with the refactors from #3547 included. There are a few significant differences from the original implementation:
- The design of the checkbox editor has changed from two tabs to a single tab containing all the fields.
- The original `ValidationOptions` validation did not allow one of `customMin` or `customMax` to be set without setting the other. This PR fixes this.
1. ~When the sidebar drawer is closed, clicking on a field results in the drawer opening to the field list, rather than directly to the editing page for that field. This will be addressed separately.~ fixed in #3583 
Field duplication and deletion will be implemented together with the relevant mocks before submitting the form builder for design …

feat(v2): edit checkbox field in form builder

---

frontend/src/features/admin-form/AdminFormCreatePage.stories.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form/create/builder-and-design/UpdateFormFieldService.ts
frontend/src/features/admin-form/create/builder-and-design/mutations/useCreateFormField.ts
frontend/src/features/admin-form/create/builder-and-design/mutations/useDeleteFormField.ts
frontend/src/features/admin-form/create/builder-and-design/mutations/useDuplicateFormField.ts
frontend/src/features/admin-form/create/builder-and-design/mutations/useEditFormField.ts
frontend/src/mocks/msw/handlers/admin-form/form.ts

Field deletion and duplication buttons currently don't do anything, and the `BiCog` icon to set the field to inactive is missing.
- Add `BiCog` icon which sets field to inactive
- Add duplication and deletion functionality

feat(v2): add field deletion, duplication, set inactive functionality

---

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditNric.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditUen.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditYesNo.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/index.ts
frontend/src/features/admin-form/create/builder-and-design/utils/fieldCreation.ts

Adds edit drawers for Yes/No, NRIC and UEN fields. These fields were all done at the same time as they require no additional configuration other than setting the "Required" toggle, so the UI is exactly the same for all 3.
I chose to copy-paste the code instead of having a common component for all 3 as this allows the types to be tighter, i.e. tied to each `fieldType`. 
Depends on #3581

feat(v2): add editors for Yes/No, NRIC, UEN

---

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditRadio.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/index.ts
frontend/src/features/admin-form/create/builder-and-design/utils/fieldCreation.ts

Part of #2792
Closes #3409 
**Features**:
- feat: add EditRadio component to render drawer content
**Bug Fixes**:
- fixed drawer width which did not resize when screen was smaller

feat(builder): add radio field preview when editing field in form builder

---

package.json

it stopped watching, not sure when (since we did not have to touch backend for a while), but adding the flag makes it work again.
Might want to do the same for the `develop` branch.

chore(v2/package.json): add --poll to tsnd so backend changes are watched

---

frontend/src/features/admin-form/create/CreatePage.tsx

This PR fixes bug where create page's mobile view would not render content due to having the wrong flex direction

fix(v2/CreatePage): use column flex in mobile view so content renders

---

frontend/package-lock.json
frontend/package.json
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/useBuilderFields.ts
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/EditFieldDrawer.tsx
frontend/src/features/public-form/components/FormFields/FieldFactory.tsx
frontend/src/features/public-form/components/FormFields/FormFields.tsx
frontend/src/mocks/msw/handlers/admin-form/form.ts
frontend/src/templates/Field/Table/ColumnCell.tsx
frontend/src/templates/Field/Table/TableField.tsx
shared/types/field/index.ts
shared/types/field/tableField.ts

Previously, `TableFieldDto` was equivalent to `FormWithWithId<TableFieldBase>`, which only added the `_id` prop to table fields. However, `TableField#columns` was also a schema with an `_id`, which was not augmented by `FormFieldWithId<F>`.
> We technically had a hint of type incompatibility when I had to cast `FormFieldWithId<TableFieldBase>` with a new schema type. Just fixing it here now.
This PR updates `TableFieldDto` to include `column#_id`. Whilst doing so, `useBuilderFields` had to be updated to create a temporary object with column `_id`s populated  when attempting to create a new table field. This is done using `cuid`.
**Bug Fixes**:
- fix: update FormFieldWithId type to assign id to TableField columns
- add cuid package to generate collision resistant ids for table field column …

fix(v2/shared): update type shape for TableFieldDto

---

frontend/src/features/admin-form/create/logic/CreatePageLogicTab.stories.tsx
frontend/src/features/admin-form/create/logic/FormLogicService.ts
frontend/src/features/admin-form/create/logic/components/DeleteLogicModal/DeleteLogicModal.tsx
frontend/src/features/admin-form/create/logic/components/DeleteLogicModal/index.ts
frontend/src/features/admin-form/create/logic/components/LogicContent/LogicBlock/LogicBlock.tsx
frontend/src/features/admin-form/create/logic/mutations.ts
frontend/src/mocks/msw/handlers/admin-form/form.ts

This PR implements the delete logic feature.
Tracked by #3365
**Features**:
- feat: add and open DeleteLogicModal on delete icon button click
- feat: implement delete logic feature
msw mock for deleting of logic has been added. Should be able to test deletion of logic.

feat(v2): implement admin form delete logic feature

---

frontend/src/features/public-form/PublicFormContext.tsx
frontend/src/features/public-form/PublicFormPage.tsx
frontend/src/features/public-form/PublicFormProvider.tsx
frontend/src/features/public-form/components/FormFields/FormFieldsContainer.tsx
frontend/src/features/public-form/components/FormFields/SectionSidebar.tsx
frontend/src/features/public-form/components/FormFooter/FormFooter.tsx
frontend/src/features/public-form/components/FormFooter/index.ts

This PR adds the missing form footer in public form pages. Prerequisite for captcha PR.
**Features**:
- add and render FormFooter component in PublicFormPage component
- feat: remove minimum widths on left spacer when displaying form if there are no section fields
- It was causing form display to be lopsided when there are no sections to jump to
- feat: pass down formBgColor prop from PublicFormContext
- so it can be reused by form footer too
**Known issues**:
Links to Terms of Use and Privacy Policy does not work yet. Will be in a separate PR.
EDIT: Now tracked in #3656  and #3657 
PublicFormPage should now display form footer.

feat(v2): add and render form footer in PublicFormPage

---

frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignContent/FieldRow/FieldRowContainer.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListOption.tsx

Currently, fields can only be added through drag and drop. We also want users to be able to simply click on fields to append them to the end of the form.
Implement field creation on click, and also scroll the new field into view when it is created.

feat: append new field to form on click

---

docker-compose.yml

[maildev](https://hub.docker.com/r/maildev/maildev) has released a new docker image on 2022-03-30, which changed the internal app ports.
The smtp server now runs on port 1025 (was 25), the web interface runs in port 1080 (was 80). This was done on purpose in [this PR](https://github.com/maildev/maildev/pull/281).
This change in port causes the docker setup for FormSG to break since the app can't connect to the mail server, and so the ports need to be updated.
Update both the web app and smtp port for maildev.
The PR targets branch `develop`, and we can merge `develop` into `form-v2/develop` later.

fix: update ports for maildev to 1080 and 1025

---

frontend/src/components/DatePicker/DateInput.tsx
frontend/src/components/Dropdown/SingleSelect/SingleSelectProvider.tsx
frontend/src/components/Dropdown/components/SelectCombobox/ComboboxClearButton.tsx
frontend/src/components/Dropdown/components/SelectCombobox/SelectCombobox.tsx
frontend/src/components/Dropdown/components/SelectCombobox/ToggleChevron.tsx
frontend/src/features/myinfo/utils/augmentWithMyInfo.ts
frontend/src/features/public-form/components/FormFields/FormFields.tsx
shared/types/field/index.ts

> Builds upon the ever growing chain of PRs related to submission epic tracked by https://github.com/opengovsg/FormSG/issues/3570.
> Note that I am unable to test this without mocking API shapes yet due to hardcoded MyInfo routes, and I have not updated the redirect URLs to go back to the React application.
> Code has been tested with `msw` mocks where the expected MyInfo prefilled shapes are returned.
This PR prefills form fields with values retrieved from MyInfo when server returns us fields with pre-filled values.
Also fixed a bug where Date and Dropdown fields were not correctly disabled when field itself is marked as disabled.
Closes #3602.
**Features**:
- feat(myinfo): add augmentWithMyInfo fn to inject MyInfo field options
- feat(FormFields): augment form …

feat(v2/submit-8): add prefilling of data when user logs in with MyInfo on public forms

---

frontend/src/features/admin-form/create/CreatePage.tsx
frontend/src/features/admin-form/create/logic/components/LogicContent/LogicBlock/FieldLogicBadge.tsx
frontend/src/features/admin-form/create/logic/hooks/useAdminFormLogic.ts
frontend/src/features/admin-form/create/logic/types.ts
frontend/src/features/form/types.ts
frontend/src/features/form/utils/augmentWithQuestionNo.ts
frontend/src/features/form/utils/index.ts
frontend/src/features/public-form/components/FormFields/FieldFactory.tsx
frontend/src/features/public-form/components/FormFields/VisibleFormFields.tsx
frontend/src/features/verifiable-fields/components/VerifiableFieldContainer/VerifiableFieldContainer.tsx
frontend/src/templates/Field/Attachment/AttachmentField.tsx
frontend/src/templates/Field/Checkbox/CheckboxField.tsx
frontend/src/templates/Field/Date/DateField.tsx
frontend/src/templates/Field/Decimal/DecimalField.tsx
frontend/src/templates/Field/Dropdown/DropdownField.tsx
frontend/src/templates/Field/Email/EmailField.tsx
frontend/src/templates/Field/FieldContainer.tsx
frontend/src/templates/Field/HomeNo/HomeNoField.tsx
frontend/src/templates/Field/LongText/LongTextField.tsx
frontend/src/templates/Field/Nric/NricField.tsx
frontend/src/templates/Field/Number/NumberField.tsx
frontend/src/templates/Field/Radio/RadioField.tsx
frontend/src/templates/Field/Rating/RatingField.tsx
frontend/src/templates/Field/ShortText/ShortTextField.tsx
frontend/src/templates/Field/Table/TableField.tsx
frontend/src/templates/Field/Table/TableFieldContainer.tsx
frontend/src/templates/Field/Uen/UenField.tsx
frontend/src/templates/Field/YesNo/YesNoField.tsx
frontend/src/templates/Field/types.ts

> This chain is getting long... Sorzzz
This PR adds question numbers to form fields that can take in a response. The only fields that do not have question numbers are the Image, Section, and Statement fields.
**Features**:
- feat: extract augmentWithQuestionNo function
- feat: use FormFieldWithQuestionNo type across form render components
- feat(FormFields): render question number in form fields
**Bug Fixes**:
- fix(logic/hooks): correctly augment logic field's question number
- Was assigning question numbers to every single field, even those that do not actually accept a response
Public form fields should now show a question number if the field accepts inputs.

feat(v2/submit-6): show question numbers in public form fields

---

frontend/src/components/DatePicker/DateInput.tsx
frontend/src/components/Dropdown/SingleSelect/SingleSelectProvider.tsx
frontend/src/components/Dropdown/components/SelectCombobox/ComboboxClearButton.tsx
frontend/src/components/Dropdown/components/SelectCombobox/SelectCombobox.tsx
frontend/src/components/Dropdown/components/SelectCombobox/ToggleChevron.tsx
frontend/src/features/myinfo/utils/augmentWithMyInfo.ts
frontend/src/features/public-form/PublicFormContext.tsx
frontend/src/features/public-form/PublicFormPage.stories.tsx
frontend/src/features/public-form/PublicFormPage.tsx
frontend/src/features/public-form/PublicFormProvider.tsx
frontend/src/features/public-form/components/FormFields/FormFields.tsx
frontend/src/features/public-form/components/FormFields/FormFieldsContainer.tsx
frontend/src/features/public-form/components/FormFields/SectionSidebar.tsx
frontend/src/features/public-form/components/FormFooter/FormFooter.tsx
frontend/src/features/public-form/components/FormFooter/index.ts
frontend/src/features/recaptcha/useRecaptcha.tsx
frontend/src/hooks/useScript.ts
frontend/src/mocks/msw/handlers/env.ts
frontend/src/mocks/msw/handlers/public-form.ts
shared/types/field/index.ts

> Builds upon the ever growing chain of PRs related to submission epic tracked by #3570.
This PR adds reCAPTCHA support in public form submissions. 
**We are still using reCAPTCHA v2 instead of v3** since mo' version doesn't mean mo' better -- v2 validation returns a true/false score whilst v3 returns a continuous value for us to take action. v3 will require server changes and I don't think we need the supposed benefits v3 gives us (variable range of actions instead of true/false).
Closes #3434 
**Features**:
- feat: add useRecaptcha custom hook
- feat: set up recaptcha in PublicFormProvider and render recaptcha container in FormFooter
- feat: retrieve captcha response from captcha before submitting
- feat: pass down formBgColor prop from …

feat(v2/submit-7): add reCAPTCHA support in public form submissions

---

.github/workflows/chromatic.yml

Chromatic is detecting package-lock changes and rerunning every single test instead of only running snapshot tests for changed stories due to `npm install` using `npm@7`, resulting in diffs between the lockfileVersion of the repository's package-lock.json and the resulting package-lock.json in the workflow, triggering Turbosnap.
This is causing the costs to balloon with every push. This PR adds a node version setting step to the workflow (to v14) so npm@6 is used to prevent any unnecessary lockfileVersion changes.

feat(ci/chromatic): fix node to v14 for turbosnap to work correctly

---

frontend/src/hooks/useToast.ts

The ChakraUI `Toast` component had a bug on larger screens where they will pop up off-center if the width of the screen is too much. This has been fixed upstream in https://github.com/chakra-ui/chakra-ui/pull/4922 and now fixed for the usage in this app

fix(v2): centre toasts used in app

---

frontend/src/features/admin-form/common/AdminViewFormService.ts
frontend/src/features/admin-form/common/components/AdminFormNavbar/AdminFormNavbarContainer.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/AddCollaboratorInput.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorList.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorModal.stories.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorModal.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/PermissionDropdown.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/index.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/useCollaboratorModal.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/utils.ts
frontend/src/features/admin-form/common/mutations.ts
frontend/src/features/admin-form/common/queries.ts
frontend/src/mocks/msw/handlers/admin-form/collaborators.ts
frontend/src/mocks/msw/handlers/admin-form/index.ts
frontend/src/mocks/msw/handlers/user.ts
frontend/src/theme/components/Menu.ts
shared/types/form/form.ts

This PR adds the initial admin form collaboration feature, where admins can add/remove collaborators.
Note that there is still no transfer ownership feature, or viewer-only modal. Those will come in later PRs.
Meaning there are no client-side guards if a user with view-only rights attempts to modify collaborator permissions (backend will correctly block the action).
Related to #2487 
**Features**:
- add CollaboratorModal component and stories, and use in admin nav bar
- includes `useCollaboratorModal` hook to control modal open close
- add various skeleton states
New stories in storybook

feat(v2): add admin form collaborator modal

---

frontend/src/features/admin-form/common/AdminViewFormService.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorListScreen/AddCollaboratorInput.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorListScreen/CollaboratorList.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorListScreen/CollaboratorListScreen.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorListScreen/PermissionDropdown.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorListScreen/index.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorModal.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorModalContent.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorWizardContext.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/TransferOwnershipScreen/TransferOwnershipScreen.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/TransferOwnershipScreen/index.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/constants.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/utils.ts
frontend/src/features/admin-form/common/mutations.ts
frontend/src/features/admin-form/common/queries.ts
frontend/src/features/workspace/components/CreateFormModal/CreateFormModalContent/CreateFormModalContent.tsx
frontend/src/templates/MotionBox/MotionBox.tsx
frontend/src/templates/MotionBox/XMotionBox.tsx
frontend/src/templates/MotionBox/index.ts

> Note that this PR builds on top of #3771.
This PR implements the ability for form owners to transfer ownership of their forms.
Same caveats as the base PR apply, no client-side guards if a user with view-only rights attempts to transfer permissions (backend will correctly block the action).
Related to #2487
**Features**:
- feat: add TransferOwnershipScreen component
- feat(PermissionDropdown): only allow transfer owner option if current logged in user is the form owner
- feat: move current modal into CollabatorListScreen so there can be a distinction between transfer ownership and default list view.
- feat: extract MotionBox and XMotionBox template components
- duplicate code, also used in CreateFormModal
- feat(CollaboratorListScreen): add bottom divider and fix …

feat(v2/collab): Add transfer ownership feature

---

frontend/src/features/recaptcha/useRecaptcha.tsx
frontend/src/templates/Field/Checkbox/CheckboxField.tsx

This PR fixes two bugs:
1. When submission fails for any reason, triggering recaptcha again results in an infinite loop. This is due to execute never returning (as the current recaptcha widget has reached the end of its lifecycle).  \
\
This is fixed by resetting the captcha widget prior to every form submission so the execution can go through (and any current response can be discarded)
3. `react-hook-form` has an interesting bug(?) where a single checkbox will not be casted to an array and instead be set directly as the value, even when the input is of a `checkbox` type. Might be due to the values being in yet another nested object. See https://github.com/react-hook-form/react-hook-form/issues/7834#issuecomment-1040735711 \
\
Fixed by adding a hidden secret checkbox with the same name to …

fix(v2): Recaptcha double submission loading loop, single checkbox error bugfixes

---

frontend/src/features/admin-form/common/AdminViewFormService.ts
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorListScreen/CollaboratorList.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorModalContent.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/CollaboratorWizardContext.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/RemoveSelfScreen/RemoveSelfScreen.tsx
frontend/src/features/admin-form/common/components/CollaboratorModal/TransferOwnershipScreen/TransferOwnershipScreen.tsx
frontend/src/features/admin-form/common/mutations.ts

> This PR builds on top of #3793 
This PR adds the ability for form collaborators (not the owners themselves) to removes themselves as a collaborator on the form. 
Related to #2487, will close when this entire chain is merged in.
**Features**:
- feat: add ability to remove self from collaborator list
- style(Collab): use secondary.500 color in collaborator modal text
No new stories, though can be tested in the Viewer-only stories.

feat(v2/collab): allow removal of self from form collaborators

---

src/app/config/datadog-statsd-client.ts
src/app/modules/twilio/twilio.controller.ts
src/app/modules/twilio/twilio.statsd-client.ts
src/app/routes/api/v3/notifications/__tests__/notifications.routes.spec.ts
src/app/services/sms/sms.service.ts
src/types/twilio.ts

We need to be able to diagnose Twilio errors early by having a clear view into Twilio API usage, callbacks, and success/errors in both cases.
Report real time counters of Twilio stats under the metrics:
* `vendor.twilio.sms.send`
* `vendor.twilio.sms.update`
Note that this is a PR for develop to be released to production asap.

feat: track Twilio metrics to DataDog

---

package-lock.json
package.json

We accidentally removed the copyfiles dependency, this PR restores it

fix: restore copyfiles

---

frontend/src/features/admin-form/create/logic/components/LogicContent/EditLogicBlock/EditLogicBlock.tsx

This PR fixes a bug where both `preventSubmitMessage` and the fields to `show` will both be POSTed if the logic types were switched whilst editing the logic.
By unregistering inputs when they are removed from the DOM, the submitted body will be in the expected shape for their respective logic types instead of containing both.
E.g:
```
// Before:
{
"_id": "6278953a0cad35006291e13a",
"conditions": [
{
"ifValueType": "number",
"field": "626022f582ffc90057bfceb0",
"state": "is equals to",
"value": 4
}
],
"logicType": "showFields",
// Note how preventSubmitMessage is still in the object body even though the logicType is LogicType.ShowFields
"preventSubmitMessage": "4 is an inauspicious number", 
"show": [
"626022dc82ffc90057bfce7b"
]
}
```
**Bug Fixes**:
- fix(EditLogicBlock): unregister …

fix(v2/EditLogicBlock): unregister inputs when logic inputs change

---

frontend/public/index.html
frontend/src/app/AppRouter.tsx
frontend/src/app/HashRouterElement.tsx

People may have bookmarked URLS into forms.
Angular JS uses Hash based routing (e.g. path like `/#!/examples`), where the URL hash is NOT sent to the server. 
Because the server doesn't get to see the URL, the frontend needs to be able to identify the old URLs and redirect to the new URL scheme.
For example:
`/#!/:formid/admin` -> `/admin/forms/:formid`
Implement a router in react that will check the hash on the base route and redirect as needed.

feat: handle old style urls in react (redirects)

---

src/app/routes/api/api.routes.ts

We can't have 404s for frontend (since frontends do catch all), but we should have 404s and error reporting for the `/api` namespace.
This PR adds error middlewares to the `/api` namespace explicitely
```bash
$ curl -v https://staging.form.gov.sg/api/foobar
< HTTP/2 404
< date: Tue, 17 May 2022 07:48:04 GMT
< content-type: text/plain; charset=utf-8
< content-length: 9
< cf-ray: 70cabfa7eb4c895c-SIN
< etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
< strict-transport-security: max-age=5184000; includeSubDomains
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< content-security-policy: img-src 'self' data: https://www.googletagmanager.com/ https://www.google-analytics.com/ https://s3-ap-southeast-1.amazonaws.com/agency.form.sg/ https://s3.ap-southeast-1.amazonaws.com/images.staging.form.gov.sg …
```

feat: add error handling middlewares for /api namespace

---

frontend/src/app/AppRouter.tsx
frontend/src/app/PublicElement.tsx
frontend/src/features/login/LoginPage.tsx
frontend/src/features/public-form/PublicFormPage.tsx
frontend/src/features/public-form/components/FormFooter/FormFooter.tsx
frontend/src/pages/PrivacyPolicy/PrivacyPolicyPage.stories.tsx
frontend/src/pages/PrivacyPolicy/PrivacyPolicyPage.tsx
frontend/src/pages/TermsOfUse/TermsOfUsePage.stories.tsx
frontend/src/pages/TermsOfUse/TermsOfUsePage.tsx

General cleanup PR. See changes below.
**Features**:
- feat: add `GovtMasthead` component to all public form elements
- feat: add `AppPublicHeader` to TOU and PP pages
- feat: add routing to PP and TOU routes in public form footer
**Bug Fixes**:
- fix: remove strictness from Privacy and Tou page routing
- this was erroneously preventing logged in users from accessing the privacy/tou pages

feat(v2): add GovtMasthead to PublicElement component, update PP and TOU routes

---

frontend/src/features/login/components/LoginForm.tsx
frontend/src/features/public-form/components/FormAuth/AuthImageSvgr.tsx
frontend/src/templates/Field/Table/ColumnCell.tsx

Fixes some a11y issues raised in design review of #3861 ([chromatic link](https://www.chromatic.com/build?appId=60911f69d4403b0039b266a2&number=1279)) 
**Bug Fixes**:
- fix(LoginPage): remove extra htmlFor prop 
- fix(ColumnCell): use VisuallyHidden rather than display none 
- feat(AuthImageSvgr): update auth svg to a more neutral color
Public form and login page stories should have (less) a11y violations

fix(v2): fix some uncaught a11y issues in public form, login page

---

.github/workflows/deploy-eb.yml

We need to be able to inject some variables at build time when deploying. for RUM monitoring, we need to have the monitors ready as soon as the app starts.
I have added new secrets in our project repo, and this PR activates substitutions. 
The substitutions are currently no-ops, because there is no template `@DD_API_KEY` `@DD_ENV` in code. These will be tested in in feature branches for staging deployments.

feat: inject DataDog config variable at build time

---

src/app/config/schema.ts
src/app/loaders/express/logging.ts
src/app/modules/react-migration/react-migration.controller.ts
src/types/config.ts

We need the ability to rollback from angular to react if we detect something really wrong. 
One mechanism in place to do that is to make sure the router serves angular if the rollout rate is 0 (fastest way to release).
BUT rollout also has a QA phase, where we need the rollout rate to be ZERO for public while we (OGP) are still able to access forms internally.
This PR introduces an additional priority cookie for QA that will allow us (formSG dev team) to access the react UI for forms in production, while members of the public will still 100% be on react.
Note: this adds some complexity to the dev team, the QA cookie will always takes priority if it is present, so it might confuse product ops and devs, when they try to load the UI.

feat: add a priority UI selector cookie for react rollout QA

---

frontend/src/features/public-form/components/FormFields/FormFields.tsx
frontend/src/features/public-form/components/FormFields/PublicFormSubmitButton.tsx

This PR moves the form input watcher into PublicFormSubmitButton subcomponent so that input changes will not rerender the entire FormFields component leading to terrible performance.
This perf degradation was introduced in #3813.
Oddy reminiscent of #3576 
**Bug Fixes**:
- perf: move form input watcher into PublicFormSubmitButton subcomponent
**BEFORE**:
**AFTER**:

perf(v2): improve responsiveness of public form when filling inputs (again)

---

src/app/modules/webhook/__tests__/webhook.validation.spec.ts
src/app/modules/webhook/webhook.validation.ts

fix: prevent webhook url from pointing to app subdomain

---

package-lock.json
src/app/modules/form/admin-form/__tests__/admin-form.controller.spec.ts
src/app/modules/form/admin-form/__tests__/admin-form.routes.spec.ts
src/app/modules/form/admin-form/admin-form.controller.ts
src/app/routes/api/v3/admin/forms/__tests__/admin-forms.presign.routes.spec.ts
src/public/services/FileHandlerService.ts
src/public/services/__tests__/FileHandlerService.test.ts

Fixes [#128](https://github.com/datagovsg/formsg-private/issues/128)
- Backend prefixes random string to image and logo filenames before returning presigned url, hence ensuring filename in bucket is unpredictable to client when `/presign` endpoint is first called
- Backward compatibility is ensured by setting `isNewClient` flag for the frontend, which will be removed at a later date
(this can be done by rolling back to commit `d979d0c1`)

fix: server to randomize image and logo filenames before generating presigned url

---

shared/utils/verification.ts
src/app/modules/verification/__tests__/verification.model.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/__tests__/verification.test.helpers.ts
src/app/modules/verification/verification.errors.ts
src/app/modules/verification/verification.model.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.util.ts
src/types/verification.ts

There is no limit to the number of OTPs users can request for a given transaction ID. This allows users to continually request for OTPs, which can be costly in the case of SMSes.
Enforce a limit of maximum 10 OTPs before user needs to refresh.

feat: enforce max 10 OTP requests for verified field

---

src/app/modules/verification/verification.routes.ts
src/app/routes/api/v3/forms/public-forms.verification.routes.ts
src/public/modules/forms/base/components/verifiable-field.client.component.js
src/public/modules/forms/base/directives/submit-form.directive.js

This PR adds some rate limiting to the generate txn id endpoints.
Also adds appropriate toast message, and error messages in verification box on the AngularJS app when user is rate limited.

feat: add rate limit to generate transactionId endpoint

---

src/app/modules/twilio/__tests__/twilio.controller.spec.ts
src/app/modules/twilio/twilio.controller.ts
src/app/modules/user/__tests__/user.controller.spec.ts
src/app/modules/user/user.controller.ts
src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/__tests__/verification.test.helpers.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.service.ts
src/app/modules/verification/verification.types.ts
src/app/services/sms/__tests__/sms.factory.spec.ts
src/app/services/sms/__tests__/sms.service.spec.ts
src/app/services/sms/sms.factory.ts
src/app/services/sms/sms.service.ts

- Currently, we are unable to match the sender IP address to the twilio sms delivery report
- pass sender IP address to twilio as part of query param for callback

feat: log ip address on callback from twilio

---

frontend/src/constants/localStorage.ts
frontend/src/features/admin-form/AdminFormCreatePage.stories.tsx
frontend/src/features/admin-form/create/CreatePage.tsx
frontend/src/features/admin-form/create/featureTour/FeatureTour.stories.tsx
frontend/src/features/admin-form/create/featureTour/FeatureTour.tsx
frontend/src/features/admin-form/create/featureTour/FeatureTourTooltip.tsx
frontend/src/features/login/LoginPage.stories.tsx
frontend/src/hooks/useLocalStorage.ts
frontend/src/utils/storybook.tsx

Feature tour should only be shown once to form admins.
Store a key-value pair in local storage to encapsulate information for each user on whether they have seen the feature tour before or not.

feat(v2): add logic to show feature tour only once to admins

---

frontend/src/components/Dropdown/SingleSelect/SingleSelectProvider.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditRating/EditRating.tsx

Previously, the isClearable prop only controls whether the clear button is shown. However, when one presses the escape key, the item can still be cleared.
This PR fixes that issue and prevents clearing of the item when isClearable is true.
Also sets EditRating dropdown selection to not be clearable.
Closes #3932

feat(v2/SingleSelect): prevent clearing of selected item when isClearable is true, prevent clearing of EditRating select fields

---

src/app/modules/verification/__tests__/verification.controller.spec.ts
src/app/modules/verification/verification.controller.ts
src/app/modules/verification/verification.util.ts

Currently users can call the OTP generation endpoint via API even for forms protected by SPCP/MyInfo. 
Before generating an OTP when the API is called, verify users if the form is protected by SPCP/MyInfo.

feat: add SPCP validation before generating OTP

---

shared/types/user.ts
src/app/models/user.server.model.ts
src/app/modules/user/__tests__/user.service.spec.ts
tests/unit/backend/helpers/jest-db.ts

This PR adds attribute to user collection to store user's last seen feature update date which will be used in future PRs to decide whether or not to notify users on the latest feature updates.
Closes #3985 

feat: add last seen feature update date attribute to user collection

---

src/app/modules/verification/__tests__/verification.service.spec.ts
src/app/modules/verification/__tests__/verification.test.helpers.ts
src/app/modules/verification/verification.service.ts

Currently, SMS OTP is generated for international mobile numbers even though the field from which it is requested did not allow intl numbers to be entered.
Closes #3973  
Prior to sending the SMS OTP to an intl mobile number, check if the field it was requested from allows intl numbers to be added.

feat: check if field allows intl numbers before sending intl OTP (#3973)

---

.github/workflows/deploy-eb.yml

- Updates `deploy-eb` to enable deployments to the new `staging-alt2` branch

dev: enable eb deploy for staging-alt2 branch

---

shared/types/user.ts
src/app/modules/user/__tests__/user.controller.spec.ts
src/app/modules/user/__tests__/user.service.spec.ts
src/app/modules/user/user.constant.ts
src/app/modules/user/user.controller.ts
src/app/modules/user/user.middleware.ts
src/app/modules/user/user.service.ts
src/app/routes/api/v3/user/__tests__/user.routes.spec.ts
src/app/routes/api/v3/user/user.routes.ts

Currently there is no endpoint to update user's last seen feature update date attribute which will be used to handle logic on whether or not to notify form admin users when there is a new feature update.
Closes #3986 

feat: add new user endpoint to update user last seen feature update date attribute

---

frontend/src/features/admin-form/AdminFormCreatePage.stories.tsx
frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx

MyInfo has certain restrictions on usage; this PR adds an inline mesage at the top of the myInfo tab and disable the fields when the requirements for myInfo usage is not met
Part of #3360 
1. Add myInfo specific `InlineMessage` component
1. check with design on link ref 
1. Didn't feel the need to set up a `MyInfoContext` as there is only 1 level of prop drilling 
2. Not sure if it's possible to trigger the drawer to slide out on initial storybook render as the drawer state is in `useCreatePageSidebar` and i didn't want to expose a prop solely for storybook.

feat(form-v2): add myinfo inline messages
